"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from discourse.api_helper import APIHelper
from discourse.apis.base_api import BaseApi
from discourse.configuration import Server
from discourse.http.http_method_enum import (
    HttpMethodEnum,
)
from discourse.models.admin_users_activate_json_response import (
    AdminUsersActivateJsonResponse,
)
from discourse.models.admin_users_anonymize_json_response import (
    AdminUsersAnonymizeJsonResponse,
)
from discourse.models.admin_users_deactivate_json_response import (
    AdminUsersDeactivateJsonResponse,
)
from discourse.models.admin_users_json_response import (
    AdminUsersJsonResponse,
)
from discourse.models.admin_users_json_response_1 import (
    AdminUsersJsonResponse1,
)
from discourse.models.admin_users_json_response_2 import (
    AdminUsersJsonResponse2,
)
from discourse.models.admin_users_list_json_response import (
    AdminUsersListJsonResponse,
)
from discourse.models.admin_users_log_out_json_response import (
    AdminUsersLogOutJsonResponse,
)
from discourse.models.admin_users_silence_json_response import (
    AdminUsersSilenceJsonResponse,
)
from discourse.models.admin_users_suspend_json_response import (
    AdminUsersSuspendJsonResponse,
)
from discourse.models.directory_items_json_response import (
    DirectoryItemsJsonResponse,
)
from discourse.models.session_forgot_password_json_response import (
    SessionForgotPasswordJsonResponse,
)
from discourse.models.u_by_external_json_response import (
    UByExternalJsonResponse,
)
from discourse.models.u_emails_json_response import (
    UEmailsJsonResponse,
)
from discourse.models.u_json_response import (
    UJsonResponse,
)
from discourse.models.u_json_response_1 import (
    UJsonResponse1,
)
from discourse.models.u_preferences_avatar_pick_json_response import (
    UPreferencesAvatarPickJsonResponse,
)
from discourse.models.user_actions_json_response import (
    UserActionsJsonResponse,
)
from discourse.models.user_avatar_refresh_gravatar_json_response import (
    UserAvatarRefreshGravatarJsonResponse,
)
from discourse.models.users_json_response import (
    UsersJsonResponse,
)


class UsersApi(BaseApi):
    """A Controller to access Endpoints in the discourse API."""

    def __init__(self, config):
        """Initialize UsersApi object."""
        super(UsersApi, self).__init__(config)

    def create_user(self,
                    api_key,
                    api_username,
                    body=None):
        """Perform a POST request to /users.json.

        Args:
            api_key (str): The request header parameter.
            api_username (str): The request header parameter.
            body (UsersJsonRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. user created

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/users.json")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("Api-Key")
                .value(api_key)
                .is_required(True))
            .header_param(Parameter()
                .key("Api-Username")
                .value(api_username)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(UsersJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def get_user(self,
                 api_key,
                 api_username,
                 username):
        """Perform a GET request to /u/{username}.json.

        Args:
            api_key (str): The request header parameter.
            api_username (str): The request header parameter.
            username (str): The request template parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. user with primary group
                response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/u/{username}.json")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Api-Key")
                .value(api_key)
                .is_required(True))
            .header_param(Parameter()
                .key("Api-Username")
                .value(api_username)
                .is_required(True))
            .template_param(Parameter()
                .key("username")
                .value(username)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(UJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def update_user(self,
                    api_key,
                    api_username,
                    username,
                    body=None):
        """Perform a PUT request to /u/{username}.json.

        Args:
            api_key (str): The request header parameter.
            api_username (str): The request header parameter.
            username (str): The request template parameter.
            body (UJsonRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. user updated

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/u/{username}.json")
            .http_method(HttpMethodEnum.PUT)
            .header_param(Parameter()
                .key("Api-Key")
                .value(api_key)
                .is_required(True))
            .header_param(Parameter()
                .key("Api-Username")
                .value(api_username)
                .is_required(True))
            .template_param(Parameter()
                .key("username")
                .value(username)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(UJsonResponse1.from_dictionary)
            .is_api_response(True),
        ).execute()

    def get_user_external_id(self,
                             api_key,
                             api_username,
                             external_id):
        """Perform a GET request to /u/by-external/{external_id}.json.

        Args:
            api_key (str): The request header parameter.
            api_username (str): The request header parameter.
            external_id (str): The request template parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. user response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/u/by-external/{external_id}.json")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Api-Key")
                .value(api_key)
                .is_required(True))
            .header_param(Parameter()
                .key("Api-Username")
                .value(api_username)
                .is_required(True))
            .template_param(Parameter()
                .key("external_id")
                .value(external_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(UByExternalJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def get_user_identiy_provider_external_id(self,
                                              api_key,
                                              api_username,
                                              provider,
                                              external_id):
        """Perform a GET request to
        /u/by-external/{provider}/{external_id}.json.

        Args:
            api_key (str): The request header parameter.
            api_username (str): The request header parameter.
            provider (str): Authentication provider name. Can be found in the
                provider callback URL: `/auth/{provider}/callback`
            external_id (str): The request template parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. user response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/u/by-external/{provider}/{external_id}.json")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Api-Key")
                .value(api_key)
                .is_required(True))
            .header_param(Parameter()
                .key("Api-Username")
                .value(api_username)
                .is_required(True))
            .template_param(Parameter()
                .key("provider")
                .value(provider)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("external_id")
                .value(external_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(UByExternalJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def update_avatar(self,
                      username,
                      body=None):
        """Perform a PUT request to /u/{username}/preferences/avatar/pick.json.

        Args:
            username (str): The request template parameter.
            body (UPreferencesAvatarPickJsonRequest, optional): The request body
                parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. avatar updated

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/u/{username}/preferences/avatar/pick.json")
            .http_method(HttpMethodEnum.PUT)
            .template_param(Parameter()
                .key("username")
                .value(username)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(UPreferencesAvatarPickJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def update_email(self,
                     username,
                     body=None):
        """Perform a PUT request to /u/{username}/preferences/email.json.

        Args:
            username (str): The request template parameter.
            body (UPreferencesEmailJsonRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. email updated

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/u/{username}/preferences/email.json")
            .http_method(HttpMethodEnum.PUT)
            .template_param(Parameter()
                .key("username")
                .value(username)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .body_serializer(APIHelper.json_serialize),
        ).response(
            ResponseHandler()
            .is_api_response(True),
        ).execute()

    def update_username(self,
                        username,
                        body=None):
        """Perform a PUT request to /u/{username}/preferences/username.json.

        Args:
            username (str): The request template parameter.
            body (UPreferencesUsernameJsonRequest, optional): The request body
                parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. username updated

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/u/{username}/preferences/username.json")
            .http_method(HttpMethodEnum.PUT)
            .template_param(Parameter()
                .key("username")
                .value(username)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .body_serializer(APIHelper.json_serialize),
        ).response(
            ResponseHandler()
            .is_api_response(True),
        ).execute()

    def list_users_public(self,
                          period,
                          order,
                          asc=None,
                          page=None):
        """Perform a GET request to /directory_items.json.

        Args:
            period (Period1): The request query parameter.
            order (Order2): The request query parameter.
            asc (Asc, optional): The request query parameter.
            page (int, optional): The request query parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. directory items response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/directory_items.json")
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                .key("period")
                .value(period)
                .is_required(True))
            .query_param(Parameter()
                .key("order")
                .value(order)
                .is_required(True))
            .query_param(Parameter()
                .key("asc")
                .value(asc))
            .query_param(Parameter()
                .key("page")
                .value(page))
            .header_param(Parameter()
                .key("accept")
                .value("application/json")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DirectoryItemsJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def admin_get_user(self,
                       id):
        """Perform a GET request to /admin/users/{id}.json.

        Args:
            id (int): The request template parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin/users/{id}.json")
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(AdminUsersJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def delete_user(self,
                    id,
                    body=None):
        """Perform a DELETE request to /admin/users/{id}.json.

        Args:
            id (int): The request template parameter.
            body (AdminUsersJsonRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin/users/{id}.json")
            .http_method(HttpMethodEnum.DELETE)
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(AdminUsersJsonResponse1.from_dictionary)
            .is_api_response(True),
        ).execute()

    def activate_user(self,
                      id):
        """Perform a PUT request to /admin/users/{id}/activate.json.

        Args:
            id (int): The request template parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin/users/{id}/activate.json")
            .http_method(HttpMethodEnum.PUT)
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(AdminUsersActivateJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def deactivate_user(self,
                        id):
        """Perform a PUT request to /admin/users/{id}/deactivate.json.

        Args:
            id (int): The request template parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin/users/{id}/deactivate.json")
            .http_method(HttpMethodEnum.PUT)
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(AdminUsersDeactivateJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def suspend_user(self,
                     id,
                     body=None):
        """Perform a PUT request to /admin/users/{id}/suspend.json.

        Args:
            id (int): The request template parameter.
            body (AdminUsersSuspendJsonRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin/users/{id}/suspend.json")
            .http_method(HttpMethodEnum.PUT)
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(AdminUsersSuspendJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def silence_user(self,
                     id,
                     body=None):
        """Perform a PUT request to /admin/users/{id}/silence.json.

        Args:
            id (int): The request template parameter.
            body (AdminUsersSilenceJsonRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin/users/{id}/silence.json")
            .http_method(HttpMethodEnum.PUT)
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(AdminUsersSilenceJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def anonymize_user(self,
                       id):
        """Perform a PUT request to /admin/users/{id}/anonymize.json.

        Args:
            id (int): The request template parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin/users/{id}/anonymize.json")
            .http_method(HttpMethodEnum.PUT)
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(AdminUsersAnonymizeJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def log_out_user(self,
                     id):
        """Perform a POST request to /admin/users/{id}/log_out.json.

        Args:
            id (int): The request template parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin/users/{id}/log_out.json")
            .http_method(HttpMethodEnum.POST)
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(AdminUsersLogOutJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def refresh_gravatar(self,
                         username):
        """Perform a POST request to
        /user_avatar/{username}/refresh_gravatar.json.

        Args:
            username (str): The request template parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/user_avatar/{username}/refresh_gravatar.json")
            .http_method(HttpMethodEnum.POST)
            .template_param(Parameter()
                .key("username")
                .value(username)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(UserAvatarRefreshGravatarJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def admin_list_users(self,
                         order=None,
                         asc=None,
                         page=None,
                         show_emails=None,
                         stats=None,
                         email=None,
                         ip=None):
        """Perform a GET request to /admin/users.json.

        Args:
            order (Order3, optional): The request query parameter.
            asc (Asc, optional): The request query parameter.
            page (int, optional): The request query parameter.
            show_emails (bool, optional): Include user email addresses in response.
                These requests will be logged in the staff action logs.
            stats (bool, optional): Include user stats information
            email (str, optional): Filter to the user with this email address
            ip (str, optional): Filter to users with this IP address

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. users response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin/users.json")
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                .key("order")
                .value(order))
            .query_param(Parameter()
                .key("asc")
                .value(asc))
            .query_param(Parameter()
                .key("page")
                .value(page))
            .query_param(Parameter()
                .key("show_emails")
                .value(show_emails))
            .query_param(Parameter()
                .key("stats")
                .value(stats))
            .query_param(Parameter()
                .key("email")
                .value(email))
            .query_param(Parameter()
                .key("ip")
                .value(ip))
            .header_param(Parameter()
                .key("accept")
                .value("application/json")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(AdminUsersJsonResponse2.from_dictionary)
            .is_api_response(True),
        ).execute()

    def admin_list_users_flag(self,
                              flag,
                              order=None,
                              asc=None,
                              page=None,
                              show_emails=None,
                              stats=None,
                              email=None,
                              ip=None):
        """Perform a GET request to /admin/users/list/{flag}.json.

        Args:
            flag (Flag): The request template parameter.
            order (Order3, optional): The request query parameter.
            asc (Asc, optional): The request query parameter.
            page (int, optional): The request query parameter.
            show_emails (bool, optional): Include user email addresses in response.
                These requests will be logged in the staff action logs.
            stats (bool, optional): Include user stats information
            email (str, optional): Filter to the user with this email address
            ip (str, optional): Filter to users with this IP address

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin/users/list/{flag}.json")
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                .key("flag")
                .value(flag)
                .is_required(True)
                .should_encode(True))
            .query_param(Parameter()
                .key("order")
                .value(order))
            .query_param(Parameter()
                .key("asc")
                .value(asc))
            .query_param(Parameter()
                .key("page")
                .value(page))
            .query_param(Parameter()
                .key("show_emails")
                .value(show_emails))
            .query_param(Parameter()
                .key("stats")
                .value(stats))
            .query_param(Parameter()
                .key("email")
                .value(email))
            .query_param(Parameter()
                .key("ip")
                .value(ip))
            .header_param(Parameter()
                .key("accept")
                .value("application/json")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(AdminUsersListJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def list_user_actions(self,
                          offset,
                          username,
                          filter):
        """Perform a GET request to /user_actions.json.

        Args:
            offset (int): The request query parameter.
            username (str): The request query parameter.
            filter (str): The request query parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/user_actions.json")
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                .key("offset")
                .value(offset)
                .is_required(True))
            .query_param(Parameter()
                .key("username")
                .value(username)
                .is_required(True))
            .query_param(Parameter()
                .key("filter")
                .value(filter)
                .is_required(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(UserActionsJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def send_password_reset_email(self,
                                  body=None):
        """Perform a POST request to /session/forgot_password.json.

        Args:
            body (SessionForgotPasswordJsonRequest, optional): The request body
                parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/session/forgot_password.json")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(SessionForgotPasswordJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def change_password(self,
                        token,
                        body=None):
        """Perform a PUT request to /users/password-reset/{token}.json.

        Args:
            token (str): The request template parameter.
            body (UsersPasswordResetJsonRequest, optional): The request body
                parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/users/password-reset/{token}.json")
            .http_method(HttpMethodEnum.PUT)
            .template_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .body_serializer(APIHelper.json_serialize),
        ).response(
            ResponseHandler()
            .is_api_response(True),
        ).execute()

    def get_user_emails(self,
                        username):
        """Perform a GET request to /u/{username}/emails.json.

        Args:
            username (str): The request template parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/u/{username}/emails.json")
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                .key("username")
                .value(username)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(UEmailsJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()
