"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from apimatic_core.configurations.global_configuration import (
    GlobalConfiguration,
)
from apimatic_core.decorators.lazy_property import (
    LazyProperty,
)

from discourse.apis.backups_api import BackupsApi
from discourse.apis.badges_api import BadgesApi
from discourse.apis.base_api import BaseApi
from discourse.apis.categories_api import CategoriesApi
from discourse.apis.discourse_calendar_events_api import (
    DiscourseCalendarEventsApi,
)
from discourse.apis.groups_api import GroupsApi
from discourse.apis.invites_api import InvitesApi
from discourse.apis.notifications_api import (
    NotificationsApi,
)
from discourse.apis.posts_api import PostsApi
from discourse.apis.private_messages_api import (
    PrivateMessagesApi,
)
from discourse.apis.search_api import SearchApi
from discourse.apis.site_api import SiteApi
from discourse.apis.tags_api import TagsApi
from discourse.apis.topics_api import TopicsApi
from discourse.apis.uploads_api import UploadsApi
from discourse.apis.users_api import UsersApi
from discourse.configuration import (
    Configuration,
    Environment,
)


class DiscourseClient(object):
    """Client that provide access to the DiscourseClient APIs."""

    @LazyProperty
    def discourse_calendar_events(self):
        """Provide access to the DiscourseCalendarEventsApi endpoints."""
        return DiscourseCalendarEventsApi(self.global_configuration)

    @LazyProperty
    def backups(self):
        """Provide access to the BackupsApi endpoints."""
        return BackupsApi(self.global_configuration)

    @LazyProperty
    def badges(self):
        """Provide access to the BadgesApi endpoints."""
        return BadgesApi(self.global_configuration)

    @LazyProperty
    def categories(self):
        """Provide access to the CategoriesApi endpoints."""
        return CategoriesApi(self.global_configuration)

    @LazyProperty
    def groups(self):
        """Provide access to the GroupsApi endpoints."""
        return GroupsApi(self.global_configuration)

    @LazyProperty
    def invites(self):
        """Provide access to the InvitesApi endpoints."""
        return InvitesApi(self.global_configuration)

    @LazyProperty
    def notifications(self):
        """Provide access to the NotificationsApi endpoints."""
        return NotificationsApi(self.global_configuration)

    @LazyProperty
    def posts(self):
        """Provide access to the PostsApi endpoints."""
        return PostsApi(self.global_configuration)

    @LazyProperty
    def private_messages(self):
        """Provide access to the PrivateMessagesApi endpoints."""
        return PrivateMessagesApi(self.global_configuration)

    @LazyProperty
    def search(self):
        """Provide access to the SearchApi endpoints."""
        return SearchApi(self.global_configuration)

    @LazyProperty
    def site(self):
        """Provide access to the SiteApi endpoints."""
        return SiteApi(self.global_configuration)

    @LazyProperty
    def tags(self):
        """Provide access to the TagsApi endpoints."""
        return TagsApi(self.global_configuration)

    @LazyProperty
    def topics(self):
        """Provide access to the TopicsApi endpoints."""
        return TopicsApi(self.global_configuration)

    @LazyProperty
    def uploads(self):
        """Provide access to the UploadsApi endpoints."""
        return UploadsApi(self.global_configuration)

    @LazyProperty
    def users(self):
        """Provide access to the UsersApi endpoints."""
        return UsersApi(self.global_configuration)

    def __init__(self, http_client_instance=None,
                 override_http_client_configuration=False, http_call_back=None,
                 timeout=30, max_retries=0, backoff_factor=2,
                 retry_statuses=None, retry_methods=None, proxy_settings=None,
                 logging_configuration=None, environment=Environment.PRODUCTION,
                 default_host="discourse.example.com", config=None):
        """Initialize a new instance of DiscourseClient."""
        self.config = config or Configuration(
            http_client_instance=http_client_instance,
            override_http_client_configuration=override_http_client_configuration,
            http_call_back=http_call_back, timeout=timeout,
            max_retries=max_retries, backoff_factor=backoff_factor,
            retry_statuses=retry_statuses, retry_methods=retry_methods,
            proxy_settings=proxy_settings,
            logging_configuration=logging_configuration,
            environment=environment, default_host=default_host)

        self.global_configuration = GlobalConfiguration(self.config)\
            .global_errors(BaseApi.global_errors())\
            .base_uri_executor(self.config.get_base_uri)\
            .user_agent(BaseApi.user_agent(),
                BaseApi.user_agent_parameters())

    @classmethod
    def from_environment(cls, dotenv_path=None, **overrides):
        """Create a client instance using environment variables.

        Returns:
            DiscourseClient instance.

        """
        return cls(config=Configuration
            .from_environment(dotenv_path=dotenv_path, **overrides))
