"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class AccessControl(object):
    """Implementation of the 'AccessControl' model.

    Attributes:
        mandatory_acl (Any): The model property of type Any.
        banned_acl (Any): The model property of type Any.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mandatory_acl": "mandatory_acl",
        "banned_acl": "banned_acl",
    }

    def __init__(
        self,
        mandatory_acl=None,
        banned_acl=None):
        """Initialize a AccessControl instance."""
        # Initialize members of the class
        self.mandatory_acl = mandatory_acl
        self.banned_acl = banned_acl

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mandatory_acl =\
            dictionary.get("mandatory_acl")\
            if dictionary.get("mandatory_acl")\
                else None
        banned_acl =\
            dictionary.get("banned_acl")\
            if dictionary.get("banned_acl")\
                else None

        # Return an object of this model
        return cls(mandatory_acl,
                   banned_acl)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mandatory_acl=self.mandatory_acl
        _banned_acl=self.banned_acl
        return (
            f"{self.__class__.__name__}("
            f"mandatory_acl={_mandatory_acl!r}, "
            f"banned_acl={_banned_acl!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mandatory_acl=self.mandatory_acl
        _banned_acl=self.banned_acl
        return (
            f"{self.__class__.__name__}("
            f"mandatory_acl={_mandatory_acl!s}, "
            f"banned_acl={_banned_acl!s}, "
            f")"
        )
