"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.models.admin_badges import (
    AdminBadges,
)
from discourseapidocumentation.models.badge import (
    Badge,
)
from discourseapidocumentation.models.badge_grouping import (
    BadgeGrouping,
)
from discourseapidocumentation.models.badge_type import (
    BadgeType,
)


class AdminBadgesJsonResponse(object):
    """Implementation of the 'Admin BadgesJson Response' model.

    Attributes:
        badges (List[Badge]): The model property of type List[Badge].
        badge_types (List[BadgeType]): The model property of type List[BadgeType].
        badge_groupings (List[BadgeGrouping]): The model property of type
            List[BadgeGrouping].
        admin_badges (AdminBadges): The model property of type AdminBadges.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "badges": "badges",
        "badge_types": "badge_types",
        "badge_groupings": "badge_groupings",
        "admin_badges": "admin_badges",
    }

    def __init__(
        self,
        badges=None,
        badge_types=None,
        badge_groupings=None,
        admin_badges=None):
        """Initialize a AdminBadgesJsonResponse instance."""
        # Initialize members of the class
        self.badges = badges
        self.badge_types = badge_types
        self.badge_groupings = badge_groupings
        self.admin_badges = admin_badges

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        badges = None
        if dictionary.get("badges") is not None:
            badges = [
                Badge.from_dictionary(x)
                    for x in dictionary.get("badges")
            ]
        badge_types = None
        if dictionary.get("badge_types") is not None:
            badge_types = [
                BadgeType.from_dictionary(x)
                    for x in dictionary.get("badge_types")
            ]
        badge_groupings = None
        if dictionary.get("badge_groupings") is not None:
            badge_groupings = [
                BadgeGrouping.from_dictionary(x)
                    for x in dictionary.get("badge_groupings")
            ]
        admin_badges =\
            AdminBadges.from_dictionary(
                dictionary.get("admin_badges"))\
                if dictionary.get("admin_badges") else None

        # Return an object of this model
        return cls(badges,
                   badge_types,
                   badge_groupings,
                   admin_badges)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _badges=self.badges
        _badge_types=self.badge_types
        _badge_groupings=self.badge_groupings
        _admin_badges=self.admin_badges
        return (
            f"{self.__class__.__name__}("
            f"badges={_badges!r}, "
            f"badge_types={_badge_types!r}, "
            f"badge_groupings={_badge_groupings!r}, "
            f"admin_badges={_admin_badges!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _badges=self.badges
        _badge_types=self.badge_types
        _badge_groupings=self.badge_groupings
        _admin_badges=self.admin_badges
        return (
            f"{self.__class__.__name__}("
            f"badges={_badges!s}, "
            f"badge_types={_badge_types!s}, "
            f"badge_groupings={_badge_groupings!s}, "
            f"admin_badges={_admin_badges!s}, "
            f")"
        )
