"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class Archetype(object):
    """Implementation of the 'Archetype' model.

    Attributes:
        id (str): The model property of type str.
        name (str): The model property of type str.
        options (List[Any]): The model property of type List[Any].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "name": "name",
        "options": "options",
    }

    def __init__(
        self,
        id=None,
        name=None,
        options=None):
        """Initialize a Archetype instance."""
        # Initialize members of the class
        self.id = id
        self.name = name
        self.options = options

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        options =\
            dictionary.get("options")\
            if dictionary.get("options")\
                else None

        # Return an object of this model
        return cls(id,
                   name,
                   options)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _name=self.name
        _options=self.options
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"name={_name!r}, "
            f"options={_options!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _name=self.name
        _options=self.options
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"name={_name!s}, "
            f"options={_options!s}, "
            f")"
        )
