"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.api_helper import (
    APIHelper,
)


class BasicTopic(object):
    """Implementation of the 'BasicTopic' model.

    Attributes:
        id (int): The model property of type int.
        title (str): The model property of type str.
        fancy_title (str): The model property of type str.
        slug (str): The model property of type str.
        posts_count (int): The model property of type int.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "title": "title",
        "fancy_title": "fancy_title",
        "slug": "slug",
        "posts_count": "posts_count",
    }

    _optionals = [
        "id",
        "title",
        "fancy_title",
        "slug",
        "posts_count",
    ]

    def __init__(
        self,
        id=APIHelper.SKIP,
        title=APIHelper.SKIP,
        fancy_title=APIHelper.SKIP,
        slug=APIHelper.SKIP,
        posts_count=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a BasicTopic instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if title is not APIHelper.SKIP:
            self.title = title
        if fancy_title is not APIHelper.SKIP:
            self.fancy_title = fancy_title
        if slug is not APIHelper.SKIP:
            self.slug = slug
        if posts_count is not APIHelper.SKIP:
            self.posts_count = posts_count

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        title =\
            dictionary.get("title")\
            if dictionary.get("title")\
                else APIHelper.SKIP
        fancy_title =\
            dictionary.get("fancy_title")\
            if dictionary.get("fancy_title")\
                else APIHelper.SKIP
        slug =\
            dictionary.get("slug")\
            if dictionary.get("slug")\
                else APIHelper.SKIP
        posts_count =\
            dictionary.get("posts_count")\
            if dictionary.get("posts_count")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(id,
                   title,
                   fancy_title,
                   slug,
                   posts_count,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _fancy_title=(
            self.fancy_title
            if hasattr(self, "fancy_title")
            else None
        )
        _slug=(
            self.slug
            if hasattr(self, "slug")
            else None
        )
        _posts_count=(
            self.posts_count
            if hasattr(self, "posts_count")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"title={_title!r}, "
            f"fancy_title={_fancy_title!r}, "
            f"slug={_slug!r}, "
            f"posts_count={_posts_count!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _fancy_title=(
            self.fancy_title
            if hasattr(self, "fancy_title")
            else None
        )
        _slug=(
            self.slug
            if hasattr(self, "slug")
            else None
        )
        _posts_count=(
            self.posts_count
            if hasattr(self, "posts_count")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"title={_title!s}, "
            f"fancy_title={_fancy_title!s}, "
            f"slug={_slug!s}, "
            f"posts_count={_posts_count!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
