"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.models.category_1 import (
    Category1,
)


class CategoryList(object):
    """Implementation of the 'CategoryList' model.

    Attributes:
        can_create_category (bool): The model property of type bool.
        can_create_topic (bool): The model property of type bool.
        categories (List[Category1]): The model property of type List[Category1].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "can_create_category": "can_create_category",
        "can_create_topic": "can_create_topic",
        "categories": "categories",
    }

    def __init__(
        self,
        can_create_category=None,
        can_create_topic=None,
        categories=None):
        """Initialize a CategoryList instance."""
        # Initialize members of the class
        self.can_create_category = can_create_category
        self.can_create_topic = can_create_topic
        self.categories = categories

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        can_create_category =\
            dictionary.get("can_create_category")\
            if "can_create_category" in dictionary.keys()\
                else None
        can_create_topic =\
            dictionary.get("can_create_topic")\
            if "can_create_topic" in dictionary.keys()\
                else None
        categories = None
        if dictionary.get("categories") is not None:
            categories = [
                Category1.from_dictionary(x)
                    for x in dictionary.get("categories")
            ]

        # Return an object of this model
        return cls(can_create_category,
                   can_create_topic,
                   categories)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _can_create_category=self.can_create_category
        _can_create_topic=self.can_create_topic
        _categories=self.categories
        return (
            f"{self.__class__.__name__}("
            f"can_create_category={_can_create_category!r}, "
            f"can_create_topic={_can_create_topic!r}, "
            f"categories={_categories!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _can_create_category=self.can_create_category
        _can_create_topic=self.can_create_topic
        _categories=self.categories
        return (
            f"{self.__class__.__name__}("
            f"can_create_category={_can_create_category!s}, "
            f"can_create_topic={_can_create_topic!s}, "
            f"categories={_categories!s}, "
            f")"
        )
