"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.api_helper import (
    APIHelper,
)


class CategorySetting(object):
    """Implementation of the 'CategorySetting' model.

    Attributes:
        auto_bump_cooldown_days (int): The model property of type int.
        num_auto_bump_daily (int): The model property of type int.
        require_reply_approval (bool): The model property of type bool.
        require_topic_approval (bool): The model property of type bool.
        nested_replies_default (bool): The model property of type bool.
        topic_posting_review_mode (str): The model property of type str.
        reply_posting_review_mode (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "auto_bump_cooldown_days": "auto_bump_cooldown_days",
        "num_auto_bump_daily": "num_auto_bump_daily",
        "require_reply_approval": "require_reply_approval",
        "require_topic_approval": "require_topic_approval",
        "nested_replies_default": "nested_replies_default",
        "topic_posting_review_mode": "topic_posting_review_mode",
        "reply_posting_review_mode": "reply_posting_review_mode",
    }

    _optionals = [
        "auto_bump_cooldown_days",
        "num_auto_bump_daily",
        "require_reply_approval",
        "require_topic_approval",
        "nested_replies_default",
        "topic_posting_review_mode",
        "reply_posting_review_mode",
    ]

    _nullables = [
        "num_auto_bump_daily",
        "require_reply_approval",
        "require_topic_approval",
        "nested_replies_default",
    ]

    def __init__(
        self,
        auto_bump_cooldown_days=APIHelper.SKIP,
        num_auto_bump_daily=APIHelper.SKIP,
        require_reply_approval=APIHelper.SKIP,
        require_topic_approval=APIHelper.SKIP,
        nested_replies_default=APIHelper.SKIP,
        topic_posting_review_mode=APIHelper.SKIP,
        reply_posting_review_mode=APIHelper.SKIP):
        """Initialize a CategorySetting instance."""
        # Initialize members of the class
        if auto_bump_cooldown_days is not APIHelper.SKIP:
            self.auto_bump_cooldown_days = auto_bump_cooldown_days
        if num_auto_bump_daily is not APIHelper.SKIP:
            self.num_auto_bump_daily = num_auto_bump_daily
        if require_reply_approval is not APIHelper.SKIP:
            self.require_reply_approval = require_reply_approval
        if require_topic_approval is not APIHelper.SKIP:
            self.require_topic_approval = require_topic_approval
        if nested_replies_default is not APIHelper.SKIP:
            self.nested_replies_default = nested_replies_default
        if topic_posting_review_mode is not APIHelper.SKIP:
            self.topic_posting_review_mode = topic_posting_review_mode
        if reply_posting_review_mode is not APIHelper.SKIP:
            self.reply_posting_review_mode = reply_posting_review_mode

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        auto_bump_cooldown_days =\
            dictionary.get("auto_bump_cooldown_days")\
            if dictionary.get("auto_bump_cooldown_days")\
                else APIHelper.SKIP
        num_auto_bump_daily =\
            dictionary.get("num_auto_bump_daily")\
            if "num_auto_bump_daily" in dictionary.keys()\
                else APIHelper.SKIP
        require_reply_approval =\
            dictionary.get("require_reply_approval")\
            if "require_reply_approval" in dictionary.keys()\
                else APIHelper.SKIP
        require_topic_approval =\
            dictionary.get("require_topic_approval")\
            if "require_topic_approval" in dictionary.keys()\
                else APIHelper.SKIP
        nested_replies_default =\
            dictionary.get("nested_replies_default")\
            if "nested_replies_default" in dictionary.keys()\
                else APIHelper.SKIP
        topic_posting_review_mode =\
            dictionary.get("topic_posting_review_mode")\
            if dictionary.get("topic_posting_review_mode")\
                else APIHelper.SKIP
        reply_posting_review_mode =\
            dictionary.get("reply_posting_review_mode")\
            if dictionary.get("reply_posting_review_mode")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(auto_bump_cooldown_days,
                   num_auto_bump_daily,
                   require_reply_approval,
                   require_topic_approval,
                   nested_replies_default,
                   topic_posting_review_mode,
                   reply_posting_review_mode)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _auto_bump_cooldown_days=(
            self.auto_bump_cooldown_days
            if hasattr(self, "auto_bump_cooldown_days")
            else None
        )
        _num_auto_bump_daily=(
            self.num_auto_bump_daily
            if hasattr(self, "num_auto_bump_daily")
            else None
        )
        _require_reply_approval=(
            self.require_reply_approval
            if hasattr(self, "require_reply_approval")
            else None
        )
        _require_topic_approval=(
            self.require_topic_approval
            if hasattr(self, "require_topic_approval")
            else None
        )
        _nested_replies_default=(
            self.nested_replies_default
            if hasattr(self, "nested_replies_default")
            else None
        )
        _topic_posting_review_mode=(
            self.topic_posting_review_mode
            if hasattr(self, "topic_posting_review_mode")
            else None
        )
        _reply_posting_review_mode=(
            self.reply_posting_review_mode
            if hasattr(self, "reply_posting_review_mode")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"auto_bump_cooldown_days={_auto_bump_cooldown_days!r}, "
            f"num_auto_bump_daily={_num_auto_bump_daily!r}, "
            f"require_reply_approval={_require_reply_approval!r}, "
            f"require_topic_approval={_require_topic_approval!r}, "
            f"nested_replies_default={_nested_replies_default!r}, "
            f"topic_posting_review_mode={_topic_posting_review_mode!r}, "
            f"reply_posting_review_mode={_reply_posting_review_mode!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _auto_bump_cooldown_days=(
            self.auto_bump_cooldown_days
            if hasattr(self, "auto_bump_cooldown_days")
            else None
        )
        _num_auto_bump_daily=(
            self.num_auto_bump_daily
            if hasattr(self, "num_auto_bump_daily")
            else None
        )
        _require_reply_approval=(
            self.require_reply_approval
            if hasattr(self, "require_reply_approval")
            else None
        )
        _require_topic_approval=(
            self.require_topic_approval
            if hasattr(self, "require_topic_approval")
            else None
        )
        _nested_replies_default=(
            self.nested_replies_default
            if hasattr(self, "nested_replies_default")
            else None
        )
        _topic_posting_review_mode=(
            self.topic_posting_review_mode
            if hasattr(self, "topic_posting_review_mode")
            else None
        )
        _reply_posting_review_mode=(
            self.reply_posting_review_mode
            if hasattr(self, "reply_posting_review_mode")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"auto_bump_cooldown_days={_auto_bump_cooldown_days!s}, "
            f"num_auto_bump_daily={_num_auto_bump_daily!s}, "
            f"require_reply_approval={_require_reply_approval!s}, "
            f"require_topic_approval={_require_topic_approval!s}, "
            f"nested_replies_default={_nested_replies_default!s}, "
            f"topic_posting_review_mode={_topic_posting_review_mode!s}, "
            f"reply_posting_review_mode={_reply_posting_review_mode!s}, "
            f")"
        )
