"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.api_helper import (
    APIHelper,
)
from discourseapidocumentation.models.created_by import (
    CreatedBy,
)
from discourseapidocumentation.models.last_poster import (
    LastPoster,
)
from discourseapidocumentation.models.participant_1 import (
    Participant1,
)


class Details(object):
    """Implementation of the 'Details' model.

    Attributes:
        can_edit (bool): The model property of type bool.
        notification_level (int): The model property of type int.
        can_move_posts (bool): The model property of type bool.
        can_delete (bool): The model property of type bool.
        can_remove_allowed_users (bool): The model property of type bool.
        can_create_post (bool): The model property of type bool.
        can_reply_as_new_topic (bool): The model property of type bool.
        can_invite_to (bool): The model property of type bool.
        can_invite_via_email (bool): The model property of type bool.
        can_flag_topic (bool): The model property of type bool.
        can_convert_topic (bool): The model property of type bool.
        can_review_topic (bool): The model property of type bool.
        can_close_topic (bool): The model property of type bool.
        can_archive_topic (bool): The model property of type bool.
        can_split_merge_topic (bool): The model property of type bool.
        can_edit_staff_notes (bool): The model property of type bool.
        can_toggle_topic_visibility (bool): The model property of type bool.
        can_pin_unpin_topic (bool): The model property of type bool.
        can_banner_topic (bool): The model property of type bool.
        can_moderate_category (bool): The model property of type bool.
        can_remove_self_id (int): The model property of type int.
        participants (List[Participant1]): The model property of type
            List[Participant1].
        created_by (CreatedBy): The model property of type CreatedBy.
        last_poster (LastPoster): The model property of type LastPoster.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "can_edit": "can_edit",
        "notification_level": "notification_level",
        "can_move_posts": "can_move_posts",
        "can_delete": "can_delete",
        "can_remove_allowed_users": "can_remove_allowed_users",
        "can_create_post": "can_create_post",
        "can_reply_as_new_topic": "can_reply_as_new_topic",
        "can_convert_topic": "can_convert_topic",
        "can_review_topic": "can_review_topic",
        "can_close_topic": "can_close_topic",
        "can_archive_topic": "can_archive_topic",
        "can_split_merge_topic": "can_split_merge_topic",
        "can_edit_staff_notes": "can_edit_staff_notes",
        "can_toggle_topic_visibility": "can_toggle_topic_visibility",
        "can_pin_unpin_topic": "can_pin_unpin_topic",
        "can_moderate_category": "can_moderate_category",
        "can_remove_self_id": "can_remove_self_id",
        "created_by": "created_by",
        "last_poster": "last_poster",
        "can_invite_to": "can_invite_to",
        "can_invite_via_email": "can_invite_via_email",
        "can_flag_topic": "can_flag_topic",
        "can_banner_topic": "can_banner_topic",
        "participants": "participants",
    }

    _optionals = [
        "can_invite_to",
        "can_invite_via_email",
        "can_flag_topic",
        "can_banner_topic",
        "participants",
    ]

    def __init__(
        self,
        can_edit=None,
        notification_level=None,
        can_move_posts=None,
        can_delete=None,
        can_remove_allowed_users=None,
        can_create_post=None,
        can_reply_as_new_topic=None,
        can_convert_topic=None,
        can_review_topic=None,
        can_close_topic=None,
        can_archive_topic=None,
        can_split_merge_topic=None,
        can_edit_staff_notes=None,
        can_toggle_topic_visibility=None,
        can_pin_unpin_topic=None,
        can_moderate_category=None,
        can_remove_self_id=None,
        created_by=None,
        last_poster=None,
        can_invite_to=APIHelper.SKIP,
        can_invite_via_email=APIHelper.SKIP,
        can_flag_topic=APIHelper.SKIP,
        can_banner_topic=APIHelper.SKIP,
        participants=APIHelper.SKIP):
        """Initialize a Details instance."""
        # Initialize members of the class
        self.can_edit = can_edit
        self.notification_level = notification_level
        self.can_move_posts = can_move_posts
        self.can_delete = can_delete
        self.can_remove_allowed_users = can_remove_allowed_users
        self.can_create_post = can_create_post
        self.can_reply_as_new_topic = can_reply_as_new_topic
        if can_invite_to is not APIHelper.SKIP:
            self.can_invite_to = can_invite_to
        if can_invite_via_email is not APIHelper.SKIP:
            self.can_invite_via_email = can_invite_via_email
        if can_flag_topic is not APIHelper.SKIP:
            self.can_flag_topic = can_flag_topic
        self.can_convert_topic = can_convert_topic
        self.can_review_topic = can_review_topic
        self.can_close_topic = can_close_topic
        self.can_archive_topic = can_archive_topic
        self.can_split_merge_topic = can_split_merge_topic
        self.can_edit_staff_notes = can_edit_staff_notes
        self.can_toggle_topic_visibility = can_toggle_topic_visibility
        self.can_pin_unpin_topic = can_pin_unpin_topic
        if can_banner_topic is not APIHelper.SKIP:
            self.can_banner_topic = can_banner_topic
        self.can_moderate_category = can_moderate_category
        self.can_remove_self_id = can_remove_self_id
        if participants is not APIHelper.SKIP:
            self.participants = participants
        self.created_by = created_by
        self.last_poster = last_poster

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        can_edit =\
            dictionary.get("can_edit")\
            if "can_edit" in dictionary.keys()\
                else None
        notification_level =\
            dictionary.get("notification_level")\
            if dictionary.get("notification_level")\
                else None
        can_move_posts =\
            dictionary.get("can_move_posts")\
            if "can_move_posts" in dictionary.keys()\
                else None
        can_delete =\
            dictionary.get("can_delete")\
            if "can_delete" in dictionary.keys()\
                else None
        can_remove_allowed_users =\
            dictionary.get("can_remove_allowed_users")\
            if "can_remove_allowed_users" in dictionary.keys()\
                else None
        can_create_post =\
            dictionary.get("can_create_post")\
            if "can_create_post" in dictionary.keys()\
                else None
        can_reply_as_new_topic =\
            dictionary.get("can_reply_as_new_topic")\
            if "can_reply_as_new_topic" in dictionary.keys()\
                else None
        can_convert_topic =\
            dictionary.get("can_convert_topic")\
            if "can_convert_topic" in dictionary.keys()\
                else None
        can_review_topic =\
            dictionary.get("can_review_topic")\
            if "can_review_topic" in dictionary.keys()\
                else None
        can_close_topic =\
            dictionary.get("can_close_topic")\
            if "can_close_topic" in dictionary.keys()\
                else None
        can_archive_topic =\
            dictionary.get("can_archive_topic")\
            if "can_archive_topic" in dictionary.keys()\
                else None
        can_split_merge_topic =\
            dictionary.get("can_split_merge_topic")\
            if "can_split_merge_topic" in dictionary.keys()\
                else None
        can_edit_staff_notes =\
            dictionary.get("can_edit_staff_notes")\
            if "can_edit_staff_notes" in dictionary.keys()\
                else None
        can_toggle_topic_visibility =\
            dictionary.get("can_toggle_topic_visibility")\
            if "can_toggle_topic_visibility" in dictionary.keys()\
                else None
        can_pin_unpin_topic =\
            dictionary.get("can_pin_unpin_topic")\
            if "can_pin_unpin_topic" in dictionary.keys()\
                else None
        can_moderate_category =\
            dictionary.get("can_moderate_category")\
            if "can_moderate_category" in dictionary.keys()\
                else None
        can_remove_self_id =\
            dictionary.get("can_remove_self_id")\
            if dictionary.get("can_remove_self_id")\
                else None
        created_by =\
            CreatedBy.from_dictionary(
                dictionary.get("created_by"))\
                if dictionary.get("created_by") else None
        last_poster =\
            LastPoster.from_dictionary(
                dictionary.get("last_poster"))\
                if dictionary.get("last_poster") else None
        can_invite_to =\
            dictionary.get("can_invite_to")\
            if "can_invite_to" in dictionary.keys()\
                else APIHelper.SKIP
        can_invite_via_email =\
            dictionary.get("can_invite_via_email")\
            if "can_invite_via_email" in dictionary.keys()\
                else APIHelper.SKIP
        can_flag_topic =\
            dictionary.get("can_flag_topic")\
            if "can_flag_topic" in dictionary.keys()\
                else APIHelper.SKIP
        can_banner_topic =\
            dictionary.get("can_banner_topic")\
            if "can_banner_topic" in dictionary.keys()\
                else APIHelper.SKIP
        participants = None
        if dictionary.get("participants") is not None:
            participants = [
                Participant1.from_dictionary(x)
                    for x in dictionary.get("participants")
            ]
        else:
            participants = APIHelper.SKIP

        # Return an object of this model
        return cls(can_edit,
                   notification_level,
                   can_move_posts,
                   can_delete,
                   can_remove_allowed_users,
                   can_create_post,
                   can_reply_as_new_topic,
                   can_convert_topic,
                   can_review_topic,
                   can_close_topic,
                   can_archive_topic,
                   can_split_merge_topic,
                   can_edit_staff_notes,
                   can_toggle_topic_visibility,
                   can_pin_unpin_topic,
                   can_moderate_category,
                   can_remove_self_id,
                   created_by,
                   last_poster,
                   can_invite_to,
                   can_invite_via_email,
                   can_flag_topic,
                   can_banner_topic,
                   participants)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _can_edit=self.can_edit
        _notification_level=self.notification_level
        _can_move_posts=self.can_move_posts
        _can_delete=self.can_delete
        _can_remove_allowed_users=self.can_remove_allowed_users
        _can_create_post=self.can_create_post
        _can_reply_as_new_topic=self.can_reply_as_new_topic
        _can_invite_to=(
            self.can_invite_to
            if hasattr(self, "can_invite_to")
            else None
        )
        _can_invite_via_email=(
            self.can_invite_via_email
            if hasattr(self, "can_invite_via_email")
            else None
        )
        _can_flag_topic=(
            self.can_flag_topic
            if hasattr(self, "can_flag_topic")
            else None
        )
        _can_convert_topic=self.can_convert_topic
        _can_review_topic=self.can_review_topic
        _can_close_topic=self.can_close_topic
        _can_archive_topic=self.can_archive_topic
        _can_split_merge_topic=self.can_split_merge_topic
        _can_edit_staff_notes=self.can_edit_staff_notes
        _can_toggle_topic_visibility=self.can_toggle_topic_visibility
        _can_pin_unpin_topic=self.can_pin_unpin_topic
        _can_banner_topic=(
            self.can_banner_topic
            if hasattr(self, "can_banner_topic")
            else None
        )
        _can_moderate_category=self.can_moderate_category
        _can_remove_self_id=self.can_remove_self_id
        _participants=(
            self.participants
            if hasattr(self, "participants")
            else None
        )
        _created_by=self.created_by
        _last_poster=self.last_poster
        return (
            f"{self.__class__.__name__}("
            f"can_edit={_can_edit!r}, "
            f"notification_level={_notification_level!r}, "
            f"can_move_posts={_can_move_posts!r}, "
            f"can_delete={_can_delete!r}, "
            f"can_remove_allowed_users={_can_remove_allowed_users!r}, "
            f"can_create_post={_can_create_post!r}, "
            f"can_reply_as_new_topic={_can_reply_as_new_topic!r}, "
            f"can_invite_to={_can_invite_to!r}, "
            f"can_invite_via_email={_can_invite_via_email!r}, "
            f"can_flag_topic={_can_flag_topic!r}, "
            f"can_convert_topic={_can_convert_topic!r}, "
            f"can_review_topic={_can_review_topic!r}, "
            f"can_close_topic={_can_close_topic!r}, "
            f"can_archive_topic={_can_archive_topic!r}, "
            f"can_split_merge_topic={_can_split_merge_topic!r}, "
            f"can_edit_staff_notes={_can_edit_staff_notes!r}, "
            f"can_toggle_topic_visibility={_can_toggle_topic_visibility!r}, "
            f"can_pin_unpin_topic={_can_pin_unpin_topic!r}, "
            f"can_banner_topic={_can_banner_topic!r}, "
            f"can_moderate_category={_can_moderate_category!r}, "
            f"can_remove_self_id={_can_remove_self_id!r}, "
            f"participants={_participants!r}, "
            f"created_by={_created_by!r}, "
            f"last_poster={_last_poster!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _can_edit=self.can_edit
        _notification_level=self.notification_level
        _can_move_posts=self.can_move_posts
        _can_delete=self.can_delete
        _can_remove_allowed_users=self.can_remove_allowed_users
        _can_create_post=self.can_create_post
        _can_reply_as_new_topic=self.can_reply_as_new_topic
        _can_invite_to=(
            self.can_invite_to
            if hasattr(self, "can_invite_to")
            else None
        )
        _can_invite_via_email=(
            self.can_invite_via_email
            if hasattr(self, "can_invite_via_email")
            else None
        )
        _can_flag_topic=(
            self.can_flag_topic
            if hasattr(self, "can_flag_topic")
            else None
        )
        _can_convert_topic=self.can_convert_topic
        _can_review_topic=self.can_review_topic
        _can_close_topic=self.can_close_topic
        _can_archive_topic=self.can_archive_topic
        _can_split_merge_topic=self.can_split_merge_topic
        _can_edit_staff_notes=self.can_edit_staff_notes
        _can_toggle_topic_visibility=self.can_toggle_topic_visibility
        _can_pin_unpin_topic=self.can_pin_unpin_topic
        _can_banner_topic=(
            self.can_banner_topic
            if hasattr(self, "can_banner_topic")
            else None
        )
        _can_moderate_category=self.can_moderate_category
        _can_remove_self_id=self.can_remove_self_id
        _participants=(
            self.participants
            if hasattr(self, "participants")
            else None
        )
        _created_by=self.created_by
        _last_poster=self.last_poster
        return (
            f"{self.__class__.__name__}("
            f"can_edit={_can_edit!s}, "
            f"notification_level={_notification_level!s}, "
            f"can_move_posts={_can_move_posts!s}, "
            f"can_delete={_can_delete!s}, "
            f"can_remove_allowed_users={_can_remove_allowed_users!s}, "
            f"can_create_post={_can_create_post!s}, "
            f"can_reply_as_new_topic={_can_reply_as_new_topic!s}, "
            f"can_invite_to={_can_invite_to!s}, "
            f"can_invite_via_email={_can_invite_via_email!s}, "
            f"can_flag_topic={_can_flag_topic!s}, "
            f"can_convert_topic={_can_convert_topic!s}, "
            f"can_review_topic={_can_review_topic!s}, "
            f"can_close_topic={_can_close_topic!s}, "
            f"can_archive_topic={_can_archive_topic!s}, "
            f"can_split_merge_topic={_can_split_merge_topic!s}, "
            f"can_edit_staff_notes={_can_edit_staff_notes!s}, "
            f"can_toggle_topic_visibility={_can_toggle_topic_visibility!s}, "
            f"can_pin_unpin_topic={_can_pin_unpin_topic!s}, "
            f"can_banner_topic={_can_banner_topic!s}, "
            f"can_moderate_category={_can_moderate_category!s}, "
            f"can_remove_self_id={_can_remove_self_id!s}, "
            f"participants={_participants!s}, "
            f"created_by={_created_by!s}, "
            f"last_poster={_last_poster!s}, "
            f")"
        )
