"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.models.directory_item import (
    DirectoryItem,
)
from discourseapidocumentation.models.meta_1 import (
    Meta1,
)


class DirectoryItemsJsonResponse(object):
    """Implementation of the 'Directory ItemsJson Response' model.

    Attributes:
        directory_items (List[DirectoryItem]): The model property of type
            List[DirectoryItem].
        meta (Meta1): The model property of type Meta1.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "directory_items": "directory_items",
        "meta": "meta",
    }

    def __init__(
        self,
        directory_items=None,
        meta=None):
        """Initialize a DirectoryItemsJsonResponse instance."""
        # Initialize members of the class
        self.directory_items = directory_items
        self.meta = meta

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        directory_items = None
        if dictionary.get("directory_items") is not None:
            directory_items = [
                DirectoryItem.from_dictionary(x)
                    for x in dictionary.get("directory_items")
            ]
        meta =\
            Meta1.from_dictionary(
                dictionary.get("meta"))\
                if dictionary.get("meta") else None

        # Return an object of this model
        return cls(directory_items,
                   meta)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _directory_items=self.directory_items
        _meta=self.meta
        return (
            f"{self.__class__.__name__}("
            f"directory_items={_directory_items!r}, "
            f"meta={_meta!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _directory_items=self.directory_items
        _meta=self.meta
        return (
            f"{self.__class__.__name__}("
            f"directory_items={_directory_items!s}, "
            f"meta={_meta!s}, "
            f")"
        )
