"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.models.user_11 import (
    User11,
)


class DirectoryItem(object):
    """Implementation of the 'DirectoryItem' model.

    Attributes:
        id (int): The model property of type int.
        likes_received (int): The model property of type int.
        likes_given (int): The model property of type int.
        topics_entered (int): The model property of type int.
        topic_count (int): The model property of type int.
        post_count (int): The model property of type int.
        posts_read (int): The model property of type int.
        days_visited (int): The model property of type int.
        user (User11): The model property of type User11.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "likes_received": "likes_received",
        "likes_given": "likes_given",
        "topics_entered": "topics_entered",
        "topic_count": "topic_count",
        "post_count": "post_count",
        "posts_read": "posts_read",
        "days_visited": "days_visited",
        "user": "user",
    }

    def __init__(
        self,
        id=None,
        likes_received=None,
        likes_given=None,
        topics_entered=None,
        topic_count=None,
        post_count=None,
        posts_read=None,
        days_visited=None,
        user=None):
        """Initialize a DirectoryItem instance."""
        # Initialize members of the class
        self.id = id
        self.likes_received = likes_received
        self.likes_given = likes_given
        self.topics_entered = topics_entered
        self.topic_count = topic_count
        self.post_count = post_count
        self.posts_read = posts_read
        self.days_visited = days_visited
        self.user = user

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        likes_received =\
            dictionary.get("likes_received")\
            if dictionary.get("likes_received")\
                else None
        likes_given =\
            dictionary.get("likes_given")\
            if dictionary.get("likes_given")\
                else None
        topics_entered =\
            dictionary.get("topics_entered")\
            if dictionary.get("topics_entered")\
                else None
        topic_count =\
            dictionary.get("topic_count")\
            if dictionary.get("topic_count")\
                else None
        post_count =\
            dictionary.get("post_count")\
            if dictionary.get("post_count")\
                else None
        posts_read =\
            dictionary.get("posts_read")\
            if dictionary.get("posts_read")\
                else None
        days_visited =\
            dictionary.get("days_visited")\
            if dictionary.get("days_visited")\
                else None
        user =\
            User11.from_dictionary(
                dictionary.get("user"))\
                if dictionary.get("user") else None

        # Return an object of this model
        return cls(id,
                   likes_received,
                   likes_given,
                   topics_entered,
                   topic_count,
                   post_count,
                   posts_read,
                   days_visited,
                   user)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _likes_received=self.likes_received
        _likes_given=self.likes_given
        _topics_entered=self.topics_entered
        _topic_count=self.topic_count
        _post_count=self.post_count
        _posts_read=self.posts_read
        _days_visited=self.days_visited
        _user=self.user
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"likes_received={_likes_received!r}, "
            f"likes_given={_likes_given!r}, "
            f"topics_entered={_topics_entered!r}, "
            f"topic_count={_topic_count!r}, "
            f"post_count={_post_count!r}, "
            f"posts_read={_posts_read!r}, "
            f"days_visited={_days_visited!r}, "
            f"user={_user!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _likes_received=self.likes_received
        _likes_given=self.likes_given
        _topics_entered=self.topics_entered
        _topic_count=self.topic_count
        _post_count=self.post_count
        _posts_read=self.posts_read
        _days_visited=self.days_visited
        _user=self.user
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"likes_received={_likes_received!s}, "
            f"likes_given={_likes_given!s}, "
            f"topics_entered={_topics_entered!s}, "
            f"topic_count={_topic_count!s}, "
            f"post_count={_post_count!s}, "
            f"posts_read={_posts_read!s}, "
            f"days_visited={_days_visited!s}, "
            f"user={_user!s}, "
            f")"
        )
