"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.api_helper import (
    APIHelper,
)
from discourseapidocumentation.models.creator import (
    Creator,
)
from discourseapidocumentation.models.occurrence import (
    Occurrence,
)
from discourseapidocumentation.models.post import (
    Post,
)
from discourseapidocumentation.models.reminder import (
    Reminder,
)


class Event(object):
    """Implementation of the 'Event' model.

    Attributes:
        id (int): The model property of type int.
        category_id (int): The model property of type int.
        name (str): The model property of type str.
        recurrence (str): The model property of type str.
        recurrence_until (datetime): The model property of type datetime.
        starts_at (datetime): The model property of type datetime.
        ends_at (datetime): The model property of type datetime.
        rrule (str): The model property of type str.
        show_local_time (bool): The model property of type bool.
        timezone (str): The model property of type str.
        duration (str): The model property of type str.
        all_day (bool): The model property of type bool.
        custom_fields (Any): The model property of type Any.
        post (Post): The model property of type Post.
        occurrences (List[Occurrence]): The model property of type List[Occurrence].
        can_act_on_discourse_post_event (bool): The model property of type bool.
        can_update_attendance (bool): The model property of type bool.
        creator (Creator): The model property of type Creator.
        is_closed (bool): The model property of type bool.
        is_expired (bool): The model property of type bool.
        is_ongoing (bool): The model property of type bool.
        is_private (bool): The model property of type bool.
        is_public (bool): The model property of type bool.
        is_standalone (bool): The model property of type bool.
        minimal (bool): The model property of type bool.
        raw_invitees (List[str]): The model property of type List[str].
        reminders (List[Reminder]): The model property of type List[Reminder].
        sample_invitees (List[Any]): The model property of type List[Any].
        should_display_invitees (bool): The model property of type bool.
        stats (Any): The model property of type Any.
        status (Status): The model property of type Status.
        url (str): The model property of type str.
        description (str): The model property of type str.
        description_html (str): The model property of type str.
        location (str): The model property of type str.
        watching_invitee (Any): The model property of type Any.
        chat_enabled (bool): The model property of type bool.
        channel (Any): The model property of type Any.
        livestream (bool): The model property of type bool.
        livestream_onebox (str): The model property of type str.
        is_zoom_livestream (bool): The model property of type bool.
        max_attendees (int): The model property of type int.
        at_capacity (bool): The model property of type bool.
        image_upload (Any): The model property of type Any.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "category_id": "category_id",
        "starts_at": "starts_at",
        "ends_at": "ends_at",
        "show_local_time": "show_local_time",
        "timezone": "timezone",
        "post": "post",
        "occurrences": "occurrences",
        "can_act_on_discourse_post_event": "can_act_on_discourse_post_event",
        "can_update_attendance": "can_update_attendance",
        "is_closed": "is_closed",
        "is_expired": "is_expired",
        "is_ongoing": "is_ongoing",
        "is_private": "is_private",
        "is_public": "is_public",
        "is_standalone": "is_standalone",
        "should_display_invitees": "should_display_invitees",
        "status": "status",
        "at_capacity": "at_capacity",
        "name": "name",
        "recurrence": "recurrence",
        "recurrence_until": "recurrence_until",
        "rrule": "rrule",
        "duration": "duration",
        "all_day": "all_day",
        "custom_fields": "custom_fields",
        "creator": "creator",
        "minimal": "minimal",
        "raw_invitees": "raw_invitees",
        "reminders": "reminders",
        "sample_invitees": "sample_invitees",
        "stats": "stats",
        "url": "url",
        "description": "description",
        "description_html": "description_html",
        "location": "location",
        "watching_invitee": "watching_invitee",
        "chat_enabled": "chat_enabled",
        "channel": "channel",
        "livestream": "livestream",
        "livestream_onebox": "livestream_onebox",
        "is_zoom_livestream": "is_zoom_livestream",
        "max_attendees": "max_attendees",
        "image_upload": "image_upload",
    }

    _optionals = [
        "name",
        "recurrence",
        "recurrence_until",
        "rrule",
        "duration",
        "all_day",
        "custom_fields",
        "creator",
        "minimal",
        "raw_invitees",
        "reminders",
        "sample_invitees",
        "stats",
        "url",
        "description",
        "description_html",
        "location",
        "watching_invitee",
        "chat_enabled",
        "channel",
        "livestream",
        "livestream_onebox",
        "is_zoom_livestream",
        "max_attendees",
        "image_upload",
    ]

    _nullables = [
        "category_id",
        "name",
        "recurrence",
        "recurrence_until",
        "starts_at",
        "ends_at",
        "timezone",
        "custom_fields",
        "can_act_on_discourse_post_event",
        "can_update_attendance",
        "minimal",
        "raw_invitees",
        "description",
        "description_html",
        "location",
        "watching_invitee",
        "chat_enabled",
        "livestream_onebox",
        "max_attendees",
        "image_upload",
    ]

    def __init__(
        self,
        id=None,
        category_id=None,
        starts_at=None,
        ends_at=None,
        show_local_time=None,
        timezone=None,
        post=None,
        occurrences=None,
        can_act_on_discourse_post_event=None,
        can_update_attendance=None,
        is_closed=None,
        is_expired=None,
        is_ongoing=None,
        is_private=None,
        is_public=None,
        is_standalone=None,
        should_display_invitees=None,
        status=None,
        at_capacity=None,
        name=APIHelper.SKIP,
        recurrence=APIHelper.SKIP,
        recurrence_until=APIHelper.SKIP,
        rrule=APIHelper.SKIP,
        duration=APIHelper.SKIP,
        all_day=APIHelper.SKIP,
        custom_fields=APIHelper.SKIP,
        creator=APIHelper.SKIP,
        minimal=APIHelper.SKIP,
        raw_invitees=APIHelper.SKIP,
        reminders=APIHelper.SKIP,
        sample_invitees=APIHelper.SKIP,
        stats=APIHelper.SKIP,
        url=APIHelper.SKIP,
        description=APIHelper.SKIP,
        description_html=APIHelper.SKIP,
        location=APIHelper.SKIP,
        watching_invitee=APIHelper.SKIP,
        chat_enabled=APIHelper.SKIP,
        channel=APIHelper.SKIP,
        livestream=APIHelper.SKIP,
        livestream_onebox=APIHelper.SKIP,
        is_zoom_livestream=APIHelper.SKIP,
        max_attendees=APIHelper.SKIP,
        image_upload=APIHelper.SKIP):
        """Initialize a Event instance."""
        # Initialize members of the class
        self.id = id
        self.category_id = category_id
        if name is not APIHelper.SKIP:
            self.name = name
        if recurrence is not APIHelper.SKIP:
            self.recurrence = recurrence
        if recurrence_until is not APIHelper.SKIP:
            self.recurrence_until =\
                 APIHelper.apply_datetime_converter(
                recurrence_until, APIHelper.RFC3339DateTime)\
                 if recurrence_until else None
        self.starts_at =\
             APIHelper.apply_datetime_converter(
            starts_at, APIHelper.RFC3339DateTime)\
             if starts_at else None
        self.ends_at =\
             APIHelper.apply_datetime_converter(
            ends_at, APIHelper.RFC3339DateTime)\
             if ends_at else None
        if rrule is not APIHelper.SKIP:
            self.rrule = rrule
        self.show_local_time = show_local_time
        self.timezone = timezone
        if duration is not APIHelper.SKIP:
            self.duration = duration
        if all_day is not APIHelper.SKIP:
            self.all_day = all_day
        if custom_fields is not APIHelper.SKIP:
            self.custom_fields = custom_fields
        self.post = post
        self.occurrences = occurrences
        self.can_act_on_discourse_post_event = can_act_on_discourse_post_event
        self.can_update_attendance = can_update_attendance
        if creator is not APIHelper.SKIP:
            self.creator = creator
        self.is_closed = is_closed
        self.is_expired = is_expired
        self.is_ongoing = is_ongoing
        self.is_private = is_private
        self.is_public = is_public
        self.is_standalone = is_standalone
        if minimal is not APIHelper.SKIP:
            self.minimal = minimal
        if raw_invitees is not APIHelper.SKIP:
            self.raw_invitees = raw_invitees
        if reminders is not APIHelper.SKIP:
            self.reminders = reminders
        if sample_invitees is not APIHelper.SKIP:
            self.sample_invitees = sample_invitees
        self.should_display_invitees = should_display_invitees
        if stats is not APIHelper.SKIP:
            self.stats = stats
        self.status = status
        if url is not APIHelper.SKIP:
            self.url = url
        if description is not APIHelper.SKIP:
            self.description = description
        if description_html is not APIHelper.SKIP:
            self.description_html = description_html
        if location is not APIHelper.SKIP:
            self.location = location
        if watching_invitee is not APIHelper.SKIP:
            self.watching_invitee = watching_invitee
        if chat_enabled is not APIHelper.SKIP:
            self.chat_enabled = chat_enabled
        if channel is not APIHelper.SKIP:
            self.channel = channel
        if livestream is not APIHelper.SKIP:
            self.livestream = livestream
        if livestream_onebox is not APIHelper.SKIP:
            self.livestream_onebox = livestream_onebox
        if is_zoom_livestream is not APIHelper.SKIP:
            self.is_zoom_livestream = is_zoom_livestream
        if max_attendees is not APIHelper.SKIP:
            self.max_attendees = max_attendees
        self.at_capacity = at_capacity
        if image_upload is not APIHelper.SKIP:
            self.image_upload = image_upload

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        category_id =\
            dictionary.get("category_id")\
            if dictionary.get("category_id")\
                else None
        starts_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("starts_at")).datetime\
            if dictionary.get("starts_at") else None
        ends_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("ends_at")).datetime\
            if dictionary.get("ends_at") else None
        show_local_time =\
            dictionary.get("show_local_time")\
            if "show_local_time" in dictionary.keys()\
                else None
        timezone =\
            dictionary.get("timezone")\
            if dictionary.get("timezone")\
                else None
        post =\
            Post.from_dictionary(
                dictionary.get("post"))\
                if dictionary.get("post") else None
        occurrences = None
        if dictionary.get("occurrences") is not None:
            occurrences = [
                Occurrence.from_dictionary(x)
                    for x in dictionary.get("occurrences")
            ]
        can_act_on_discourse_post_event =\
            dictionary.get("can_act_on_discourse_post_event")\
            if "can_act_on_discourse_post_event" in dictionary.keys()\
                else None
        can_update_attendance =\
            dictionary.get("can_update_attendance")\
            if "can_update_attendance" in dictionary.keys()\
                else None
        is_closed =\
            dictionary.get("is_closed")\
            if "is_closed" in dictionary.keys()\
                else None
        is_expired =\
            dictionary.get("is_expired")\
            if "is_expired" in dictionary.keys()\
                else None
        is_ongoing =\
            dictionary.get("is_ongoing")\
            if "is_ongoing" in dictionary.keys()\
                else None
        is_private =\
            dictionary.get("is_private")\
            if "is_private" in dictionary.keys()\
                else None
        is_public =\
            dictionary.get("is_public")\
            if "is_public" in dictionary.keys()\
                else None
        is_standalone =\
            dictionary.get("is_standalone")\
            if "is_standalone" in dictionary.keys()\
                else None
        should_display_invitees =\
            dictionary.get("should_display_invitees")\
            if "should_display_invitees" in dictionary.keys()\
                else None
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else None
        at_capacity =\
            dictionary.get("at_capacity")\
            if "at_capacity" in dictionary.keys()\
                else None
        name =\
            dictionary.get("name")\
            if "name" in dictionary.keys()\
                else APIHelper.SKIP
        recurrence =\
            dictionary.get("recurrence")\
            if "recurrence" in dictionary.keys()\
                else APIHelper.SKIP
        if "recurrence_until" in dictionary.keys():
            recurrence_until = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("recurrence_until")).datetime\
                if dictionary.get("recurrence_until") else None

        else:
            recurrence_until = APIHelper.SKIP
        rrule =\
            dictionary.get("rrule")\
            if dictionary.get("rrule")\
                else APIHelper.SKIP
        duration =\
            dictionary.get("duration")\
            if dictionary.get("duration")\
                else APIHelper.SKIP
        all_day =\
            dictionary.get("all_day")\
            if "all_day" in dictionary.keys()\
                else APIHelper.SKIP
        custom_fields =\
            dictionary.get("custom_fields")\
            if "custom_fields" in dictionary.keys()\
                else APIHelper.SKIP
        creator =\
            Creator.from_dictionary(
                dictionary.get("creator"))\
                if "creator" in dictionary.keys()\
                else APIHelper.SKIP
        minimal =\
            dictionary.get("minimal")\
            if "minimal" in dictionary.keys()\
                else APIHelper.SKIP
        raw_invitees =\
            dictionary.get("raw_invitees")\
            if "raw_invitees" in dictionary.keys()\
                else APIHelper.SKIP
        reminders = None
        if dictionary.get("reminders") is not None:
            reminders = [
                Reminder.from_dictionary(x)
                    for x in dictionary.get("reminders")
            ]
        else:
            reminders = APIHelper.SKIP
        sample_invitees =\
            dictionary.get("sample_invitees")\
            if dictionary.get("sample_invitees")\
                else APIHelper.SKIP
        stats =\
            dictionary.get("stats")\
            if dictionary.get("stats")\
                else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if "description" in dictionary.keys()\
                else APIHelper.SKIP
        description_html =\
            dictionary.get("description_html")\
            if "description_html" in dictionary.keys()\
                else APIHelper.SKIP
        location =\
            dictionary.get("location")\
            if "location" in dictionary.keys()\
                else APIHelper.SKIP
        watching_invitee =\
            dictionary.get("watching_invitee")\
            if "watching_invitee" in dictionary.keys()\
                else APIHelper.SKIP
        chat_enabled =\
            dictionary.get("chat_enabled")\
            if "chat_enabled" in dictionary.keys()\
                else APIHelper.SKIP
        channel =\
            dictionary.get("channel")\
            if dictionary.get("channel")\
                else APIHelper.SKIP
        livestream =\
            dictionary.get("livestream")\
            if "livestream" in dictionary.keys()\
                else APIHelper.SKIP
        livestream_onebox =\
            dictionary.get("livestream_onebox")\
            if "livestream_onebox" in dictionary.keys()\
                else APIHelper.SKIP
        is_zoom_livestream =\
            dictionary.get("is_zoom_livestream")\
            if "is_zoom_livestream" in dictionary.keys()\
                else APIHelper.SKIP
        max_attendees =\
            dictionary.get("max_attendees")\
            if "max_attendees" in dictionary.keys()\
                else APIHelper.SKIP
        image_upload =\
            dictionary.get("image_upload")\
            if "image_upload" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(id,
                   category_id,
                   starts_at,
                   ends_at,
                   show_local_time,
                   timezone,
                   post,
                   occurrences,
                   can_act_on_discourse_post_event,
                   can_update_attendance,
                   is_closed,
                   is_expired,
                   is_ongoing,
                   is_private,
                   is_public,
                   is_standalone,
                   should_display_invitees,
                   status,
                   at_capacity,
                   name,
                   recurrence,
                   recurrence_until,
                   rrule,
                   duration,
                   all_day,
                   custom_fields,
                   creator,
                   minimal,
                   raw_invitees,
                   reminders,
                   sample_invitees,
                   stats,
                   url,
                   description,
                   description_html,
                   location,
                   watching_invitee,
                   chat_enabled,
                   channel,
                   livestream,
                   livestream_onebox,
                   is_zoom_livestream,
                   max_attendees,
                   image_upload)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _category_id=self.category_id
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _recurrence=(
            self.recurrence
            if hasattr(self, "recurrence")
            else None
        )
        _recurrence_until=(
            self.recurrence_until
            if hasattr(self, "recurrence_until")
            else None
        )
        _starts_at=self.starts_at
        _ends_at=self.ends_at
        _rrule=(
            self.rrule
            if hasattr(self, "rrule")
            else None
        )
        _show_local_time=self.show_local_time
        _timezone=self.timezone
        _duration=(
            self.duration
            if hasattr(self, "duration")
            else None
        )
        _all_day=(
            self.all_day
            if hasattr(self, "all_day")
            else None
        )
        _custom_fields=(
            self.custom_fields
            if hasattr(self, "custom_fields")
            else None
        )
        _post=self.post
        _occurrences=self.occurrences
        _can_act_on_discourse_post_event=self.can_act_on_discourse_post_event
        _can_update_attendance=self.can_update_attendance
        _creator=(
            self.creator
            if hasattr(self, "creator")
            else None
        )
        _is_closed=self.is_closed
        _is_expired=self.is_expired
        _is_ongoing=self.is_ongoing
        _is_private=self.is_private
        _is_public=self.is_public
        _is_standalone=self.is_standalone
        _minimal=(
            self.minimal
            if hasattr(self, "minimal")
            else None
        )
        _raw_invitees=(
            self.raw_invitees
            if hasattr(self, "raw_invitees")
            else None
        )
        _reminders=(
            self.reminders
            if hasattr(self, "reminders")
            else None
        )
        _sample_invitees=(
            self.sample_invitees
            if hasattr(self, "sample_invitees")
            else None
        )
        _should_display_invitees=self.should_display_invitees
        _stats=(
            self.stats
            if hasattr(self, "stats")
            else None
        )
        _status=self.status
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _description_html=(
            self.description_html
            if hasattr(self, "description_html")
            else None
        )
        _location=(
            self.location
            if hasattr(self, "location")
            else None
        )
        _watching_invitee=(
            self.watching_invitee
            if hasattr(self, "watching_invitee")
            else None
        )
        _chat_enabled=(
            self.chat_enabled
            if hasattr(self, "chat_enabled")
            else None
        )
        _channel=(
            self.channel
            if hasattr(self, "channel")
            else None
        )
        _livestream=(
            self.livestream
            if hasattr(self, "livestream")
            else None
        )
        _livestream_onebox=(
            self.livestream_onebox
            if hasattr(self, "livestream_onebox")
            else None
        )
        _is_zoom_livestream=(
            self.is_zoom_livestream
            if hasattr(self, "is_zoom_livestream")
            else None
        )
        _max_attendees=(
            self.max_attendees
            if hasattr(self, "max_attendees")
            else None
        )
        _at_capacity=self.at_capacity
        _image_upload=(
            self.image_upload
            if hasattr(self, "image_upload")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"category_id={_category_id!r}, "
            f"name={_name!r}, "
            f"recurrence={_recurrence!r}, "
            f"recurrence_until={_recurrence_until!r}, "
            f"starts_at={_starts_at!r}, "
            f"ends_at={_ends_at!r}, "
            f"rrule={_rrule!r}, "
            f"show_local_time={_show_local_time!r}, "
            f"timezone={_timezone!r}, "
            f"duration={_duration!r}, "
            f"all_day={_all_day!r}, "
            f"custom_fields={_custom_fields!r}, "
            f"post={_post!r}, "
            f"occurrences={_occurrences!r}, "
            f"can_act_on_discourse_post_event={_can_act_on_discourse_post_event!r}, "
            f"can_update_attendance={_can_update_attendance!r}, "
            f"creator={_creator!r}, "
            f"is_closed={_is_closed!r}, "
            f"is_expired={_is_expired!r}, "
            f"is_ongoing={_is_ongoing!r}, "
            f"is_private={_is_private!r}, "
            f"is_public={_is_public!r}, "
            f"is_standalone={_is_standalone!r}, "
            f"minimal={_minimal!r}, "
            f"raw_invitees={_raw_invitees!r}, "
            f"reminders={_reminders!r}, "
            f"sample_invitees={_sample_invitees!r}, "
            f"should_display_invitees={_should_display_invitees!r}, "
            f"stats={_stats!r}, "
            f"status={_status!r}, "
            f"url={_url!r}, "
            f"description={_description!r}, "
            f"description_html={_description_html!r}, "
            f"location={_location!r}, "
            f"watching_invitee={_watching_invitee!r}, "
            f"chat_enabled={_chat_enabled!r}, "
            f"channel={_channel!r}, "
            f"livestream={_livestream!r}, "
            f"livestream_onebox={_livestream_onebox!r}, "
            f"is_zoom_livestream={_is_zoom_livestream!r}, "
            f"max_attendees={_max_attendees!r}, "
            f"at_capacity={_at_capacity!r}, "
            f"image_upload={_image_upload!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _category_id=self.category_id
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _recurrence=(
            self.recurrence
            if hasattr(self, "recurrence")
            else None
        )
        _recurrence_until=(
            self.recurrence_until
            if hasattr(self, "recurrence_until")
            else None
        )
        _starts_at=self.starts_at
        _ends_at=self.ends_at
        _rrule=(
            self.rrule
            if hasattr(self, "rrule")
            else None
        )
        _show_local_time=self.show_local_time
        _timezone=self.timezone
        _duration=(
            self.duration
            if hasattr(self, "duration")
            else None
        )
        _all_day=(
            self.all_day
            if hasattr(self, "all_day")
            else None
        )
        _custom_fields=(
            self.custom_fields
            if hasattr(self, "custom_fields")
            else None
        )
        _post=self.post
        _occurrences=self.occurrences
        _can_act_on_discourse_post_event=self.can_act_on_discourse_post_event
        _can_update_attendance=self.can_update_attendance
        _creator=(
            self.creator
            if hasattr(self, "creator")
            else None
        )
        _is_closed=self.is_closed
        _is_expired=self.is_expired
        _is_ongoing=self.is_ongoing
        _is_private=self.is_private
        _is_public=self.is_public
        _is_standalone=self.is_standalone
        _minimal=(
            self.minimal
            if hasattr(self, "minimal")
            else None
        )
        _raw_invitees=(
            self.raw_invitees
            if hasattr(self, "raw_invitees")
            else None
        )
        _reminders=(
            self.reminders
            if hasattr(self, "reminders")
            else None
        )
        _sample_invitees=(
            self.sample_invitees
            if hasattr(self, "sample_invitees")
            else None
        )
        _should_display_invitees=self.should_display_invitees
        _stats=(
            self.stats
            if hasattr(self, "stats")
            else None
        )
        _status=self.status
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _description_html=(
            self.description_html
            if hasattr(self, "description_html")
            else None
        )
        _location=(
            self.location
            if hasattr(self, "location")
            else None
        )
        _watching_invitee=(
            self.watching_invitee
            if hasattr(self, "watching_invitee")
            else None
        )
        _chat_enabled=(
            self.chat_enabled
            if hasattr(self, "chat_enabled")
            else None
        )
        _channel=(
            self.channel
            if hasattr(self, "channel")
            else None
        )
        _livestream=(
            self.livestream
            if hasattr(self, "livestream")
            else None
        )
        _livestream_onebox=(
            self.livestream_onebox
            if hasattr(self, "livestream_onebox")
            else None
        )
        _is_zoom_livestream=(
            self.is_zoom_livestream
            if hasattr(self, "is_zoom_livestream")
            else None
        )
        _max_attendees=(
            self.max_attendees
            if hasattr(self, "max_attendees")
            else None
        )
        _at_capacity=self.at_capacity
        _image_upload=(
            self.image_upload
            if hasattr(self, "image_upload")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"category_id={_category_id!s}, "
            f"name={_name!s}, "
            f"recurrence={_recurrence!s}, "
            f"recurrence_until={_recurrence_until!s}, "
            f"starts_at={_starts_at!s}, "
            f"ends_at={_ends_at!s}, "
            f"rrule={_rrule!s}, "
            f"show_local_time={_show_local_time!s}, "
            f"timezone={_timezone!s}, "
            f"duration={_duration!s}, "
            f"all_day={_all_day!s}, "
            f"custom_fields={_custom_fields!s}, "
            f"post={_post!s}, "
            f"occurrences={_occurrences!s}, "
            f"can_act_on_discourse_post_event={_can_act_on_discourse_post_event!s}, "
            f"can_update_attendance={_can_update_attendance!s}, "
            f"creator={_creator!s}, "
            f"is_closed={_is_closed!s}, "
            f"is_expired={_is_expired!s}, "
            f"is_ongoing={_is_ongoing!s}, "
            f"is_private={_is_private!s}, "
            f"is_public={_is_public!s}, "
            f"is_standalone={_is_standalone!s}, "
            f"minimal={_minimal!s}, "
            f"raw_invitees={_raw_invitees!s}, "
            f"reminders={_reminders!s}, "
            f"sample_invitees={_sample_invitees!s}, "
            f"should_display_invitees={_should_display_invitees!s}, "
            f"stats={_stats!s}, "
            f"status={_status!s}, "
            f"url={_url!s}, "
            f"description={_description!s}, "
            f"description_html={_description_html!s}, "
            f"location={_location!s}, "
            f"watching_invitee={_watching_invitee!s}, "
            f"chat_enabled={_chat_enabled!s}, "
            f"channel={_channel!s}, "
            f"livestream={_livestream!s}, "
            f"livestream_onebox={_livestream_onebox!s}, "
            f"is_zoom_livestream={_is_zoom_livestream!s}, "
            f"max_attendees={_max_attendees!s}, "
            f"at_capacity={_at_capacity!s}, "
            f"image_upload={_image_upload!s}, "
            f")"
        )
