"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class Extras2(object):
    """Implementation of the 'Extras2' model.

    Attributes:
        type_filters (List[Any]): The model property of type List[Any].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "type_filters": "type_filters",
    }

    def __init__(
        self,
        type_filters=None):
        """Initialize a Extras2 instance."""
        # Initialize members of the class
        self.type_filters = type_filters

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        type_filters =\
            dictionary.get("type_filters")\
            if dictionary.get("type_filters")\
                else None

        # Return an object of this model
        return cls(type_filters)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _type_filters=self.type_filters
        return (
            f"{self.__class__.__name__}("
            f"type_filters={_type_filters!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _type_filters=self.type_filters
        return (
            f"{self.__class__.__name__}("
            f"type_filters={_type_filters!s}, "
            f")"
        )
