"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class GroupPermission(object):
    """Implementation of the 'GroupPermission' model.

    Attributes:
        permission_type (int): The model property of type int.
        group_name (str): The model property of type str.
        group_id (int): The model property of type int.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "permission_type": "permission_type",
        "group_name": "group_name",
        "group_id": "group_id",
    }

    def __init__(
        self,
        permission_type=None,
        group_name=None,
        group_id=None):
        """Initialize a GroupPermission instance."""
        # Initialize members of the class
        self.permission_type = permission_type
        self.group_name = group_name
        self.group_id = group_id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        permission_type =\
            dictionary.get("permission_type")\
            if dictionary.get("permission_type")\
                else None
        group_name =\
            dictionary.get("group_name")\
            if dictionary.get("group_name")\
                else None
        group_id =\
            dictionary.get("group_id")\
            if dictionary.get("group_id")\
                else None

        # Return an object of this model
        return cls(permission_type,
                   group_name,
                   group_id)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _permission_type=self.permission_type
        _group_name=self.group_name
        _group_id=self.group_id
        return (
            f"{self.__class__.__name__}("
            f"permission_type={_permission_type!r}, "
            f"group_name={_group_name!r}, "
            f"group_id={_group_id!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _permission_type=self.permission_type
        _group_name=self.group_name
        _group_id=self.group_id
        return (
            f"{self.__class__.__name__}("
            f"permission_type={_permission_type!s}, "
            f"group_name={_group_name!s}, "
            f"group_id={_group_id!s}, "
            f")"
        )
