"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.models.member import (
    Member,
)
from discourseapidocumentation.models.meta import (
    Meta,
)
from discourseapidocumentation.models.owner import (
    Owner,
)


class GroupsMembersJsonResponse(object):
    """Implementation of the 'Groups MembersJson Response' model.

    Attributes:
        members (List[Member]): The model property of type List[Member].
        owners (List[Owner]): The model property of type List[Owner].
        meta (Meta): The model property of type Meta.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "members": "members",
        "owners": "owners",
        "meta": "meta",
    }

    def __init__(
        self,
        members=None,
        owners=None,
        meta=None):
        """Initialize a GroupsMembersJsonResponse instance."""
        # Initialize members of the class
        self.members = members
        self.owners = owners
        self.meta = meta

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        members = None
        if dictionary.get("members") is not None:
            members = [
                Member.from_dictionary(x)
                    for x in dictionary.get("members")
            ]
        owners = None
        if dictionary.get("owners") is not None:
            owners = [
                Owner.from_dictionary(x)
                    for x in dictionary.get("owners")
            ]
        meta =\
            Meta.from_dictionary(
                dictionary.get("meta"))\
                if dictionary.get("meta") else None

        # Return an object of this model
        return cls(members,
                   owners,
                   meta)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _members=self.members
        _owners=self.owners
        _meta=self.meta
        return (
            f"{self.__class__.__name__}("
            f"members={_members!r}, "
            f"owners={_owners!r}, "
            f"meta={_meta!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _members=self.members
        _owners=self.owners
        _meta=self.meta
        return (
            f"{self.__class__.__name__}("
            f"members={_members!s}, "
            f"owners={_owners!s}, "
            f"meta={_meta!s}, "
            f")"
        )
