"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.api_helper import (
    APIHelper,
)


class InvitesCreateMultipleJsonResponse(object):
    """Implementation of the 'Invites Create MultipleJson Response' model.

    Attributes:
        num_successfully_created_invitations (int): The model property of type int.
        num_failed_invitations (int): The model property of type int.
        failed_invitations (List[Any]): The model property of type List[Any].
        successful_invitations (List[Any]): The model property of type List[Any].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "num_successfully_created_invitations": "num_successfully_created_invitations",
        "num_failed_invitations": "num_failed_invitations",
        "failed_invitations": "failed_invitations",
        "successful_invitations": "successful_invitations",
    }

    _optionals = [
        "num_successfully_created_invitations",
        "num_failed_invitations",
        "failed_invitations",
        "successful_invitations",
    ]

    def __init__(
        self,
        num_successfully_created_invitations=APIHelper.SKIP,
        num_failed_invitations=APIHelper.SKIP,
        failed_invitations=APIHelper.SKIP,
        successful_invitations=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a InvitesCreateMultipleJsonResponse instance."""
        # Initialize members of the class
        if num_successfully_created_invitations is not APIHelper.SKIP:
            self.num_successfully_created_invitations =\
                 num_successfully_created_invitations
        if num_failed_invitations is not APIHelper.SKIP:
            self.num_failed_invitations = num_failed_invitations
        if failed_invitations is not APIHelper.SKIP:
            self.failed_invitations = failed_invitations
        if successful_invitations is not APIHelper.SKIP:
            self.successful_invitations = successful_invitations

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        num_successfully_created_invitations =\
            dictionary.get("num_successfully_created_invitations")\
            if dictionary.get("num_successfully_created_invitations")\
                else APIHelper.SKIP
        num_failed_invitations =\
            dictionary.get("num_failed_invitations")\
            if dictionary.get("num_failed_invitations")\
                else APIHelper.SKIP
        failed_invitations =\
            dictionary.get("failed_invitations")\
            if dictionary.get("failed_invitations")\
                else APIHelper.SKIP
        successful_invitations =\
            dictionary.get("successful_invitations")\
            if dictionary.get("successful_invitations")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(num_successfully_created_invitations,
                   num_failed_invitations,
                   failed_invitations,
                   successful_invitations,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _num_successfully_created_invitations=(
            self.num_successfully_created_invitations
            if hasattr(self, "num_successfully_created_invitations")
            else None
        )
        _num_failed_invitations=(
            self.num_failed_invitations
            if hasattr(self, "num_failed_invitations")
            else None
        )
        _failed_invitations=(
            self.failed_invitations
            if hasattr(self, "failed_invitations")
            else None
        )
        _successful_invitations=(
            self.successful_invitations
            if hasattr(self, "successful_invitations")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"num_successfully_created_invitations={_num_successfully_created_invitations!r}, "
            f"num_failed_invitations={_num_failed_invitations!r}, "
            f"failed_invitations={_failed_invitations!r}, "
            f"successful_invitations={_successful_invitations!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _num_successfully_created_invitations=(
            self.num_successfully_created_invitations
            if hasattr(self, "num_successfully_created_invitations")
            else None
        )
        _num_failed_invitations=(
            self.num_failed_invitations
            if hasattr(self, "num_failed_invitations")
            else None
        )
        _failed_invitations=(
            self.failed_invitations
            if hasattr(self, "failed_invitations")
            else None
        )
        _successful_invitations=(
            self.successful_invitations
            if hasattr(self, "successful_invitations")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"num_successfully_created_invitations={_num_successfully_created_invitations!s}, "
            f"num_failed_invitations={_num_failed_invitations!s}, "
            f"failed_invitations={_failed_invitations!s}, "
            f"successful_invitations={_successful_invitations!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
