"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class Member(object):
    """Implementation of the 'Member' model.

    Attributes:
        id (int): The model property of type int.
        username (str): The model property of type str.
        name (str): The model property of type str.
        avatar_template (str): The model property of type str.
        title (str): The model property of type str.
        last_posted_at (str): The model property of type str.
        last_seen_at (str): The model property of type str.
        added_at (str): The model property of type str.
        timezone (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "username": "username",
        "name": "name",
        "avatar_template": "avatar_template",
        "title": "title",
        "last_posted_at": "last_posted_at",
        "last_seen_at": "last_seen_at",
        "added_at": "added_at",
        "timezone": "timezone",
    }

    _nullables = [
        "name",
        "title",
    ]

    def __init__(
        self,
        id=None,
        username=None,
        name=None,
        avatar_template=None,
        title=None,
        last_posted_at=None,
        last_seen_at=None,
        added_at=None,
        timezone=None):
        """Initialize a Member instance."""
        # Initialize members of the class
        self.id = id
        self.username = username
        self.name = name
        self.avatar_template = avatar_template
        self.title = title
        self.last_posted_at = last_posted_at
        self.last_seen_at = last_seen_at
        self.added_at = added_at
        self.timezone = timezone

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        username =\
            dictionary.get("username")\
            if dictionary.get("username")\
                else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        avatar_template =\
            dictionary.get("avatar_template")\
            if dictionary.get("avatar_template")\
                else None
        title =\
            dictionary.get("title")\
            if dictionary.get("title")\
                else None
        last_posted_at =\
            dictionary.get("last_posted_at")\
            if dictionary.get("last_posted_at")\
                else None
        last_seen_at =\
            dictionary.get("last_seen_at")\
            if dictionary.get("last_seen_at")\
                else None
        added_at =\
            dictionary.get("added_at")\
            if dictionary.get("added_at")\
                else None
        timezone =\
            dictionary.get("timezone")\
            if dictionary.get("timezone")\
                else None

        # Return an object of this model
        return cls(id,
                   username,
                   name,
                   avatar_template,
                   title,
                   last_posted_at,
                   last_seen_at,
                   added_at,
                   timezone)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _username=self.username
        _name=self.name
        _avatar_template=self.avatar_template
        _title=self.title
        _last_posted_at=self.last_posted_at
        _last_seen_at=self.last_seen_at
        _added_at=self.added_at
        _timezone=self.timezone
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"username={_username!r}, "
            f"name={_name!r}, "
            f"avatar_template={_avatar_template!r}, "
            f"title={_title!r}, "
            f"last_posted_at={_last_posted_at!r}, "
            f"last_seen_at={_last_seen_at!r}, "
            f"added_at={_added_at!r}, "
            f"timezone={_timezone!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _username=self.username
        _name=self.name
        _avatar_template=self.avatar_template
        _title=self.title
        _last_posted_at=self.last_posted_at
        _last_seen_at=self.last_seen_at
        _added_at=self.added_at
        _timezone=self.timezone
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"username={_username!s}, "
            f"name={_name!s}, "
            f"avatar_template={_avatar_template!s}, "
            f"title={_title!s}, "
            f"last_posted_at={_last_posted_at!s}, "
            f"last_seen_at={_last_seen_at!s}, "
            f"added_at={_added_at!s}, "
            f"timezone={_timezone!s}, "
            f")"
        )
