"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.api_helper import (
    APIHelper,
)


class NotificationTypes(object):
    """Implementation of the 'NotificationTypes' model.

    Attributes:
        mentioned (int): The model property of type int.
        replied (int): The model property of type int.
        quoted (int): The model property of type int.
        edited (int): The model property of type int.
        liked (int): The model property of type int.
        private_message (int): The model property of type int.
        invited_to_private_message (int): The model property of type int.
        invitee_accepted (int): The model property of type int.
        posted (int): The model property of type int.
        watching_category_or_tag (int): The model property of type int.
        new_features (int): The model property of type int.
        admin_problems (int): The model property of type int.
        moved_post (int): The model property of type int.
        linked (int): The model property of type int.
        granted_badge (int): The model property of type int.
        invited_to_topic (int): The model property of type int.
        custom (int): The model property of type int.
        group_mentioned (int): The model property of type int.
        group_message_summary (int): The model property of type int.
        watching_first_post (int): The model property of type int.
        topic_reminder (int): The model property of type int.
        liked_consolidated (int): The model property of type int.
        linked_consolidated (int): The model property of type int.
        post_approved (int): The model property of type int.
        code_review_commit_approved (int): The model property of type int.
        membership_request_accepted (int): The model property of type int.
        membership_request_consolidated (int): The model property of type int.
        bookmark_reminder (int): The model property of type int.
        reaction (int): The model property of type int.
        votes_released (int): The model property of type int.
        event_reminder (int): The model property of type int.
        event_invitation (int): The model property of type int.
        chat_mention (int): The model property of type int.
        chat_message (int): The model property of type int.
        chat_invitation (int): The model property of type int.
        chat_group_mention (int): The model property of type int.
        chat_quoted (int): The model property of type int.
        chat_watched_thread (int): The model property of type int.
        upcoming_change_available (int): The model property of type int.
        upcoming_change_automatically_promoted (int): The model property of type int.
        assigned (int): The model property of type int.
        question_answer_user_commented (int): The model property of type int.
        following (int): The model property of type int.
        following_created_topic (int): The model property of type int.
        following_replied (int): The model property of type int.
        circles_activity (int): The model property of type int.
        boost (int): The model property of type int.
        suggested_edit_created (int): The model property of type int.
        suggested_edit_accepted (int): The model property of type int.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mentioned": "mentioned",
        "replied": "replied",
        "quoted": "quoted",
        "edited": "edited",
        "liked": "liked",
        "private_message": "private_message",
        "invited_to_private_message": "invited_to_private_message",
        "invitee_accepted": "invitee_accepted",
        "posted": "posted",
        "watching_category_or_tag": "watching_category_or_tag",
        "moved_post": "moved_post",
        "linked": "linked",
        "granted_badge": "granted_badge",
        "invited_to_topic": "invited_to_topic",
        "custom": "custom",
        "group_mentioned": "group_mentioned",
        "group_message_summary": "group_message_summary",
        "watching_first_post": "watching_first_post",
        "topic_reminder": "topic_reminder",
        "liked_consolidated": "liked_consolidated",
        "linked_consolidated": "linked_consolidated",
        "post_approved": "post_approved",
        "code_review_commit_approved": "code_review_commit_approved",
        "membership_request_accepted": "membership_request_accepted",
        "membership_request_consolidated": "membership_request_consolidated",
        "bookmark_reminder": "bookmark_reminder",
        "reaction": "reaction",
        "votes_released": "votes_released",
        "event_reminder": "event_reminder",
        "event_invitation": "event_invitation",
        "chat_mention": "chat_mention",
        "chat_message": "chat_message",
        "chat_invitation": "chat_invitation",
        "chat_group_mention": "chat_group_mention",
        "new_features": "new_features",
        "admin_problems": "admin_problems",
        "chat_quoted": "chat_quoted",
        "chat_watched_thread": "chat_watched_thread",
        "upcoming_change_available": "upcoming_change_available",
        "upcoming_change_automatically_promoted":
            "upcoming_change_automatically_promoted",
        "assigned": "assigned",
        "question_answer_user_commented": "question_answer_user_commented",
        "following": "following",
        "following_created_topic": "following_created_topic",
        "following_replied": "following_replied",
        "circles_activity": "circles_activity",
        "boost": "boost",
        "suggested_edit_created": "suggested_edit_created",
        "suggested_edit_accepted": "suggested_edit_accepted",
    }

    _optionals = [
        "new_features",
        "admin_problems",
        "chat_quoted",
        "chat_watched_thread",
        "upcoming_change_available",
        "upcoming_change_automatically_promoted",
        "assigned",
        "question_answer_user_commented",
        "following",
        "following_created_topic",
        "following_replied",
        "circles_activity",
        "boost",
        "suggested_edit_created",
        "suggested_edit_accepted",
    ]

    def __init__(
        self,
        mentioned=None,
        replied=None,
        quoted=None,
        edited=None,
        liked=None,
        private_message=None,
        invited_to_private_message=None,
        invitee_accepted=None,
        posted=None,
        watching_category_or_tag=None,
        moved_post=None,
        linked=None,
        granted_badge=None,
        invited_to_topic=None,
        custom=None,
        group_mentioned=None,
        group_message_summary=None,
        watching_first_post=None,
        topic_reminder=None,
        liked_consolidated=None,
        linked_consolidated=None,
        post_approved=None,
        code_review_commit_approved=None,
        membership_request_accepted=None,
        membership_request_consolidated=None,
        bookmark_reminder=None,
        reaction=None,
        votes_released=None,
        event_reminder=None,
        event_invitation=None,
        chat_mention=None,
        chat_message=None,
        chat_invitation=None,
        chat_group_mention=None,
        new_features=APIHelper.SKIP,
        admin_problems=APIHelper.SKIP,
        chat_quoted=APIHelper.SKIP,
        chat_watched_thread=APIHelper.SKIP,
        upcoming_change_available=APIHelper.SKIP,
        upcoming_change_automatically_promoted=APIHelper.SKIP,
        assigned=APIHelper.SKIP,
        question_answer_user_commented=APIHelper.SKIP,
        following=APIHelper.SKIP,
        following_created_topic=APIHelper.SKIP,
        following_replied=APIHelper.SKIP,
        circles_activity=APIHelper.SKIP,
        boost=APIHelper.SKIP,
        suggested_edit_created=APIHelper.SKIP,
        suggested_edit_accepted=APIHelper.SKIP):
        """Initialize a NotificationTypes instance."""
        # Initialize members of the class
        self.mentioned = mentioned
        self.replied = replied
        self.quoted = quoted
        self.edited = edited
        self.liked = liked
        self.private_message = private_message
        self.invited_to_private_message = invited_to_private_message
        self.invitee_accepted = invitee_accepted
        self.posted = posted
        self.watching_category_or_tag = watching_category_or_tag
        if new_features is not APIHelper.SKIP:
            self.new_features = new_features
        if admin_problems is not APIHelper.SKIP:
            self.admin_problems = admin_problems
        self.moved_post = moved_post
        self.linked = linked
        self.granted_badge = granted_badge
        self.invited_to_topic = invited_to_topic
        self.custom = custom
        self.group_mentioned = group_mentioned
        self.group_message_summary = group_message_summary
        self.watching_first_post = watching_first_post
        self.topic_reminder = topic_reminder
        self.liked_consolidated = liked_consolidated
        self.linked_consolidated = linked_consolidated
        self.post_approved = post_approved
        self.code_review_commit_approved = code_review_commit_approved
        self.membership_request_accepted = membership_request_accepted
        self.membership_request_consolidated = membership_request_consolidated
        self.bookmark_reminder = bookmark_reminder
        self.reaction = reaction
        self.votes_released = votes_released
        self.event_reminder = event_reminder
        self.event_invitation = event_invitation
        self.chat_mention = chat_mention
        self.chat_message = chat_message
        self.chat_invitation = chat_invitation
        self.chat_group_mention = chat_group_mention
        if chat_quoted is not APIHelper.SKIP:
            self.chat_quoted = chat_quoted
        if chat_watched_thread is not APIHelper.SKIP:
            self.chat_watched_thread = chat_watched_thread
        if upcoming_change_available is not APIHelper.SKIP:
            self.upcoming_change_available = upcoming_change_available
        if upcoming_change_automatically_promoted is not APIHelper.SKIP:
            self.upcoming_change_automatically_promoted =\
                 upcoming_change_automatically_promoted
        if assigned is not APIHelper.SKIP:
            self.assigned = assigned
        if question_answer_user_commented is not APIHelper.SKIP:
            self.question_answer_user_commented = question_answer_user_commented
        if following is not APIHelper.SKIP:
            self.following = following
        if following_created_topic is not APIHelper.SKIP:
            self.following_created_topic = following_created_topic
        if following_replied is not APIHelper.SKIP:
            self.following_replied = following_replied
        if circles_activity is not APIHelper.SKIP:
            self.circles_activity = circles_activity
        if boost is not APIHelper.SKIP:
            self.boost = boost
        if suggested_edit_created is not APIHelper.SKIP:
            self.suggested_edit_created = suggested_edit_created
        if suggested_edit_accepted is not APIHelper.SKIP:
            self.suggested_edit_accepted = suggested_edit_accepted

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mentioned =\
            dictionary.get("mentioned")\
            if dictionary.get("mentioned")\
                else None
        replied =\
            dictionary.get("replied")\
            if dictionary.get("replied")\
                else None
        quoted =\
            dictionary.get("quoted")\
            if dictionary.get("quoted")\
                else None
        edited =\
            dictionary.get("edited")\
            if dictionary.get("edited")\
                else None
        liked =\
            dictionary.get("liked")\
            if dictionary.get("liked")\
                else None
        private_message =\
            dictionary.get("private_message")\
            if dictionary.get("private_message")\
                else None
        invited_to_private_message =\
            dictionary.get("invited_to_private_message")\
            if dictionary.get("invited_to_private_message")\
                else None
        invitee_accepted =\
            dictionary.get("invitee_accepted")\
            if dictionary.get("invitee_accepted")\
                else None
        posted =\
            dictionary.get("posted")\
            if dictionary.get("posted")\
                else None
        watching_category_or_tag =\
            dictionary.get("watching_category_or_tag")\
            if dictionary.get("watching_category_or_tag")\
                else None
        moved_post =\
            dictionary.get("moved_post")\
            if dictionary.get("moved_post")\
                else None
        linked =\
            dictionary.get("linked")\
            if dictionary.get("linked")\
                else None
        granted_badge =\
            dictionary.get("granted_badge")\
            if dictionary.get("granted_badge")\
                else None
        invited_to_topic =\
            dictionary.get("invited_to_topic")\
            if dictionary.get("invited_to_topic")\
                else None
        custom =\
            dictionary.get("custom")\
            if dictionary.get("custom")\
                else None
        group_mentioned =\
            dictionary.get("group_mentioned")\
            if dictionary.get("group_mentioned")\
                else None
        group_message_summary =\
            dictionary.get("group_message_summary")\
            if dictionary.get("group_message_summary")\
                else None
        watching_first_post =\
            dictionary.get("watching_first_post")\
            if dictionary.get("watching_first_post")\
                else None
        topic_reminder =\
            dictionary.get("topic_reminder")\
            if dictionary.get("topic_reminder")\
                else None
        liked_consolidated =\
            dictionary.get("liked_consolidated")\
            if dictionary.get("liked_consolidated")\
                else None
        linked_consolidated =\
            dictionary.get("linked_consolidated")\
            if dictionary.get("linked_consolidated")\
                else None
        post_approved =\
            dictionary.get("post_approved")\
            if dictionary.get("post_approved")\
                else None
        code_review_commit_approved =\
            dictionary.get("code_review_commit_approved")\
            if dictionary.get("code_review_commit_approved")\
                else None
        membership_request_accepted =\
            dictionary.get("membership_request_accepted")\
            if dictionary.get("membership_request_accepted")\
                else None
        membership_request_consolidated =\
            dictionary.get("membership_request_consolidated")\
            if dictionary.get("membership_request_consolidated")\
                else None
        bookmark_reminder =\
            dictionary.get("bookmark_reminder")\
            if dictionary.get("bookmark_reminder")\
                else None
        reaction =\
            dictionary.get("reaction")\
            if dictionary.get("reaction")\
                else None
        votes_released =\
            dictionary.get("votes_released")\
            if dictionary.get("votes_released")\
                else None
        event_reminder =\
            dictionary.get("event_reminder")\
            if dictionary.get("event_reminder")\
                else None
        event_invitation =\
            dictionary.get("event_invitation")\
            if dictionary.get("event_invitation")\
                else None
        chat_mention =\
            dictionary.get("chat_mention")\
            if dictionary.get("chat_mention")\
                else None
        chat_message =\
            dictionary.get("chat_message")\
            if dictionary.get("chat_message")\
                else None
        chat_invitation =\
            dictionary.get("chat_invitation")\
            if dictionary.get("chat_invitation")\
                else None
        chat_group_mention =\
            dictionary.get("chat_group_mention")\
            if dictionary.get("chat_group_mention")\
                else None
        new_features =\
            dictionary.get("new_features")\
            if dictionary.get("new_features")\
                else APIHelper.SKIP
        admin_problems =\
            dictionary.get("admin_problems")\
            if dictionary.get("admin_problems")\
                else APIHelper.SKIP
        chat_quoted =\
            dictionary.get("chat_quoted")\
            if dictionary.get("chat_quoted")\
                else APIHelper.SKIP
        chat_watched_thread =\
            dictionary.get("chat_watched_thread")\
            if dictionary.get("chat_watched_thread")\
                else APIHelper.SKIP
        upcoming_change_available =\
            dictionary.get("upcoming_change_available")\
            if dictionary.get("upcoming_change_available")\
                else APIHelper.SKIP
        upcoming_change_automatically_promoted =\
            dictionary.get("upcoming_change_automatically_promoted")\
            if dictionary.get("upcoming_change_automatically_promoted")\
                else APIHelper.SKIP
        assigned =\
            dictionary.get("assigned")\
            if dictionary.get("assigned")\
                else APIHelper.SKIP
        question_answer_user_commented =\
            dictionary.get("question_answer_user_commented")\
            if dictionary.get("question_answer_user_commented")\
                else APIHelper.SKIP
        following =\
            dictionary.get("following")\
            if dictionary.get("following")\
                else APIHelper.SKIP
        following_created_topic =\
            dictionary.get("following_created_topic")\
            if dictionary.get("following_created_topic")\
                else APIHelper.SKIP
        following_replied =\
            dictionary.get("following_replied")\
            if dictionary.get("following_replied")\
                else APIHelper.SKIP
        circles_activity =\
            dictionary.get("circles_activity")\
            if dictionary.get("circles_activity")\
                else APIHelper.SKIP
        boost =\
            dictionary.get("boost")\
            if dictionary.get("boost")\
                else APIHelper.SKIP
        suggested_edit_created =\
            dictionary.get("suggested_edit_created")\
            if dictionary.get("suggested_edit_created")\
                else APIHelper.SKIP
        suggested_edit_accepted =\
            dictionary.get("suggested_edit_accepted")\
            if dictionary.get("suggested_edit_accepted")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(mentioned,
                   replied,
                   quoted,
                   edited,
                   liked,
                   private_message,
                   invited_to_private_message,
                   invitee_accepted,
                   posted,
                   watching_category_or_tag,
                   moved_post,
                   linked,
                   granted_badge,
                   invited_to_topic,
                   custom,
                   group_mentioned,
                   group_message_summary,
                   watching_first_post,
                   topic_reminder,
                   liked_consolidated,
                   linked_consolidated,
                   post_approved,
                   code_review_commit_approved,
                   membership_request_accepted,
                   membership_request_consolidated,
                   bookmark_reminder,
                   reaction,
                   votes_released,
                   event_reminder,
                   event_invitation,
                   chat_mention,
                   chat_message,
                   chat_invitation,
                   chat_group_mention,
                   new_features,
                   admin_problems,
                   chat_quoted,
                   chat_watched_thread,
                   upcoming_change_available,
                   upcoming_change_automatically_promoted,
                   assigned,
                   question_answer_user_commented,
                   following,
                   following_created_topic,
                   following_replied,
                   circles_activity,
                   boost,
                   suggested_edit_created,
                   suggested_edit_accepted)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mentioned=self.mentioned
        _replied=self.replied
        _quoted=self.quoted
        _edited=self.edited
        _liked=self.liked
        _private_message=self.private_message
        _invited_to_private_message=self.invited_to_private_message
        _invitee_accepted=self.invitee_accepted
        _posted=self.posted
        _watching_category_or_tag=self.watching_category_or_tag
        _new_features=(
            self.new_features
            if hasattr(self, "new_features")
            else None
        )
        _admin_problems=(
            self.admin_problems
            if hasattr(self, "admin_problems")
            else None
        )
        _moved_post=self.moved_post
        _linked=self.linked
        _granted_badge=self.granted_badge
        _invited_to_topic=self.invited_to_topic
        _custom=self.custom
        _group_mentioned=self.group_mentioned
        _group_message_summary=self.group_message_summary
        _watching_first_post=self.watching_first_post
        _topic_reminder=self.topic_reminder
        _liked_consolidated=self.liked_consolidated
        _linked_consolidated=self.linked_consolidated
        _post_approved=self.post_approved
        _code_review_commit_approved=self.code_review_commit_approved
        _membership_request_accepted=self.membership_request_accepted
        _membership_request_consolidated=self.membership_request_consolidated
        _bookmark_reminder=self.bookmark_reminder
        _reaction=self.reaction
        _votes_released=self.votes_released
        _event_reminder=self.event_reminder
        _event_invitation=self.event_invitation
        _chat_mention=self.chat_mention
        _chat_message=self.chat_message
        _chat_invitation=self.chat_invitation
        _chat_group_mention=self.chat_group_mention
        _chat_quoted=(
            self.chat_quoted
            if hasattr(self, "chat_quoted")
            else None
        )
        _chat_watched_thread=(
            self.chat_watched_thread
            if hasattr(self, "chat_watched_thread")
            else None
        )
        _upcoming_change_available=(
            self.upcoming_change_available
            if hasattr(self, "upcoming_change_available")
            else None
        )
        _upcoming_change_automatically_promoted=(
            self.upcoming_change_automatically_promoted
            if hasattr(self, "upcoming_change_automatically_promoted")
            else None
        )
        _assigned=(
            self.assigned
            if hasattr(self, "assigned")
            else None
        )
        _question_answer_user_commented=(
            self.question_answer_user_commented
            if hasattr(self, "question_answer_user_commented")
            else None
        )
        _following=(
            self.following
            if hasattr(self, "following")
            else None
        )
        _following_created_topic=(
            self.following_created_topic
            if hasattr(self, "following_created_topic")
            else None
        )
        _following_replied=(
            self.following_replied
            if hasattr(self, "following_replied")
            else None
        )
        _circles_activity=(
            self.circles_activity
            if hasattr(self, "circles_activity")
            else None
        )
        _boost=(
            self.boost
            if hasattr(self, "boost")
            else None
        )
        _suggested_edit_created=(
            self.suggested_edit_created
            if hasattr(self, "suggested_edit_created")
            else None
        )
        _suggested_edit_accepted=(
            self.suggested_edit_accepted
            if hasattr(self, "suggested_edit_accepted")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"mentioned={_mentioned!r}, "
            f"replied={_replied!r}, "
            f"quoted={_quoted!r}, "
            f"edited={_edited!r}, "
            f"liked={_liked!r}, "
            f"private_message={_private_message!r}, "
            f"invited_to_private_message={_invited_to_private_message!r}, "
            f"invitee_accepted={_invitee_accepted!r}, "
            f"posted={_posted!r}, "
            f"watching_category_or_tag={_watching_category_or_tag!r}, "
            f"new_features={_new_features!r}, "
            f"admin_problems={_admin_problems!r}, "
            f"moved_post={_moved_post!r}, "
            f"linked={_linked!r}, "
            f"granted_badge={_granted_badge!r}, "
            f"invited_to_topic={_invited_to_topic!r}, "
            f"custom={_custom!r}, "
            f"group_mentioned={_group_mentioned!r}, "
            f"group_message_summary={_group_message_summary!r}, "
            f"watching_first_post={_watching_first_post!r}, "
            f"topic_reminder={_topic_reminder!r}, "
            f"liked_consolidated={_liked_consolidated!r}, "
            f"linked_consolidated={_linked_consolidated!r}, "
            f"post_approved={_post_approved!r}, "
            f"code_review_commit_approved={_code_review_commit_approved!r}, "
            f"membership_request_accepted={_membership_request_accepted!r}, "
            f"membership_request_consolidated={_membership_request_consolidated!r}, "
            f"bookmark_reminder={_bookmark_reminder!r}, "
            f"reaction={_reaction!r}, "
            f"votes_released={_votes_released!r}, "
            f"event_reminder={_event_reminder!r}, "
            f"event_invitation={_event_invitation!r}, "
            f"chat_mention={_chat_mention!r}, "
            f"chat_message={_chat_message!r}, "
            f"chat_invitation={_chat_invitation!r}, "
            f"chat_group_mention={_chat_group_mention!r}, "
            f"chat_quoted={_chat_quoted!r}, "
            f"chat_watched_thread={_chat_watched_thread!r}, "
            f"upcoming_change_available={_upcoming_change_available!r}, "
            f"upcoming_change_automatically_promoted={_upcoming_change_automatically_promoted!r}, "
            f"assigned={_assigned!r}, "
            f"question_answer_user_commented={_question_answer_user_commented!r}, "
            f"following={_following!r}, "
            f"following_created_topic={_following_created_topic!r}, "
            f"following_replied={_following_replied!r}, "
            f"circles_activity={_circles_activity!r}, "
            f"boost={_boost!r}, "
            f"suggested_edit_created={_suggested_edit_created!r}, "
            f"suggested_edit_accepted={_suggested_edit_accepted!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mentioned=self.mentioned
        _replied=self.replied
        _quoted=self.quoted
        _edited=self.edited
        _liked=self.liked
        _private_message=self.private_message
        _invited_to_private_message=self.invited_to_private_message
        _invitee_accepted=self.invitee_accepted
        _posted=self.posted
        _watching_category_or_tag=self.watching_category_or_tag
        _new_features=(
            self.new_features
            if hasattr(self, "new_features")
            else None
        )
        _admin_problems=(
            self.admin_problems
            if hasattr(self, "admin_problems")
            else None
        )
        _moved_post=self.moved_post
        _linked=self.linked
        _granted_badge=self.granted_badge
        _invited_to_topic=self.invited_to_topic
        _custom=self.custom
        _group_mentioned=self.group_mentioned
        _group_message_summary=self.group_message_summary
        _watching_first_post=self.watching_first_post
        _topic_reminder=self.topic_reminder
        _liked_consolidated=self.liked_consolidated
        _linked_consolidated=self.linked_consolidated
        _post_approved=self.post_approved
        _code_review_commit_approved=self.code_review_commit_approved
        _membership_request_accepted=self.membership_request_accepted
        _membership_request_consolidated=self.membership_request_consolidated
        _bookmark_reminder=self.bookmark_reminder
        _reaction=self.reaction
        _votes_released=self.votes_released
        _event_reminder=self.event_reminder
        _event_invitation=self.event_invitation
        _chat_mention=self.chat_mention
        _chat_message=self.chat_message
        _chat_invitation=self.chat_invitation
        _chat_group_mention=self.chat_group_mention
        _chat_quoted=(
            self.chat_quoted
            if hasattr(self, "chat_quoted")
            else None
        )
        _chat_watched_thread=(
            self.chat_watched_thread
            if hasattr(self, "chat_watched_thread")
            else None
        )
        _upcoming_change_available=(
            self.upcoming_change_available
            if hasattr(self, "upcoming_change_available")
            else None
        )
        _upcoming_change_automatically_promoted=(
            self.upcoming_change_automatically_promoted
            if hasattr(self, "upcoming_change_automatically_promoted")
            else None
        )
        _assigned=(
            self.assigned
            if hasattr(self, "assigned")
            else None
        )
        _question_answer_user_commented=(
            self.question_answer_user_commented
            if hasattr(self, "question_answer_user_commented")
            else None
        )
        _following=(
            self.following
            if hasattr(self, "following")
            else None
        )
        _following_created_topic=(
            self.following_created_topic
            if hasattr(self, "following_created_topic")
            else None
        )
        _following_replied=(
            self.following_replied
            if hasattr(self, "following_replied")
            else None
        )
        _circles_activity=(
            self.circles_activity
            if hasattr(self, "circles_activity")
            else None
        )
        _boost=(
            self.boost
            if hasattr(self, "boost")
            else None
        )
        _suggested_edit_created=(
            self.suggested_edit_created
            if hasattr(self, "suggested_edit_created")
            else None
        )
        _suggested_edit_accepted=(
            self.suggested_edit_accepted
            if hasattr(self, "suggested_edit_accepted")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"mentioned={_mentioned!s}, "
            f"replied={_replied!s}, "
            f"quoted={_quoted!s}, "
            f"edited={_edited!s}, "
            f"liked={_liked!s}, "
            f"private_message={_private_message!s}, "
            f"invited_to_private_message={_invited_to_private_message!s}, "
            f"invitee_accepted={_invitee_accepted!s}, "
            f"posted={_posted!s}, "
            f"watching_category_or_tag={_watching_category_or_tag!s}, "
            f"new_features={_new_features!s}, "
            f"admin_problems={_admin_problems!s}, "
            f"moved_post={_moved_post!s}, "
            f"linked={_linked!s}, "
            f"granted_badge={_granted_badge!s}, "
            f"invited_to_topic={_invited_to_topic!s}, "
            f"custom={_custom!s}, "
            f"group_mentioned={_group_mentioned!s}, "
            f"group_message_summary={_group_message_summary!s}, "
            f"watching_first_post={_watching_first_post!s}, "
            f"topic_reminder={_topic_reminder!s}, "
            f"liked_consolidated={_liked_consolidated!s}, "
            f"linked_consolidated={_linked_consolidated!s}, "
            f"post_approved={_post_approved!s}, "
            f"code_review_commit_approved={_code_review_commit_approved!s}, "
            f"membership_request_accepted={_membership_request_accepted!s}, "
            f"membership_request_consolidated={_membership_request_consolidated!s}, "
            f"bookmark_reminder={_bookmark_reminder!s}, "
            f"reaction={_reaction!s}, "
            f"votes_released={_votes_released!s}, "
            f"event_reminder={_event_reminder!s}, "
            f"event_invitation={_event_invitation!s}, "
            f"chat_mention={_chat_mention!s}, "
            f"chat_message={_chat_message!s}, "
            f"chat_invitation={_chat_invitation!s}, "
            f"chat_group_mention={_chat_group_mention!s}, "
            f"chat_quoted={_chat_quoted!s}, "
            f"chat_watched_thread={_chat_watched_thread!s}, "
            f"upcoming_change_available={_upcoming_change_available!s}, "
            f"upcoming_change_automatically_promoted={_upcoming_change_automatically_promoted!s}, "
            f"assigned={_assigned!s}, "
            f"question_answer_user_commented={_question_answer_user_commented!s}, "
            f"following={_following!s}, "
            f"following_created_topic={_following_created_topic!s}, "
            f"following_replied={_following_replied!s}, "
            f"circles_activity={_circles_activity!s}, "
            f"boost={_boost!s}, "
            f"suggested_edit_created={_suggested_edit_created!s}, "
            f"suggested_edit_accepted={_suggested_edit_accepted!s}, "
            f")"
        )
