"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.api_helper import (
    APIHelper,
)


class Permissions2(object):
    """Implementation of the 'Permissions2' model.

    Attributes:
        everyone (int): The model property of type int.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "everyone": "everyone",
    }

    _optionals = [
        "everyone",
    ]

    def __init__(
        self,
        everyone=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Permissions2 instance."""
        # Initialize members of the class
        if everyone is not APIHelper.SKIP:
            self.everyone = everyone

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        everyone =\
            dictionary.get("everyone")\
            if dictionary.get("everyone")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(everyone,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _everyone=(
            self.everyone
            if hasattr(self, "everyone")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"everyone={_everyone!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _everyone=(
            self.everyone
            if hasattr(self, "everyone")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"everyone={_everyone!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
