"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.api_helper import (
    APIHelper,
)
from discourseapidocumentation.models.post_1 import (
    Post1,
)


class PostsJsonRequest1(object):
    """Implementation of the 'Posts Json Request1' model.

    Attributes:
        post (Post1): The model property of type Post1.
        bypass_bump (bool): Skip bumping the topic when updating the post. Requires
            staff or TL4 permissions.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "post": "post",
        "bypass_bump": "bypass_bump",
    }

    _optionals = [
        "post",
        "bypass_bump",
    ]

    def __init__(
        self,
        post=APIHelper.SKIP,
        bypass_bump=APIHelper.SKIP):
        """Initialize a PostsJsonRequest1 instance."""
        # Initialize members of the class
        if post is not APIHelper.SKIP:
            self.post = post
        if bypass_bump is not APIHelper.SKIP:
            self.bypass_bump = bypass_bump

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        post =\
            Post1.from_dictionary(
                dictionary.get("post"))\
                if "post" in dictionary.keys()\
                else APIHelper.SKIP
        bypass_bump =\
            dictionary.get("bypass_bump")\
            if "bypass_bump" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(post,
                   bypass_bump)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _post=(
            self.post
            if hasattr(self, "post")
            else None
        )
        _bypass_bump=(
            self.bypass_bump
            if hasattr(self, "bypass_bump")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"post={_post!r}, "
            f"bypass_bump={_bypass_bump!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _post=(
            self.post
            if hasattr(self, "post")
            else None
        )
        _bypass_bump=(
            self.bypass_bump
            if hasattr(self, "bypass_bump")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"post={_post!s}, "
            f"bypass_bump={_bypass_bump!s}, "
            f")"
        )
