"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.api_helper import (
    APIHelper,
)
from discourseapidocumentation.models.actions_summary import (
    ActionsSummary,
)
from discourseapidocumentation.models.link_count import (
    LinkCount,
)


class Post4(object):
    """Implementation of the 'Post4' model.

    Attributes:
        id (int): The model property of type int.
        name (str): The model property of type str.
        username (str): The model property of type str.
        avatar_template (str): The model property of type str.
        created_at (str): The model property of type str.
        cooked (str): The model property of type str.
        post_number (int): The model property of type int.
        post_type (int): The model property of type int.
        updated_at (str): The model property of type str.
        reply_count (int): The model property of type int.
        reply_to_post_number (str): The model property of type str.
        quote_count (int): The model property of type int.
        incoming_link_count (int): The model property of type int.
        reads (int): The model property of type int.
        readers_count (int): The model property of type int.
        score (float): The model property of type float.
        yours (bool): The model property of type bool.
        topic_id (int): The model property of type int.
        topic_slug (str): The model property of type str.
        display_username (str): The model property of type str.
        primary_group_name (str): The model property of type str.
        flair_name (str): The model property of type str.
        flair_url (str): The model property of type str.
        flair_bg_color (str): The model property of type str.
        flair_color (str): The model property of type str.
        version (int): The model property of type int.
        can_edit (bool): The model property of type bool.
        can_delete (bool): The model property of type bool.
        can_recover (bool): The model property of type bool.
        can_see_hidden_post (bool): The model property of type bool.
        can_wiki (bool): The model property of type bool.
        link_counts (List[LinkCount]): The model property of type List[LinkCount].
        read (bool): The model property of type bool.
        user_title (str): The model property of type str.
        bookmarked (bool): The model property of type bool.
        actions_summary (List[ActionsSummary]): The model property of type
            List[ActionsSummary].
        moderator (bool): The model property of type bool.
        admin (bool): The model property of type bool.
        staff (bool): The model property of type bool.
        user_id (int): The model property of type int.
        hidden (bool): The model property of type bool.
        trust_level (int): The model property of type int.
        deleted_at (str): The model property of type str.
        user_deleted (bool): The model property of type bool.
        edit_reason (str): The model property of type str.
        can_view_edit_history (bool): The model property of type bool.
        wiki (bool): The model property of type bool.
        reviewable_id (int): The model property of type int.
        reviewable_score_count (int): The model property of type int.
        reviewable_score_pending_count (int): The model property of type int.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "name": "name",
        "username": "username",
        "avatar_template": "avatar_template",
        "created_at": "created_at",
        "cooked": "cooked",
        "post_number": "post_number",
        "post_type": "post_type",
        "updated_at": "updated_at",
        "reply_count": "reply_count",
        "reply_to_post_number": "reply_to_post_number",
        "quote_count": "quote_count",
        "incoming_link_count": "incoming_link_count",
        "reads": "reads",
        "readers_count": "readers_count",
        "score": "score",
        "yours": "yours",
        "topic_id": "topic_id",
        "topic_slug": "topic_slug",
        "display_username": "display_username",
        "primary_group_name": "primary_group_name",
        "flair_name": "flair_name",
        "flair_url": "flair_url",
        "flair_bg_color": "flair_bg_color",
        "flair_color": "flair_color",
        "version": "version",
        "can_edit": "can_edit",
        "can_delete": "can_delete",
        "can_recover": "can_recover",
        "can_wiki": "can_wiki",
        "link_counts": "link_counts",
        "read": "read",
        "user_title": "user_title",
        "bookmarked": "bookmarked",
        "actions_summary": "actions_summary",
        "moderator": "moderator",
        "admin": "admin",
        "staff": "staff",
        "user_id": "user_id",
        "hidden": "hidden",
        "trust_level": "trust_level",
        "deleted_at": "deleted_at",
        "user_deleted": "user_deleted",
        "edit_reason": "edit_reason",
        "can_view_edit_history": "can_view_edit_history",
        "wiki": "wiki",
        "reviewable_id": "reviewable_id",
        "reviewable_score_count": "reviewable_score_count",
        "reviewable_score_pending_count": "reviewable_score_pending_count",
        "can_see_hidden_post": "can_see_hidden_post",
    }

    _optionals = [
        "can_see_hidden_post",
    ]

    _nullables = [
        "reply_to_post_number",
        "primary_group_name",
        "flair_name",
        "flair_url",
        "flair_bg_color",
        "flair_color",
        "user_title",
        "deleted_at",
        "edit_reason",
    ]

    def __init__(
        self,
        id=None,
        name=None,
        username=None,
        avatar_template=None,
        created_at=None,
        cooked=None,
        post_number=None,
        post_type=None,
        updated_at=None,
        reply_count=None,
        reply_to_post_number=None,
        quote_count=None,
        incoming_link_count=None,
        reads=None,
        readers_count=None,
        score=None,
        yours=None,
        topic_id=None,
        topic_slug=None,
        display_username=None,
        primary_group_name=None,
        flair_name=None,
        flair_url=None,
        flair_bg_color=None,
        flair_color=None,
        version=None,
        can_edit=None,
        can_delete=None,
        can_recover=None,
        can_wiki=None,
        link_counts=None,
        read=None,
        user_title=None,
        bookmarked=None,
        actions_summary=None,
        moderator=None,
        admin=None,
        staff=None,
        user_id=None,
        hidden=None,
        trust_level=None,
        deleted_at=None,
        user_deleted=None,
        edit_reason=None,
        can_view_edit_history=None,
        wiki=None,
        reviewable_id=None,
        reviewable_score_count=None,
        reviewable_score_pending_count=None,
        can_see_hidden_post=APIHelper.SKIP):
        """Initialize a Post4 instance."""
        # Initialize members of the class
        self.id = id
        self.name = name
        self.username = username
        self.avatar_template = avatar_template
        self.created_at = created_at
        self.cooked = cooked
        self.post_number = post_number
        self.post_type = post_type
        self.updated_at = updated_at
        self.reply_count = reply_count
        self.reply_to_post_number = reply_to_post_number
        self.quote_count = quote_count
        self.incoming_link_count = incoming_link_count
        self.reads = reads
        self.readers_count = readers_count
        self.score = score
        self.yours = yours
        self.topic_id = topic_id
        self.topic_slug = topic_slug
        self.display_username = display_username
        self.primary_group_name = primary_group_name
        self.flair_name = flair_name
        self.flair_url = flair_url
        self.flair_bg_color = flair_bg_color
        self.flair_color = flair_color
        self.version = version
        self.can_edit = can_edit
        self.can_delete = can_delete
        self.can_recover = can_recover
        if can_see_hidden_post is not APIHelper.SKIP:
            self.can_see_hidden_post = can_see_hidden_post
        self.can_wiki = can_wiki
        self.link_counts = link_counts
        self.read = read
        self.user_title = user_title
        self.bookmarked = bookmarked
        self.actions_summary = actions_summary
        self.moderator = moderator
        self.admin = admin
        self.staff = staff
        self.user_id = user_id
        self.hidden = hidden
        self.trust_level = trust_level
        self.deleted_at = deleted_at
        self.user_deleted = user_deleted
        self.edit_reason = edit_reason
        self.can_view_edit_history = can_view_edit_history
        self.wiki = wiki
        self.reviewable_id = reviewable_id
        self.reviewable_score_count = reviewable_score_count
        self.reviewable_score_pending_count = reviewable_score_pending_count

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        username =\
            dictionary.get("username")\
            if dictionary.get("username")\
                else None
        avatar_template =\
            dictionary.get("avatar_template")\
            if dictionary.get("avatar_template")\
                else None
        created_at =\
            dictionary.get("created_at")\
            if dictionary.get("created_at")\
                else None
        cooked =\
            dictionary.get("cooked")\
            if dictionary.get("cooked")\
                else None
        post_number =\
            dictionary.get("post_number")\
            if dictionary.get("post_number")\
                else None
        post_type =\
            dictionary.get("post_type")\
            if dictionary.get("post_type")\
                else None
        updated_at =\
            dictionary.get("updated_at")\
            if dictionary.get("updated_at")\
                else None
        reply_count =\
            dictionary.get("reply_count")\
            if dictionary.get("reply_count")\
                else None
        reply_to_post_number =\
            dictionary.get("reply_to_post_number")\
            if dictionary.get("reply_to_post_number")\
                else None
        quote_count =\
            dictionary.get("quote_count")\
            if dictionary.get("quote_count")\
                else None
        incoming_link_count =\
            dictionary.get("incoming_link_count")\
            if dictionary.get("incoming_link_count")\
                else None
        reads =\
            dictionary.get("reads")\
            if dictionary.get("reads")\
                else None
        readers_count =\
            dictionary.get("readers_count")\
            if dictionary.get("readers_count")\
                else None
        score =\
            dictionary.get("score")\
            if dictionary.get("score")\
                else None
        yours =\
            dictionary.get("yours")\
            if "yours" in dictionary.keys()\
                else None
        topic_id =\
            dictionary.get("topic_id")\
            if dictionary.get("topic_id")\
                else None
        topic_slug =\
            dictionary.get("topic_slug")\
            if dictionary.get("topic_slug")\
                else None
        display_username =\
            dictionary.get("display_username")\
            if dictionary.get("display_username")\
                else None
        primary_group_name =\
            dictionary.get("primary_group_name")\
            if dictionary.get("primary_group_name")\
                else None
        flair_name =\
            dictionary.get("flair_name")\
            if dictionary.get("flair_name")\
                else None
        flair_url =\
            dictionary.get("flair_url")\
            if dictionary.get("flair_url")\
                else None
        flair_bg_color =\
            dictionary.get("flair_bg_color")\
            if dictionary.get("flair_bg_color")\
                else None
        flair_color =\
            dictionary.get("flair_color")\
            if dictionary.get("flair_color")\
                else None
        version =\
            dictionary.get("version")\
            if dictionary.get("version")\
                else None
        can_edit =\
            dictionary.get("can_edit")\
            if "can_edit" in dictionary.keys()\
                else None
        can_delete =\
            dictionary.get("can_delete")\
            if "can_delete" in dictionary.keys()\
                else None
        can_recover =\
            dictionary.get("can_recover")\
            if "can_recover" in dictionary.keys()\
                else None
        can_wiki =\
            dictionary.get("can_wiki")\
            if "can_wiki" in dictionary.keys()\
                else None
        link_counts = None
        if dictionary.get("link_counts") is not None:
            link_counts = [
                LinkCount.from_dictionary(x)
                    for x in dictionary.get("link_counts")
            ]
        read =\
            dictionary.get("read")\
            if "read" in dictionary.keys()\
                else None
        user_title =\
            dictionary.get("user_title")\
            if dictionary.get("user_title")\
                else None
        bookmarked =\
            dictionary.get("bookmarked")\
            if "bookmarked" in dictionary.keys()\
                else None
        actions_summary = None
        if dictionary.get("actions_summary") is not None:
            actions_summary = [
                ActionsSummary.from_dictionary(x)
                    for x in dictionary.get("actions_summary")
            ]
        moderator =\
            dictionary.get("moderator")\
            if "moderator" in dictionary.keys()\
                else None
        admin =\
            dictionary.get("admin")\
            if "admin" in dictionary.keys()\
                else None
        staff =\
            dictionary.get("staff")\
            if "staff" in dictionary.keys()\
                else None
        user_id =\
            dictionary.get("user_id")\
            if dictionary.get("user_id")\
                else None
        hidden =\
            dictionary.get("hidden")\
            if "hidden" in dictionary.keys()\
                else None
        trust_level =\
            dictionary.get("trust_level")\
            if dictionary.get("trust_level")\
                else None
        deleted_at =\
            dictionary.get("deleted_at")\
            if dictionary.get("deleted_at")\
                else None
        user_deleted =\
            dictionary.get("user_deleted")\
            if "user_deleted" in dictionary.keys()\
                else None
        edit_reason =\
            dictionary.get("edit_reason")\
            if dictionary.get("edit_reason")\
                else None
        can_view_edit_history =\
            dictionary.get("can_view_edit_history")\
            if "can_view_edit_history" in dictionary.keys()\
                else None
        wiki =\
            dictionary.get("wiki")\
            if "wiki" in dictionary.keys()\
                else None
        reviewable_id =\
            dictionary.get("reviewable_id")\
            if dictionary.get("reviewable_id")\
                else None
        reviewable_score_count =\
            dictionary.get("reviewable_score_count")\
            if dictionary.get("reviewable_score_count")\
                else None
        reviewable_score_pending_count =\
            dictionary.get("reviewable_score_pending_count")\
            if dictionary.get("reviewable_score_pending_count")\
                else None
        can_see_hidden_post =\
            dictionary.get("can_see_hidden_post")\
            if "can_see_hidden_post" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(id,
                   name,
                   username,
                   avatar_template,
                   created_at,
                   cooked,
                   post_number,
                   post_type,
                   updated_at,
                   reply_count,
                   reply_to_post_number,
                   quote_count,
                   incoming_link_count,
                   reads,
                   readers_count,
                   score,
                   yours,
                   topic_id,
                   topic_slug,
                   display_username,
                   primary_group_name,
                   flair_name,
                   flair_url,
                   flair_bg_color,
                   flair_color,
                   version,
                   can_edit,
                   can_delete,
                   can_recover,
                   can_wiki,
                   link_counts,
                   read,
                   user_title,
                   bookmarked,
                   actions_summary,
                   moderator,
                   admin,
                   staff,
                   user_id,
                   hidden,
                   trust_level,
                   deleted_at,
                   user_deleted,
                   edit_reason,
                   can_view_edit_history,
                   wiki,
                   reviewable_id,
                   reviewable_score_count,
                   reviewable_score_pending_count,
                   can_see_hidden_post)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _name=self.name
        _username=self.username
        _avatar_template=self.avatar_template
        _created_at=self.created_at
        _cooked=self.cooked
        _post_number=self.post_number
        _post_type=self.post_type
        _updated_at=self.updated_at
        _reply_count=self.reply_count
        _reply_to_post_number=self.reply_to_post_number
        _quote_count=self.quote_count
        _incoming_link_count=self.incoming_link_count
        _reads=self.reads
        _readers_count=self.readers_count
        _score=self.score
        _yours=self.yours
        _topic_id=self.topic_id
        _topic_slug=self.topic_slug
        _display_username=self.display_username
        _primary_group_name=self.primary_group_name
        _flair_name=self.flair_name
        _flair_url=self.flair_url
        _flair_bg_color=self.flair_bg_color
        _flair_color=self.flair_color
        _version=self.version
        _can_edit=self.can_edit
        _can_delete=self.can_delete
        _can_recover=self.can_recover
        _can_see_hidden_post=(
            self.can_see_hidden_post
            if hasattr(self, "can_see_hidden_post")
            else None
        )
        _can_wiki=self.can_wiki
        _link_counts=self.link_counts
        _read=self.read
        _user_title=self.user_title
        _bookmarked=self.bookmarked
        _actions_summary=self.actions_summary
        _moderator=self.moderator
        _admin=self.admin
        _staff=self.staff
        _user_id=self.user_id
        _hidden=self.hidden
        _trust_level=self.trust_level
        _deleted_at=self.deleted_at
        _user_deleted=self.user_deleted
        _edit_reason=self.edit_reason
        _can_view_edit_history=self.can_view_edit_history
        _wiki=self.wiki
        _reviewable_id=self.reviewable_id
        _reviewable_score_count=self.reviewable_score_count
        _reviewable_score_pending_count=self.reviewable_score_pending_count
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"name={_name!r}, "
            f"username={_username!r}, "
            f"avatar_template={_avatar_template!r}, "
            f"created_at={_created_at!r}, "
            f"cooked={_cooked!r}, "
            f"post_number={_post_number!r}, "
            f"post_type={_post_type!r}, "
            f"updated_at={_updated_at!r}, "
            f"reply_count={_reply_count!r}, "
            f"reply_to_post_number={_reply_to_post_number!r}, "
            f"quote_count={_quote_count!r}, "
            f"incoming_link_count={_incoming_link_count!r}, "
            f"reads={_reads!r}, "
            f"readers_count={_readers_count!r}, "
            f"score={_score!r}, "
            f"yours={_yours!r}, "
            f"topic_id={_topic_id!r}, "
            f"topic_slug={_topic_slug!r}, "
            f"display_username={_display_username!r}, "
            f"primary_group_name={_primary_group_name!r}, "
            f"flair_name={_flair_name!r}, "
            f"flair_url={_flair_url!r}, "
            f"flair_bg_color={_flair_bg_color!r}, "
            f"flair_color={_flair_color!r}, "
            f"version={_version!r}, "
            f"can_edit={_can_edit!r}, "
            f"can_delete={_can_delete!r}, "
            f"can_recover={_can_recover!r}, "
            f"can_see_hidden_post={_can_see_hidden_post!r}, "
            f"can_wiki={_can_wiki!r}, "
            f"link_counts={_link_counts!r}, "
            f"read={_read!r}, "
            f"user_title={_user_title!r}, "
            f"bookmarked={_bookmarked!r}, "
            f"actions_summary={_actions_summary!r}, "
            f"moderator={_moderator!r}, "
            f"admin={_admin!r}, "
            f"staff={_staff!r}, "
            f"user_id={_user_id!r}, "
            f"hidden={_hidden!r}, "
            f"trust_level={_trust_level!r}, "
            f"deleted_at={_deleted_at!r}, "
            f"user_deleted={_user_deleted!r}, "
            f"edit_reason={_edit_reason!r}, "
            f"can_view_edit_history={_can_view_edit_history!r}, "
            f"wiki={_wiki!r}, "
            f"reviewable_id={_reviewable_id!r}, "
            f"reviewable_score_count={_reviewable_score_count!r}, "
            f"reviewable_score_pending_count={_reviewable_score_pending_count!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _name=self.name
        _username=self.username
        _avatar_template=self.avatar_template
        _created_at=self.created_at
        _cooked=self.cooked
        _post_number=self.post_number
        _post_type=self.post_type
        _updated_at=self.updated_at
        _reply_count=self.reply_count
        _reply_to_post_number=self.reply_to_post_number
        _quote_count=self.quote_count
        _incoming_link_count=self.incoming_link_count
        _reads=self.reads
        _readers_count=self.readers_count
        _score=self.score
        _yours=self.yours
        _topic_id=self.topic_id
        _topic_slug=self.topic_slug
        _display_username=self.display_username
        _primary_group_name=self.primary_group_name
        _flair_name=self.flair_name
        _flair_url=self.flair_url
        _flair_bg_color=self.flair_bg_color
        _flair_color=self.flair_color
        _version=self.version
        _can_edit=self.can_edit
        _can_delete=self.can_delete
        _can_recover=self.can_recover
        _can_see_hidden_post=(
            self.can_see_hidden_post
            if hasattr(self, "can_see_hidden_post")
            else None
        )
        _can_wiki=self.can_wiki
        _link_counts=self.link_counts
        _read=self.read
        _user_title=self.user_title
        _bookmarked=self.bookmarked
        _actions_summary=self.actions_summary
        _moderator=self.moderator
        _admin=self.admin
        _staff=self.staff
        _user_id=self.user_id
        _hidden=self.hidden
        _trust_level=self.trust_level
        _deleted_at=self.deleted_at
        _user_deleted=self.user_deleted
        _edit_reason=self.edit_reason
        _can_view_edit_history=self.can_view_edit_history
        _wiki=self.wiki
        _reviewable_id=self.reviewable_id
        _reviewable_score_count=self.reviewable_score_count
        _reviewable_score_pending_count=self.reviewable_score_pending_count
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"name={_name!s}, "
            f"username={_username!s}, "
            f"avatar_template={_avatar_template!s}, "
            f"created_at={_created_at!s}, "
            f"cooked={_cooked!s}, "
            f"post_number={_post_number!s}, "
            f"post_type={_post_type!s}, "
            f"updated_at={_updated_at!s}, "
            f"reply_count={_reply_count!s}, "
            f"reply_to_post_number={_reply_to_post_number!s}, "
            f"quote_count={_quote_count!s}, "
            f"incoming_link_count={_incoming_link_count!s}, "
            f"reads={_reads!s}, "
            f"readers_count={_readers_count!s}, "
            f"score={_score!s}, "
            f"yours={_yours!s}, "
            f"topic_id={_topic_id!s}, "
            f"topic_slug={_topic_slug!s}, "
            f"display_username={_display_username!s}, "
            f"primary_group_name={_primary_group_name!s}, "
            f"flair_name={_flair_name!s}, "
            f"flair_url={_flair_url!s}, "
            f"flair_bg_color={_flair_bg_color!s}, "
            f"flair_color={_flair_color!s}, "
            f"version={_version!s}, "
            f"can_edit={_can_edit!s}, "
            f"can_delete={_can_delete!s}, "
            f"can_recover={_can_recover!s}, "
            f"can_see_hidden_post={_can_see_hidden_post!s}, "
            f"can_wiki={_can_wiki!s}, "
            f"link_counts={_link_counts!s}, "
            f"read={_read!s}, "
            f"user_title={_user_title!s}, "
            f"bookmarked={_bookmarked!s}, "
            f"actions_summary={_actions_summary!s}, "
            f"moderator={_moderator!s}, "
            f"admin={_admin!s}, "
            f"staff={_staff!s}, "
            f"user_id={_user_id!s}, "
            f"hidden={_hidden!s}, "
            f"trust_level={_trust_level!s}, "
            f"deleted_at={_deleted_at!s}, "
            f"user_deleted={_user_deleted!s}, "
            f"edit_reason={_edit_reason!s}, "
            f"can_view_edit_history={_can_view_edit_history!s}, "
            f"wiki={_wiki!s}, "
            f"reviewable_id={_reviewable_id!s}, "
            f"reviewable_score_count={_reviewable_score_count!s}, "
            f"reviewable_score_pending_count={_reviewable_score_pending_count!s}, "
            f")"
        )
