"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.api_helper import (
    APIHelper,
)


class PostsJsonRequest(object):
    """Implementation of the 'PostsJson Request' model.

    Attributes:
        title (str): Required if creating a new topic or new private message.
        raw (str): The model property of type str.
        topic_id (int): Required if creating a new post.
        category (int): Optional if creating a new topic, and ignored if creating a
            new post.
        target_recipients (str): Required for private message, comma separated.
        target_usernames (str): Deprecated. Use target_recipients instead.
        archetype (str): Required for new private message.
        created_at (str): The model property of type str.
        reply_to_post_number (int): Optional, the post number to reply to inside a
            topic.
        embed_url (str): Provide a URL from a remote system to associate a forum
            topic with that URL, typically for using Discourse as a comments system
            for an external blog.
        external_id (str): Provide an external_id from a remote system to associate a
            forum topic with that id.
        auto_track (bool): If false, the user will not track the topic. By default,
            the user will track the topic.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "raw": "raw",
        "title": "title",
        "topic_id": "topic_id",
        "category": "category",
        "target_recipients": "target_recipients",
        "target_usernames": "target_usernames",
        "archetype": "archetype",
        "created_at": "created_at",
        "reply_to_post_number": "reply_to_post_number",
        "embed_url": "embed_url",
        "external_id": "external_id",
        "auto_track": "auto_track",
    }

    _optionals = [
        "title",
        "topic_id",
        "category",
        "target_recipients",
        "target_usernames",
        "archetype",
        "created_at",
        "reply_to_post_number",
        "embed_url",
        "external_id",
        "auto_track",
    ]

    def __init__(
        self,
        raw=None,
        title=APIHelper.SKIP,
        topic_id=APIHelper.SKIP,
        category=APIHelper.SKIP,
        target_recipients=APIHelper.SKIP,
        target_usernames=APIHelper.SKIP,
        archetype=APIHelper.SKIP,
        created_at=APIHelper.SKIP,
        reply_to_post_number=APIHelper.SKIP,
        embed_url=APIHelper.SKIP,
        external_id=APIHelper.SKIP,
        auto_track=APIHelper.SKIP):
        """Initialize a PostsJsonRequest instance."""
        # Initialize members of the class
        if title is not APIHelper.SKIP:
            self.title = title
        self.raw = raw
        if topic_id is not APIHelper.SKIP:
            self.topic_id = topic_id
        if category is not APIHelper.SKIP:
            self.category = category
        if target_recipients is not APIHelper.SKIP:
            self.target_recipients = target_recipients
        if target_usernames is not APIHelper.SKIP:
            self.target_usernames = target_usernames
        if archetype is not APIHelper.SKIP:
            self.archetype = archetype
        if created_at is not APIHelper.SKIP:
            self.created_at = created_at
        if reply_to_post_number is not APIHelper.SKIP:
            self.reply_to_post_number = reply_to_post_number
        if embed_url is not APIHelper.SKIP:
            self.embed_url = embed_url
        if external_id is not APIHelper.SKIP:
            self.external_id = external_id
        if auto_track is not APIHelper.SKIP:
            self.auto_track = auto_track

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        raw =\
            dictionary.get("raw")\
            if dictionary.get("raw")\
                else None
        title =\
            dictionary.get("title")\
            if dictionary.get("title")\
                else APIHelper.SKIP
        topic_id =\
            dictionary.get("topic_id")\
            if dictionary.get("topic_id")\
                else APIHelper.SKIP
        category =\
            dictionary.get("category")\
            if dictionary.get("category")\
                else APIHelper.SKIP
        target_recipients =\
            dictionary.get("target_recipients")\
            if dictionary.get("target_recipients")\
                else APIHelper.SKIP
        target_usernames =\
            dictionary.get("target_usernames")\
            if dictionary.get("target_usernames")\
                else APIHelper.SKIP
        archetype =\
            dictionary.get("archetype")\
            if dictionary.get("archetype")\
                else APIHelper.SKIP
        created_at =\
            dictionary.get("created_at")\
            if dictionary.get("created_at")\
                else APIHelper.SKIP
        reply_to_post_number =\
            dictionary.get("reply_to_post_number")\
            if dictionary.get("reply_to_post_number")\
                else APIHelper.SKIP
        embed_url =\
            dictionary.get("embed_url")\
            if dictionary.get("embed_url")\
                else APIHelper.SKIP
        external_id =\
            dictionary.get("external_id")\
            if dictionary.get("external_id")\
                else APIHelper.SKIP
        auto_track =\
            dictionary.get("auto_track")\
            if "auto_track" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(raw,
                   title,
                   topic_id,
                   category,
                   target_recipients,
                   target_usernames,
                   archetype,
                   created_at,
                   reply_to_post_number,
                   embed_url,
                   external_id,
                   auto_track)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _raw=self.raw
        _topic_id=(
            self.topic_id
            if hasattr(self, "topic_id")
            else None
        )
        _category=(
            self.category
            if hasattr(self, "category")
            else None
        )
        _target_recipients=(
            self.target_recipients
            if hasattr(self, "target_recipients")
            else None
        )
        _target_usernames=(
            self.target_usernames
            if hasattr(self, "target_usernames")
            else None
        )
        _archetype=(
            self.archetype
            if hasattr(self, "archetype")
            else None
        )
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _reply_to_post_number=(
            self.reply_to_post_number
            if hasattr(self, "reply_to_post_number")
            else None
        )
        _embed_url=(
            self.embed_url
            if hasattr(self, "embed_url")
            else None
        )
        _external_id=(
            self.external_id
            if hasattr(self, "external_id")
            else None
        )
        _auto_track=(
            self.auto_track
            if hasattr(self, "auto_track")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"title={_title!r}, "
            f"raw={_raw!r}, "
            f"topic_id={_topic_id!r}, "
            f"category={_category!r}, "
            f"target_recipients={_target_recipients!r}, "
            f"target_usernames={_target_usernames!r}, "
            f"archetype={_archetype!r}, "
            f"created_at={_created_at!r}, "
            f"reply_to_post_number={_reply_to_post_number!r}, "
            f"embed_url={_embed_url!r}, "
            f"external_id={_external_id!r}, "
            f"auto_track={_auto_track!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _raw=self.raw
        _topic_id=(
            self.topic_id
            if hasattr(self, "topic_id")
            else None
        )
        _category=(
            self.category
            if hasattr(self, "category")
            else None
        )
        _target_recipients=(
            self.target_recipients
            if hasattr(self, "target_recipients")
            else None
        )
        _target_usernames=(
            self.target_usernames
            if hasattr(self, "target_usernames")
            else None
        )
        _archetype=(
            self.archetype
            if hasattr(self, "archetype")
            else None
        )
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _reply_to_post_number=(
            self.reply_to_post_number
            if hasattr(self, "reply_to_post_number")
            else None
        )
        _embed_url=(
            self.embed_url
            if hasattr(self, "embed_url")
            else None
        )
        _external_id=(
            self.external_id
            if hasattr(self, "external_id")
            else None
        )
        _auto_track=(
            self.auto_track
            if hasattr(self, "auto_track")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"title={_title!s}, "
            f"raw={_raw!s}, "
            f"topic_id={_topic_id!s}, "
            f"category={_category!s}, "
            f"target_recipients={_target_recipients!s}, "
            f"target_usernames={_target_usernames!s}, "
            f"archetype={_archetype!s}, "
            f"created_at={_created_at!s}, "
            f"reply_to_post_number={_reply_to_post_number!s}, "
            f"embed_url={_embed_url!s}, "
            f"external_id={_external_id!s}, "
            f"auto_track={_auto_track!s}, "
            f")"
        )
