"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.models.post_2 import (
    Post2,
)


class PostsJsonResponse3(object):
    """Implementation of the 'Posts Json Response3' model.

    Attributes:
        post (Post2): The model property of type Post2.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "post": "post",
    }

    def __init__(
        self,
        post=None):
        """Initialize a PostsJsonResponse3 instance."""
        # Initialize members of the class
        self.post = post

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        post =\
            Post2.from_dictionary(
                dictionary.get("post"))\
                if dictionary.get("post") else None

        # Return an object of this model
        return cls(post)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _post=self.post
        return (
            f"{self.__class__.__name__}("
            f"post={_post!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _post=self.post
        return (
            f"{self.__class__.__name__}("
            f"post={_post!s}, "
            f")"
        )
