"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Reason(object):
    """Implementation of the 'Reason' enum.

    Attributes:
        ENABLED_FOR_EVERYONE: The enum member of type str.
        ENABLED_FOR_NO_ONE: The enum member of type str.
        IN_SPECIFIC_GROUPS: The enum member of type str.
        NOT_IN_SPECIFIC_GROUPS: The enum member of type str.

    """

    ENABLED_FOR_EVERYONE = "enabled_for_everyone"

    ENABLED_FOR_NO_ONE = "enabled_for_no_one"

    IN_SPECIFIC_GROUPS = "in_specific_groups"

    NOT_IN_SPECIFIC_GROUPS = "not_in_specific_groups"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
