"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.models.suspended_by import (
    SuspendedBy,
)


class Suspension(object):
    """Implementation of the 'Suspension' model.

    Attributes:
        suspend_reason (str): The model property of type str.
        full_suspend_reason (str): The model property of type str.
        suspended_till (str): The model property of type str.
        suspended_at (str): The model property of type str.
        suspended_by (SuspendedBy): The model property of type SuspendedBy.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "suspend_reason": "suspend_reason",
        "full_suspend_reason": "full_suspend_reason",
        "suspended_till": "suspended_till",
        "suspended_at": "suspended_at",
        "suspended_by": "suspended_by",
    }

    def __init__(
        self,
        suspend_reason=None,
        full_suspend_reason=None,
        suspended_till=None,
        suspended_at=None,
        suspended_by=None):
        """Initialize a Suspension instance."""
        # Initialize members of the class
        self.suspend_reason = suspend_reason
        self.full_suspend_reason = full_suspend_reason
        self.suspended_till = suspended_till
        self.suspended_at = suspended_at
        self.suspended_by = suspended_by

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        suspend_reason =\
            dictionary.get("suspend_reason")\
            if dictionary.get("suspend_reason")\
                else None
        full_suspend_reason =\
            dictionary.get("full_suspend_reason")\
            if dictionary.get("full_suspend_reason")\
                else None
        suspended_till =\
            dictionary.get("suspended_till")\
            if dictionary.get("suspended_till")\
                else None
        suspended_at =\
            dictionary.get("suspended_at")\
            if dictionary.get("suspended_at")\
                else None
        suspended_by =\
            SuspendedBy.from_dictionary(
                dictionary.get("suspended_by"))\
                if dictionary.get("suspended_by") else None

        # Return an object of this model
        return cls(suspend_reason,
                   full_suspend_reason,
                   suspended_till,
                   suspended_at,
                   suspended_by)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _suspend_reason=self.suspend_reason
        _full_suspend_reason=self.full_suspend_reason
        _suspended_till=self.suspended_till
        _suspended_at=self.suspended_at
        _suspended_by=self.suspended_by
        return (
            f"{self.__class__.__name__}("
            f"suspend_reason={_suspend_reason!r}, "
            f"full_suspend_reason={_full_suspend_reason!r}, "
            f"suspended_till={_suspended_till!r}, "
            f"suspended_at={_suspended_at!r}, "
            f"suspended_by={_suspended_by!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _suspend_reason=self.suspend_reason
        _full_suspend_reason=self.full_suspend_reason
        _suspended_till=self.suspended_till
        _suspended_at=self.suspended_at
        _suspended_by=self.suspended_by
        return (
            f"{self.__class__.__name__}("
            f"suspend_reason={_suspend_reason!s}, "
            f"full_suspend_reason={_full_suspend_reason!s}, "
            f"suspended_till={_suspended_till!s}, "
            f"suspended_at={_suspended_at!s}, "
            f"suspended_by={_suspended_by!s}, "
            f")"
        )
