"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.api_helper import (
    APIHelper,
)


class TNotificationsJsonRequest(object):
    """Implementation of the 'T NotificationsJson Request' model.

    Attributes:
        notification_level (NotificationLevel): The model property of type
            NotificationLevel.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "notification_level": "notification_level",
    }

    def __init__(
        self,
        notification_level=None,
        additional_properties=None):
        """Initialize a TNotificationsJsonRequest instance."""
        # Initialize members of the class
        self.notification_level = notification_level

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        notification_level =\
            dictionary.get("notification_level")\
            if dictionary.get("notification_level")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(notification_level,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _notification_level=self.notification_level
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"notification_level={_notification_level!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _notification_level=self.notification_level
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"notification_level={_notification_level!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
