"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.api_helper import (
    APIHelper,
)


class TStatusJsonRequest(object):
    """Implementation of the 'T StatusJson Request' model.

    Attributes:
        status (Status1): The model property of type Status1.
        enabled (Enabled): The model property of type Enabled.
        until (str): Only required for `pinned` and `pinned_globally`
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "status": "status",
        "enabled": "enabled",
        "until": "until",
    }

    _optionals = [
        "until",
    ]

    def __init__(
        self,
        status=None,
        enabled=None,
        until=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a TStatusJsonRequest instance."""
        # Initialize members of the class
        self.status = status
        self.enabled = enabled
        if until is not APIHelper.SKIP:
            self.until = until

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else None
        enabled =\
            dictionary.get("enabled")\
            if dictionary.get("enabled")\
                else None
        until =\
            dictionary.get("until")\
            if dictionary.get("until")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(status,
                   enabled,
                   until,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _status=self.status
        _enabled=self.enabled
        _until=(
            self.until
            if hasattr(self, "until")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"status={_status!r}, "
            f"enabled={_enabled!r}, "
            f"until={_until!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _status=self.status
        _enabled=self.enabled
        _until=(
            self.until
            if hasattr(self, "until")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"status={_status!s}, "
            f"enabled={_enabled!s}, "
            f"until={_until!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
