"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.api_helper import (
    APIHelper,
)
from discourseapidocumentation.models.extras_3 import (
    Extras3,
)
from discourseapidocumentation.models.tag_3 import (
    Tag3,
)


class TagsJsonResponse(object):
    """Implementation of the 'TagsJson Response' model.

    Attributes:
        tags (List[Tag3]): The model property of type List[Tag3].
        extras (Extras3): The model property of type Extras3.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "tags": "tags",
        "extras": "extras",
    }

    _optionals = [
        "tags",
        "extras",
    ]

    def __init__(
        self,
        tags=APIHelper.SKIP,
        extras=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a TagsJsonResponse instance."""
        # Initialize members of the class
        if tags is not APIHelper.SKIP:
            self.tags = tags
        if extras is not APIHelper.SKIP:
            self.extras = extras

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        tags = None
        if dictionary.get("tags") is not None:
            tags = [
                Tag3.from_dictionary(x)
                    for x in dictionary.get("tags")
            ]
        else:
            tags = APIHelper.SKIP
        extras =\
            Extras3.from_dictionary(
                dictionary.get("extras"))\
                if "extras" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(tags,
                   extras,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _extras=(
            self.extras
            if hasattr(self, "extras")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"tags={_tags!r}, "
            f"extras={_extras!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _extras=(
            self.extras
            if hasattr(self, "extras")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"tags={_tags!s}, "
            f"extras={_extras!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
