"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.api_helper import (
    APIHelper,
)


class UploadsGeneratePresignedPutJsonResponse(object):
    """Implementation of the 'Uploads Generate Presigned PutJson Response' model.

    Attributes:
        key (str): The path of the temporary file on the external storage service.
        url (str): A presigned PUT URL which must be used to upload the file binary
            blob to.
        signed_headers (Any): A map of headers that must be sent with the PUT request.
        unique_identifier (str): A unique string that identifies the external upload.
            This must be stored and then sent in the /complete-external-upload
            endpoint to complete the direct upload.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "key": "key",
        "url": "url",
        "signed_headers": "signed_headers",
        "unique_identifier": "unique_identifier",
    }

    _optionals = [
        "key",
        "url",
        "signed_headers",
        "unique_identifier",
    ]

    def __init__(
        self,
        key=APIHelper.SKIP,
        url=APIHelper.SKIP,
        signed_headers=APIHelper.SKIP,
        unique_identifier=APIHelper.SKIP):
        """Initialize a UploadsGeneratePresignedPutJsonResponse instance."""
        # Initialize members of the class
        if key is not APIHelper.SKIP:
            self.key = key
        if url is not APIHelper.SKIP:
            self.url = url
        if signed_headers is not APIHelper.SKIP:
            self.signed_headers = signed_headers
        if unique_identifier is not APIHelper.SKIP:
            self.unique_identifier = unique_identifier

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        key =\
            dictionary.get("key")\
            if dictionary.get("key")\
                else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else APIHelper.SKIP
        signed_headers =\
            dictionary.get("signed_headers")\
            if dictionary.get("signed_headers")\
                else APIHelper.SKIP
        unique_identifier =\
            dictionary.get("unique_identifier")\
            if dictionary.get("unique_identifier")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(key,
                   url,
                   signed_headers,
                   unique_identifier)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _key=(
            self.key
            if hasattr(self, "key")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _signed_headers=(
            self.signed_headers
            if hasattr(self, "signed_headers")
            else None
        )
        _unique_identifier=(
            self.unique_identifier
            if hasattr(self, "unique_identifier")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"key={_key!r}, "
            f"url={_url!r}, "
            f"signed_headers={_signed_headers!r}, "
            f"unique_identifier={_unique_identifier!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _key=(
            self.key
            if hasattr(self, "key")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _signed_headers=(
            self.signed_headers
            if hasattr(self, "signed_headers")
            else None
        )
        _unique_identifier=(
            self.unique_identifier
            if hasattr(self, "unique_identifier")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"key={_key!s}, "
            f"url={_url!s}, "
            f"signed_headers={_signed_headers!s}, "
            f"unique_identifier={_unique_identifier!s}, "
            f")"
        )
