"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class UploadsBatchPresignMultipartPartsJsonResponse(object):
    """Implementation of the
    'Uploads Batch Presign Multipart PartsJson Response' model.

    Attributes:
        presigned_urls (Any): The presigned URLs for each part number, which has the
            part numbers as keys.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "presigned_urls": "presigned_urls",
    }

    def __init__(
        self,
        presigned_urls=None):
        """Initialize a UploadsBatchPresignMultipartPartsJsonResponse instance."""
        # Initialize members of the class
        self.presigned_urls = presigned_urls

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        presigned_urls =\
            dictionary.get("presigned_urls")\
            if dictionary.get("presigned_urls")\
                else None

        # Return an object of this model
        return cls(presigned_urls)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _presigned_urls=self.presigned_urls
        return (
            f"{self.__class__.__name__}("
            f"presigned_urls={_presigned_urls!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _presigned_urls=self.presigned_urls
        return (
            f"{self.__class__.__name__}("
            f"presigned_urls={_presigned_urls!s}, "
            f")"
        )
