"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourseapidocumentation.api_helper import (
    APIHelper,
)
from discourseapidocumentation.models.custom_fields import (
    CustomFields,
)
from discourseapidocumentation.models.featured_topic import (
    FeaturedTopic,
)
from discourseapidocumentation.models.group_7 import (
    Group7,
)
from discourseapidocumentation.models.group_user import (
    GroupUser,
)
from discourseapidocumentation.models.user_auth_token import (
    UserAuthToken,
)
from discourseapidocumentation.models.user_notification_schedule import (
    UserNotificationSchedule,
)
from discourseapidocumentation.models.user_option import (
    UserOption,
)


class User8(object):
    """Implementation of the 'User8' model.

    Attributes:
        id (int): The model property of type int.
        username (str): The model property of type str.
        name (str): The model property of type str.
        avatar_template (str): The model property of type str.
        last_posted_at (str): The model property of type str.
        last_seen_at (str): The model property of type str.
        created_at (str): The model property of type str.
        ignored (bool): The model property of type bool.
        muted (bool): The model property of type bool.
        can_ignore_user (bool): The model property of type bool.
        can_ignore_users (bool): The model property of type bool.
        can_mute_user (bool): The model property of type bool.
        can_mute_users (bool): The model property of type bool.
        can_send_private_messages (bool): The model property of type bool.
        can_send_private_message_to_user (bool): The model property of type bool.
        trust_level (int): The model property of type int.
        moderator (bool): The model property of type bool.
        admin (bool): The model property of type bool.
        title (str): The model property of type str.
        badge_count (int): The model property of type int.
        second_factor_backup_enabled (bool): The model property of type bool.
        user_fields (Dict[str, str]): The model property of type Dict[str, str].
        custom_fields (CustomFields): The model property of type CustomFields.
        time_read (int): The model property of type int.
        recent_time_read (int): The model property of type int.
        primary_group_id (int): The model property of type int.
        primary_group_name (str): The model property of type str.
        flair_group_id (int): The model property of type int.
        flair_name (str): The model property of type str.
        flair_url (str): The model property of type str.
        flair_bg_color (str): The model property of type str.
        flair_color (str): The model property of type str.
        featured_topic (FeaturedTopic): The model property of type FeaturedTopic.
        staged (bool): The model property of type bool.
        can_edit (bool): The model property of type bool.
        can_edit_username (bool): The model property of type bool.
        can_edit_email (bool): The model property of type bool.
        can_edit_name (bool): The model property of type bool.
        uploaded_avatar_id (int): The model property of type int.
        has_title_badges (bool): The model property of type bool.
        pending_count (int): The model property of type int.
        pending_posts_count (int): The model property of type int.
        profile_view_count (int): The model property of type int.
        second_factor_enabled (bool): The model property of type bool.
        can_upload_profile_header (bool): The model property of type bool.
        can_upload_user_card_background (bool): The model property of type bool.
        post_count (int): The model property of type int.
        topic_count (int): The model property of type int.
        can_be_deleted (bool): The model property of type bool.
        can_delete_all_posts (bool): The model property of type bool.
        locale (str): The model property of type str.
        muted_category_ids (List[Any]): The model property of type List[Any].
        regular_category_ids (List[Any]): The model property of type List[Any].
        watched_tags (List[Any]): The model property of type List[Any].
        watching_first_post_tags (List[Any]): The model property of type List[Any].
        tracked_tags (List[Any]): The model property of type List[Any].
        muted_tags (List[Any]): The model property of type List[Any].
        tracked_category_ids (List[Any]): The model property of type List[Any].
        watched_category_ids (List[Any]): The model property of type List[Any].
        watched_first_post_category_ids (List[Any]): The model property of type
            List[Any].
        system_avatar_upload_id (str): The model property of type str.
        system_avatar_template (str): The model property of type str.
        muted_usernames (List[Any]): The model property of type List[Any].
        ignored_usernames (List[Any]): The model property of type List[Any].
        allowed_pm_usernames (List[Any]): The model property of type List[Any].
        mailing_list_posts_per_day (int): The model property of type int.
        can_change_bio (bool): The model property of type bool.
        can_change_location (bool): The model property of type bool.
        can_change_website (bool): The model property of type bool.
        can_change_tracking_preferences (bool): The model property of type bool.
        user_api_keys (str): The model property of type str.
        user_passkeys (List[Any]): The model property of type List[Any].
        sidebar_tags (List[Any]): The model property of type List[Any].
        sidebar_category_ids (List[Any]): The model property of type List[Any].
        display_sidebar_tags (bool): The model property of type bool.
        can_pick_theme_with_custom_homepage (bool): The model property of type bool.
        user_auth_tokens (List[UserAuthToken]): The model property of type
            List[UserAuthToken].
        user_notification_schedule (UserNotificationSchedule): The model property of
            type UserNotificationSchedule.
        use_logo_small_as_avatar (bool): The model property of type bool.
        featured_user_badge_ids (List[Any]): The model property of type List[Any].
        invited_by (str): The model property of type str.
        groups (List[Group7]): The model property of type List[Group7].
        group_users (List[GroupUser]): The model property of type List[GroupUser].
        user_option (UserOption): The model property of type UserOption.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "username": "username",
        "name": "name",
        "avatar_template": "avatar_template",
        "last_posted_at": "last_posted_at",
        "last_seen_at": "last_seen_at",
        "created_at": "created_at",
        "ignored": "ignored",
        "muted": "muted",
        "can_ignore_user": "can_ignore_user",
        "can_mute_user": "can_mute_user",
        "can_send_private_messages": "can_send_private_messages",
        "can_send_private_message_to_user": "can_send_private_message_to_user",
        "trust_level": "trust_level",
        "moderator": "moderator",
        "admin": "admin",
        "title": "title",
        "badge_count": "badge_count",
        "custom_fields": "custom_fields",
        "time_read": "time_read",
        "recent_time_read": "recent_time_read",
        "primary_group_id": "primary_group_id",
        "primary_group_name": "primary_group_name",
        "flair_group_id": "flair_group_id",
        "flair_name": "flair_name",
        "flair_url": "flair_url",
        "flair_bg_color": "flair_bg_color",
        "flair_color": "flair_color",
        "featured_topic": "featured_topic",
        "staged": "staged",
        "can_edit": "can_edit",
        "can_edit_username": "can_edit_username",
        "can_edit_email": "can_edit_email",
        "can_edit_name": "can_edit_name",
        "uploaded_avatar_id": "uploaded_avatar_id",
        "has_title_badges": "has_title_badges",
        "pending_count": "pending_count",
        "profile_view_count": "profile_view_count",
        "second_factor_enabled": "second_factor_enabled",
        "can_upload_profile_header": "can_upload_profile_header",
        "can_upload_user_card_background": "can_upload_user_card_background",
        "post_count": "post_count",
        "topic_count": "topic_count",
        "can_be_deleted": "can_be_deleted",
        "can_delete_all_posts": "can_delete_all_posts",
        "locale": "locale",
        "muted_category_ids": "muted_category_ids",
        "regular_category_ids": "regular_category_ids",
        "watched_tags": "watched_tags",
        "watching_first_post_tags": "watching_first_post_tags",
        "tracked_tags": "tracked_tags",
        "muted_tags": "muted_tags",
        "tracked_category_ids": "tracked_category_ids",
        "watched_category_ids": "watched_category_ids",
        "watched_first_post_category_ids": "watched_first_post_category_ids",
        "system_avatar_upload_id": "system_avatar_upload_id",
        "system_avatar_template": "system_avatar_template",
        "muted_usernames": "muted_usernames",
        "ignored_usernames": "ignored_usernames",
        "allowed_pm_usernames": "allowed_pm_usernames",
        "mailing_list_posts_per_day": "mailing_list_posts_per_day",
        "can_change_bio": "can_change_bio",
        "can_change_location": "can_change_location",
        "can_change_website": "can_change_website",
        "can_change_tracking_preferences": "can_change_tracking_preferences",
        "user_api_keys": "user_api_keys",
        "user_auth_tokens": "user_auth_tokens",
        "user_notification_schedule": "user_notification_schedule",
        "use_logo_small_as_avatar": "use_logo_small_as_avatar",
        "featured_user_badge_ids": "featured_user_badge_ids",
        "invited_by": "invited_by",
        "groups": "groups",
        "group_users": "group_users",
        "user_option": "user_option",
        "can_ignore_users": "can_ignore_users",
        "can_mute_users": "can_mute_users",
        "second_factor_backup_enabled": "second_factor_backup_enabled",
        "user_fields": "user_fields",
        "pending_posts_count": "pending_posts_count",
        "user_passkeys": "user_passkeys",
        "sidebar_tags": "sidebar_tags",
        "sidebar_category_ids": "sidebar_category_ids",
        "display_sidebar_tags": "display_sidebar_tags",
        "can_pick_theme_with_custom_homepage": "can_pick_theme_with_custom_homepage",
    }

    _optionals = [
        "can_ignore_users",
        "can_mute_users",
        "second_factor_backup_enabled",
        "user_fields",
        "pending_posts_count",
        "user_passkeys",
        "sidebar_tags",
        "sidebar_category_ids",
        "display_sidebar_tags",
        "can_pick_theme_with_custom_homepage",
    ]

    _nullables = [
        "last_posted_at",
        "last_seen_at",
        "title",
        "primary_group_id",
        "primary_group_name",
        "flair_group_id",
        "flair_name",
        "flair_url",
        "flair_bg_color",
        "flair_color",
        "uploaded_avatar_id",
        "locale",
        "system_avatar_upload_id",
        "user_api_keys",
        "invited_by",
    ]

    def __init__(
        self,
        id=None,
        username=None,
        name=None,
        avatar_template=None,
        last_posted_at=None,
        last_seen_at=None,
        created_at=None,
        ignored=None,
        muted=None,
        can_ignore_user=None,
        can_mute_user=None,
        can_send_private_messages=None,
        can_send_private_message_to_user=None,
        trust_level=None,
        moderator=None,
        admin=None,
        title=None,
        badge_count=None,
        custom_fields=None,
        time_read=None,
        recent_time_read=None,
        primary_group_id=None,
        primary_group_name=None,
        flair_group_id=None,
        flair_name=None,
        flair_url=None,
        flair_bg_color=None,
        flair_color=None,
        featured_topic=None,
        staged=None,
        can_edit=None,
        can_edit_username=None,
        can_edit_email=None,
        can_edit_name=None,
        uploaded_avatar_id=None,
        has_title_badges=None,
        pending_count=None,
        profile_view_count=None,
        second_factor_enabled=None,
        can_upload_profile_header=None,
        can_upload_user_card_background=None,
        post_count=None,
        topic_count=None,
        can_be_deleted=None,
        can_delete_all_posts=None,
        locale=None,
        muted_category_ids=None,
        regular_category_ids=None,
        watched_tags=None,
        watching_first_post_tags=None,
        tracked_tags=None,
        muted_tags=None,
        tracked_category_ids=None,
        watched_category_ids=None,
        watched_first_post_category_ids=None,
        system_avatar_upload_id=None,
        system_avatar_template=None,
        muted_usernames=None,
        ignored_usernames=None,
        allowed_pm_usernames=None,
        mailing_list_posts_per_day=None,
        can_change_bio=None,
        can_change_location=None,
        can_change_website=None,
        can_change_tracking_preferences=None,
        user_api_keys=None,
        user_auth_tokens=None,
        user_notification_schedule=None,
        use_logo_small_as_avatar=None,
        featured_user_badge_ids=None,
        invited_by=None,
        groups=None,
        group_users=None,
        user_option=None,
        can_ignore_users=APIHelper.SKIP,
        can_mute_users=APIHelper.SKIP,
        second_factor_backup_enabled=APIHelper.SKIP,
        user_fields=APIHelper.SKIP,
        pending_posts_count=APIHelper.SKIP,
        user_passkeys=APIHelper.SKIP,
        sidebar_tags=APIHelper.SKIP,
        sidebar_category_ids=APIHelper.SKIP,
        display_sidebar_tags=APIHelper.SKIP,
        can_pick_theme_with_custom_homepage=APIHelper.SKIP):
        """Initialize a User8 instance."""
        # Initialize members of the class
        self.id = id
        self.username = username
        self.name = name
        self.avatar_template = avatar_template
        self.last_posted_at = last_posted_at
        self.last_seen_at = last_seen_at
        self.created_at = created_at
        self.ignored = ignored
        self.muted = muted
        self.can_ignore_user = can_ignore_user
        if can_ignore_users is not APIHelper.SKIP:
            self.can_ignore_users = can_ignore_users
        self.can_mute_user = can_mute_user
        if can_mute_users is not APIHelper.SKIP:
            self.can_mute_users = can_mute_users
        self.can_send_private_messages = can_send_private_messages
        self.can_send_private_message_to_user = can_send_private_message_to_user
        self.trust_level = trust_level
        self.moderator = moderator
        self.admin = admin
        self.title = title
        self.badge_count = badge_count
        if second_factor_backup_enabled is not APIHelper.SKIP:
            self.second_factor_backup_enabled = second_factor_backup_enabled
        if user_fields is not APIHelper.SKIP:
            self.user_fields = user_fields
        self.custom_fields = custom_fields
        self.time_read = time_read
        self.recent_time_read = recent_time_read
        self.primary_group_id = primary_group_id
        self.primary_group_name = primary_group_name
        self.flair_group_id = flair_group_id
        self.flair_name = flair_name
        self.flair_url = flair_url
        self.flair_bg_color = flair_bg_color
        self.flair_color = flair_color
        self.featured_topic = featured_topic
        self.staged = staged
        self.can_edit = can_edit
        self.can_edit_username = can_edit_username
        self.can_edit_email = can_edit_email
        self.can_edit_name = can_edit_name
        self.uploaded_avatar_id = uploaded_avatar_id
        self.has_title_badges = has_title_badges
        self.pending_count = pending_count
        if pending_posts_count is not APIHelper.SKIP:
            self.pending_posts_count = pending_posts_count
        self.profile_view_count = profile_view_count
        self.second_factor_enabled = second_factor_enabled
        self.can_upload_profile_header = can_upload_profile_header
        self.can_upload_user_card_background = can_upload_user_card_background
        self.post_count = post_count
        self.topic_count = topic_count
        self.can_be_deleted = can_be_deleted
        self.can_delete_all_posts = can_delete_all_posts
        self.locale = locale
        self.muted_category_ids = muted_category_ids
        self.regular_category_ids = regular_category_ids
        self.watched_tags = watched_tags
        self.watching_first_post_tags = watching_first_post_tags
        self.tracked_tags = tracked_tags
        self.muted_tags = muted_tags
        self.tracked_category_ids = tracked_category_ids
        self.watched_category_ids = watched_category_ids
        self.watched_first_post_category_ids = watched_first_post_category_ids
        self.system_avatar_upload_id = system_avatar_upload_id
        self.system_avatar_template = system_avatar_template
        self.muted_usernames = muted_usernames
        self.ignored_usernames = ignored_usernames
        self.allowed_pm_usernames = allowed_pm_usernames
        self.mailing_list_posts_per_day = mailing_list_posts_per_day
        self.can_change_bio = can_change_bio
        self.can_change_location = can_change_location
        self.can_change_website = can_change_website
        self.can_change_tracking_preferences = can_change_tracking_preferences
        self.user_api_keys = user_api_keys
        if user_passkeys is not APIHelper.SKIP:
            self.user_passkeys = user_passkeys
        if sidebar_tags is not APIHelper.SKIP:
            self.sidebar_tags = sidebar_tags
        if sidebar_category_ids is not APIHelper.SKIP:
            self.sidebar_category_ids = sidebar_category_ids
        if display_sidebar_tags is not APIHelper.SKIP:
            self.display_sidebar_tags = display_sidebar_tags
        if can_pick_theme_with_custom_homepage is not APIHelper.SKIP:
            self.can_pick_theme_with_custom_homepage =\
                 can_pick_theme_with_custom_homepage
        self.user_auth_tokens = user_auth_tokens
        self.user_notification_schedule = user_notification_schedule
        self.use_logo_small_as_avatar = use_logo_small_as_avatar
        self.featured_user_badge_ids = featured_user_badge_ids
        self.invited_by = invited_by
        self.groups = groups
        self.group_users = group_users
        self.user_option = user_option

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        username =\
            dictionary.get("username")\
            if dictionary.get("username")\
                else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        avatar_template =\
            dictionary.get("avatar_template")\
            if dictionary.get("avatar_template")\
                else None
        last_posted_at =\
            dictionary.get("last_posted_at")\
            if dictionary.get("last_posted_at")\
                else None
        last_seen_at =\
            dictionary.get("last_seen_at")\
            if dictionary.get("last_seen_at")\
                else None
        created_at =\
            dictionary.get("created_at")\
            if dictionary.get("created_at")\
                else None
        ignored =\
            dictionary.get("ignored")\
            if "ignored" in dictionary.keys()\
                else None
        muted =\
            dictionary.get("muted")\
            if "muted" in dictionary.keys()\
                else None
        can_ignore_user =\
            dictionary.get("can_ignore_user")\
            if "can_ignore_user" in dictionary.keys()\
                else None
        can_mute_user =\
            dictionary.get("can_mute_user")\
            if "can_mute_user" in dictionary.keys()\
                else None
        can_send_private_messages =\
            dictionary.get("can_send_private_messages")\
            if "can_send_private_messages" in dictionary.keys()\
                else None
        can_send_private_message_to_user =\
            dictionary.get("can_send_private_message_to_user")\
            if "can_send_private_message_to_user" in dictionary.keys()\
                else None
        trust_level =\
            dictionary.get("trust_level")\
            if dictionary.get("trust_level")\
                else None
        moderator =\
            dictionary.get("moderator")\
            if "moderator" in dictionary.keys()\
                else None
        admin =\
            dictionary.get("admin")\
            if "admin" in dictionary.keys()\
                else None
        title =\
            dictionary.get("title")\
            if dictionary.get("title")\
                else None
        badge_count =\
            dictionary.get("badge_count")\
            if dictionary.get("badge_count")\
                else None
        custom_fields =\
            CustomFields.from_dictionary(
                dictionary.get("custom_fields"))\
                if dictionary.get("custom_fields") else None
        time_read =\
            dictionary.get("time_read")\
            if dictionary.get("time_read")\
                else None
        recent_time_read =\
            dictionary.get("recent_time_read")\
            if dictionary.get("recent_time_read")\
                else None
        primary_group_id =\
            dictionary.get("primary_group_id")\
            if dictionary.get("primary_group_id")\
                else None
        primary_group_name =\
            dictionary.get("primary_group_name")\
            if dictionary.get("primary_group_name")\
                else None
        flair_group_id =\
            dictionary.get("flair_group_id")\
            if dictionary.get("flair_group_id")\
                else None
        flair_name =\
            dictionary.get("flair_name")\
            if dictionary.get("flair_name")\
                else None
        flair_url =\
            dictionary.get("flair_url")\
            if dictionary.get("flair_url")\
                else None
        flair_bg_color =\
            dictionary.get("flair_bg_color")\
            if dictionary.get("flair_bg_color")\
                else None
        flair_color =\
            dictionary.get("flair_color")\
            if dictionary.get("flair_color")\
                else None
        featured_topic =\
            FeaturedTopic.from_dictionary(
                dictionary.get("featured_topic"))\
                if dictionary.get("featured_topic") else None
        staged =\
            dictionary.get("staged")\
            if "staged" in dictionary.keys()\
                else None
        can_edit =\
            dictionary.get("can_edit")\
            if "can_edit" in dictionary.keys()\
                else None
        can_edit_username =\
            dictionary.get("can_edit_username")\
            if "can_edit_username" in dictionary.keys()\
                else None
        can_edit_email =\
            dictionary.get("can_edit_email")\
            if "can_edit_email" in dictionary.keys()\
                else None
        can_edit_name =\
            dictionary.get("can_edit_name")\
            if "can_edit_name" in dictionary.keys()\
                else None
        uploaded_avatar_id =\
            dictionary.get("uploaded_avatar_id")\
            if dictionary.get("uploaded_avatar_id")\
                else None
        has_title_badges =\
            dictionary.get("has_title_badges")\
            if "has_title_badges" in dictionary.keys()\
                else None
        pending_count =\
            dictionary.get("pending_count")\
            if dictionary.get("pending_count")\
                else None
        profile_view_count =\
            dictionary.get("profile_view_count")\
            if dictionary.get("profile_view_count")\
                else None
        second_factor_enabled =\
            dictionary.get("second_factor_enabled")\
            if "second_factor_enabled" in dictionary.keys()\
                else None
        can_upload_profile_header =\
            dictionary.get("can_upload_profile_header")\
            if "can_upload_profile_header" in dictionary.keys()\
                else None
        can_upload_user_card_background =\
            dictionary.get("can_upload_user_card_background")\
            if "can_upload_user_card_background" in dictionary.keys()\
                else None
        post_count =\
            dictionary.get("post_count")\
            if dictionary.get("post_count")\
                else None
        topic_count =\
            dictionary.get("topic_count")\
            if dictionary.get("topic_count")\
                else None
        can_be_deleted =\
            dictionary.get("can_be_deleted")\
            if "can_be_deleted" in dictionary.keys()\
                else None
        can_delete_all_posts =\
            dictionary.get("can_delete_all_posts")\
            if "can_delete_all_posts" in dictionary.keys()\
                else None
        locale =\
            dictionary.get("locale")\
            if dictionary.get("locale")\
                else None
        muted_category_ids =\
            dictionary.get("muted_category_ids")\
            if dictionary.get("muted_category_ids")\
                else None
        regular_category_ids =\
            dictionary.get("regular_category_ids")\
            if dictionary.get("regular_category_ids")\
                else None
        watched_tags =\
            dictionary.get("watched_tags")\
            if dictionary.get("watched_tags")\
                else None
        watching_first_post_tags =\
            dictionary.get("watching_first_post_tags")\
            if dictionary.get("watching_first_post_tags")\
                else None
        tracked_tags =\
            dictionary.get("tracked_tags")\
            if dictionary.get("tracked_tags")\
                else None
        muted_tags =\
            dictionary.get("muted_tags")\
            if dictionary.get("muted_tags")\
                else None
        tracked_category_ids =\
            dictionary.get("tracked_category_ids")\
            if dictionary.get("tracked_category_ids")\
                else None
        watched_category_ids =\
            dictionary.get("watched_category_ids")\
            if dictionary.get("watched_category_ids")\
                else None
        watched_first_post_category_ids =\
            dictionary.get("watched_first_post_category_ids")\
            if dictionary.get("watched_first_post_category_ids")\
                else None
        system_avatar_upload_id =\
            dictionary.get("system_avatar_upload_id")\
            if dictionary.get("system_avatar_upload_id")\
                else None
        system_avatar_template =\
            dictionary.get("system_avatar_template")\
            if dictionary.get("system_avatar_template")\
                else None
        muted_usernames =\
            dictionary.get("muted_usernames")\
            if dictionary.get("muted_usernames")\
                else None
        ignored_usernames =\
            dictionary.get("ignored_usernames")\
            if dictionary.get("ignored_usernames")\
                else None
        allowed_pm_usernames =\
            dictionary.get("allowed_pm_usernames")\
            if dictionary.get("allowed_pm_usernames")\
                else None
        mailing_list_posts_per_day =\
            dictionary.get("mailing_list_posts_per_day")\
            if dictionary.get("mailing_list_posts_per_day")\
                else None
        can_change_bio =\
            dictionary.get("can_change_bio")\
            if "can_change_bio" in dictionary.keys()\
                else None
        can_change_location =\
            dictionary.get("can_change_location")\
            if "can_change_location" in dictionary.keys()\
                else None
        can_change_website =\
            dictionary.get("can_change_website")\
            if "can_change_website" in dictionary.keys()\
                else None
        can_change_tracking_preferences =\
            dictionary.get("can_change_tracking_preferences")\
            if "can_change_tracking_preferences" in dictionary.keys()\
                else None
        user_api_keys =\
            dictionary.get("user_api_keys")\
            if dictionary.get("user_api_keys")\
                else None
        user_auth_tokens = None
        if dictionary.get("user_auth_tokens") is not None:
            user_auth_tokens = [
                UserAuthToken.from_dictionary(x)
                    for x in dictionary.get("user_auth_tokens")
            ]
        user_notification_schedule =\
            UserNotificationSchedule.from_dictionary(
                dictionary.get("user_notification_schedule"))\
                if dictionary.get("user_notification_schedule") else None
        use_logo_small_as_avatar =\
            dictionary.get("use_logo_small_as_avatar")\
            if "use_logo_small_as_avatar" in dictionary.keys()\
                else None
        featured_user_badge_ids =\
            dictionary.get("featured_user_badge_ids")\
            if dictionary.get("featured_user_badge_ids")\
                else None
        invited_by =\
            dictionary.get("invited_by")\
            if dictionary.get("invited_by")\
                else None
        groups = None
        if dictionary.get("groups") is not None:
            groups = [
                Group7.from_dictionary(x)
                    for x in dictionary.get("groups")
            ]
        group_users = None
        if dictionary.get("group_users") is not None:
            group_users = [
                GroupUser.from_dictionary(x)
                    for x in dictionary.get("group_users")
            ]
        user_option =\
            UserOption.from_dictionary(
                dictionary.get("user_option"))\
                if dictionary.get("user_option") else None
        can_ignore_users =\
            dictionary.get("can_ignore_users")\
            if "can_ignore_users" in dictionary.keys()\
                else APIHelper.SKIP
        can_mute_users =\
            dictionary.get("can_mute_users")\
            if "can_mute_users" in dictionary.keys()\
                else APIHelper.SKIP
        second_factor_backup_enabled =\
            dictionary.get("second_factor_backup_enabled")\
            if "second_factor_backup_enabled" in dictionary.keys()\
                else APIHelper.SKIP
        user_fields =\
            dictionary.get("user_fields")\
            if dictionary.get("user_fields")\
                else APIHelper.SKIP
        pending_posts_count =\
            dictionary.get("pending_posts_count")\
            if dictionary.get("pending_posts_count")\
                else APIHelper.SKIP
        user_passkeys =\
            dictionary.get("user_passkeys")\
            if dictionary.get("user_passkeys")\
                else APIHelper.SKIP
        sidebar_tags =\
            dictionary.get("sidebar_tags")\
            if dictionary.get("sidebar_tags")\
                else APIHelper.SKIP
        sidebar_category_ids =\
            dictionary.get("sidebar_category_ids")\
            if dictionary.get("sidebar_category_ids")\
                else APIHelper.SKIP
        display_sidebar_tags =\
            dictionary.get("display_sidebar_tags")\
            if "display_sidebar_tags" in dictionary.keys()\
                else APIHelper.SKIP
        can_pick_theme_with_custom_homepage =\
            dictionary.get("can_pick_theme_with_custom_homepage")\
            if "can_pick_theme_with_custom_homepage" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(id,
                   username,
                   name,
                   avatar_template,
                   last_posted_at,
                   last_seen_at,
                   created_at,
                   ignored,
                   muted,
                   can_ignore_user,
                   can_mute_user,
                   can_send_private_messages,
                   can_send_private_message_to_user,
                   trust_level,
                   moderator,
                   admin,
                   title,
                   badge_count,
                   custom_fields,
                   time_read,
                   recent_time_read,
                   primary_group_id,
                   primary_group_name,
                   flair_group_id,
                   flair_name,
                   flair_url,
                   flair_bg_color,
                   flair_color,
                   featured_topic,
                   staged,
                   can_edit,
                   can_edit_username,
                   can_edit_email,
                   can_edit_name,
                   uploaded_avatar_id,
                   has_title_badges,
                   pending_count,
                   profile_view_count,
                   second_factor_enabled,
                   can_upload_profile_header,
                   can_upload_user_card_background,
                   post_count,
                   topic_count,
                   can_be_deleted,
                   can_delete_all_posts,
                   locale,
                   muted_category_ids,
                   regular_category_ids,
                   watched_tags,
                   watching_first_post_tags,
                   tracked_tags,
                   muted_tags,
                   tracked_category_ids,
                   watched_category_ids,
                   watched_first_post_category_ids,
                   system_avatar_upload_id,
                   system_avatar_template,
                   muted_usernames,
                   ignored_usernames,
                   allowed_pm_usernames,
                   mailing_list_posts_per_day,
                   can_change_bio,
                   can_change_location,
                   can_change_website,
                   can_change_tracking_preferences,
                   user_api_keys,
                   user_auth_tokens,
                   user_notification_schedule,
                   use_logo_small_as_avatar,
                   featured_user_badge_ids,
                   invited_by,
                   groups,
                   group_users,
                   user_option,
                   can_ignore_users,
                   can_mute_users,
                   second_factor_backup_enabled,
                   user_fields,
                   pending_posts_count,
                   user_passkeys,
                   sidebar_tags,
                   sidebar_category_ids,
                   display_sidebar_tags,
                   can_pick_theme_with_custom_homepage)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _username=self.username
        _name=self.name
        _avatar_template=self.avatar_template
        _last_posted_at=self.last_posted_at
        _last_seen_at=self.last_seen_at
        _created_at=self.created_at
        _ignored=self.ignored
        _muted=self.muted
        _can_ignore_user=self.can_ignore_user
        _can_ignore_users=(
            self.can_ignore_users
            if hasattr(self, "can_ignore_users")
            else None
        )
        _can_mute_user=self.can_mute_user
        _can_mute_users=(
            self.can_mute_users
            if hasattr(self, "can_mute_users")
            else None
        )
        _can_send_private_messages=self.can_send_private_messages
        _can_send_private_message_to_user=self.can_send_private_message_to_user
        _trust_level=self.trust_level
        _moderator=self.moderator
        _admin=self.admin
        _title=self.title
        _badge_count=self.badge_count
        _second_factor_backup_enabled=(
            self.second_factor_backup_enabled
            if hasattr(self, "second_factor_backup_enabled")
            else None
        )
        _user_fields=(
            self.user_fields
            if hasattr(self, "user_fields")
            else None
        )
        _custom_fields=self.custom_fields
        _time_read=self.time_read
        _recent_time_read=self.recent_time_read
        _primary_group_id=self.primary_group_id
        _primary_group_name=self.primary_group_name
        _flair_group_id=self.flair_group_id
        _flair_name=self.flair_name
        _flair_url=self.flair_url
        _flair_bg_color=self.flair_bg_color
        _flair_color=self.flair_color
        _featured_topic=self.featured_topic
        _staged=self.staged
        _can_edit=self.can_edit
        _can_edit_username=self.can_edit_username
        _can_edit_email=self.can_edit_email
        _can_edit_name=self.can_edit_name
        _uploaded_avatar_id=self.uploaded_avatar_id
        _has_title_badges=self.has_title_badges
        _pending_count=self.pending_count
        _pending_posts_count=(
            self.pending_posts_count
            if hasattr(self, "pending_posts_count")
            else None
        )
        _profile_view_count=self.profile_view_count
        _second_factor_enabled=self.second_factor_enabled
        _can_upload_profile_header=self.can_upload_profile_header
        _can_upload_user_card_background=self.can_upload_user_card_background
        _post_count=self.post_count
        _topic_count=self.topic_count
        _can_be_deleted=self.can_be_deleted
        _can_delete_all_posts=self.can_delete_all_posts
        _locale=self.locale
        _muted_category_ids=self.muted_category_ids
        _regular_category_ids=self.regular_category_ids
        _watched_tags=self.watched_tags
        _watching_first_post_tags=self.watching_first_post_tags
        _tracked_tags=self.tracked_tags
        _muted_tags=self.muted_tags
        _tracked_category_ids=self.tracked_category_ids
        _watched_category_ids=self.watched_category_ids
        _watched_first_post_category_ids=self.watched_first_post_category_ids
        _system_avatar_upload_id=self.system_avatar_upload_id
        _system_avatar_template=self.system_avatar_template
        _muted_usernames=self.muted_usernames
        _ignored_usernames=self.ignored_usernames
        _allowed_pm_usernames=self.allowed_pm_usernames
        _mailing_list_posts_per_day=self.mailing_list_posts_per_day
        _can_change_bio=self.can_change_bio
        _can_change_location=self.can_change_location
        _can_change_website=self.can_change_website
        _can_change_tracking_preferences=self.can_change_tracking_preferences
        _user_api_keys=self.user_api_keys
        _user_passkeys=(
            self.user_passkeys
            if hasattr(self, "user_passkeys")
            else None
        )
        _sidebar_tags=(
            self.sidebar_tags
            if hasattr(self, "sidebar_tags")
            else None
        )
        _sidebar_category_ids=(
            self.sidebar_category_ids
            if hasattr(self, "sidebar_category_ids")
            else None
        )
        _display_sidebar_tags=(
            self.display_sidebar_tags
            if hasattr(self, "display_sidebar_tags")
            else None
        )
        _can_pick_theme_with_custom_homepage=(
            self.can_pick_theme_with_custom_homepage
            if hasattr(self, "can_pick_theme_with_custom_homepage")
            else None
        )
        _user_auth_tokens=self.user_auth_tokens
        _user_notification_schedule=self.user_notification_schedule
        _use_logo_small_as_avatar=self.use_logo_small_as_avatar
        _featured_user_badge_ids=self.featured_user_badge_ids
        _invited_by=self.invited_by
        _groups=self.groups
        _group_users=self.group_users
        _user_option=self.user_option
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"username={_username!r}, "
            f"name={_name!r}, "
            f"avatar_template={_avatar_template!r}, "
            f"last_posted_at={_last_posted_at!r}, "
            f"last_seen_at={_last_seen_at!r}, "
            f"created_at={_created_at!r}, "
            f"ignored={_ignored!r}, "
            f"muted={_muted!r}, "
            f"can_ignore_user={_can_ignore_user!r}, "
            f"can_ignore_users={_can_ignore_users!r}, "
            f"can_mute_user={_can_mute_user!r}, "
            f"can_mute_users={_can_mute_users!r}, "
            f"can_send_private_messages={_can_send_private_messages!r}, "
            f"can_send_private_message_to_user={_can_send_private_message_to_user!r}, "
            f"trust_level={_trust_level!r}, "
            f"moderator={_moderator!r}, "
            f"admin={_admin!r}, "
            f"title={_title!r}, "
            f"badge_count={_badge_count!r}, "
            f"second_factor_backup_enabled={_second_factor_backup_enabled!r}, "
            f"user_fields={_user_fields!r}, "
            f"custom_fields={_custom_fields!r}, "
            f"time_read={_time_read!r}, "
            f"recent_time_read={_recent_time_read!r}, "
            f"primary_group_id={_primary_group_id!r}, "
            f"primary_group_name={_primary_group_name!r}, "
            f"flair_group_id={_flair_group_id!r}, "
            f"flair_name={_flair_name!r}, "
            f"flair_url={_flair_url!r}, "
            f"flair_bg_color={_flair_bg_color!r}, "
            f"flair_color={_flair_color!r}, "
            f"featured_topic={_featured_topic!r}, "
            f"staged={_staged!r}, "
            f"can_edit={_can_edit!r}, "
            f"can_edit_username={_can_edit_username!r}, "
            f"can_edit_email={_can_edit_email!r}, "
            f"can_edit_name={_can_edit_name!r}, "
            f"uploaded_avatar_id={_uploaded_avatar_id!r}, "
            f"has_title_badges={_has_title_badges!r}, "
            f"pending_count={_pending_count!r}, "
            f"pending_posts_count={_pending_posts_count!r}, "
            f"profile_view_count={_profile_view_count!r}, "
            f"second_factor_enabled={_second_factor_enabled!r}, "
            f"can_upload_profile_header={_can_upload_profile_header!r}, "
            f"can_upload_user_card_background={_can_upload_user_card_background!r}, "
            f"post_count={_post_count!r}, "
            f"topic_count={_topic_count!r}, "
            f"can_be_deleted={_can_be_deleted!r}, "
            f"can_delete_all_posts={_can_delete_all_posts!r}, "
            f"locale={_locale!r}, "
            f"muted_category_ids={_muted_category_ids!r}, "
            f"regular_category_ids={_regular_category_ids!r}, "
            f"watched_tags={_watched_tags!r}, "
            f"watching_first_post_tags={_watching_first_post_tags!r}, "
            f"tracked_tags={_tracked_tags!r}, "
            f"muted_tags={_muted_tags!r}, "
            f"tracked_category_ids={_tracked_category_ids!r}, "
            f"watched_category_ids={_watched_category_ids!r}, "
            f"watched_first_post_category_ids={_watched_first_post_category_ids!r}, "
            f"system_avatar_upload_id={_system_avatar_upload_id!r}, "
            f"system_avatar_template={_system_avatar_template!r}, "
            f"muted_usernames={_muted_usernames!r}, "
            f"ignored_usernames={_ignored_usernames!r}, "
            f"allowed_pm_usernames={_allowed_pm_usernames!r}, "
            f"mailing_list_posts_per_day={_mailing_list_posts_per_day!r}, "
            f"can_change_bio={_can_change_bio!r}, "
            f"can_change_location={_can_change_location!r}, "
            f"can_change_website={_can_change_website!r}, "
            f"can_change_tracking_preferences={_can_change_tracking_preferences!r}, "
            f"user_api_keys={_user_api_keys!r}, "
            f"user_passkeys={_user_passkeys!r}, "
            f"sidebar_tags={_sidebar_tags!r}, "
            f"sidebar_category_ids={_sidebar_category_ids!r}, "
            f"display_sidebar_tags={_display_sidebar_tags!r}, "
            f"can_pick_theme_with_custom_homepage={_can_pick_theme_with_custom_homepage!r}, "
            f"user_auth_tokens={_user_auth_tokens!r}, "
            f"user_notification_schedule={_user_notification_schedule!r}, "
            f"use_logo_small_as_avatar={_use_logo_small_as_avatar!r}, "
            f"featured_user_badge_ids={_featured_user_badge_ids!r}, "
            f"invited_by={_invited_by!r}, "
            f"groups={_groups!r}, "
            f"group_users={_group_users!r}, "
            f"user_option={_user_option!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _username=self.username
        _name=self.name
        _avatar_template=self.avatar_template
        _last_posted_at=self.last_posted_at
        _last_seen_at=self.last_seen_at
        _created_at=self.created_at
        _ignored=self.ignored
        _muted=self.muted
        _can_ignore_user=self.can_ignore_user
        _can_ignore_users=(
            self.can_ignore_users
            if hasattr(self, "can_ignore_users")
            else None
        )
        _can_mute_user=self.can_mute_user
        _can_mute_users=(
            self.can_mute_users
            if hasattr(self, "can_mute_users")
            else None
        )
        _can_send_private_messages=self.can_send_private_messages
        _can_send_private_message_to_user=self.can_send_private_message_to_user
        _trust_level=self.trust_level
        _moderator=self.moderator
        _admin=self.admin
        _title=self.title
        _badge_count=self.badge_count
        _second_factor_backup_enabled=(
            self.second_factor_backup_enabled
            if hasattr(self, "second_factor_backup_enabled")
            else None
        )
        _user_fields=(
            self.user_fields
            if hasattr(self, "user_fields")
            else None
        )
        _custom_fields=self.custom_fields
        _time_read=self.time_read
        _recent_time_read=self.recent_time_read
        _primary_group_id=self.primary_group_id
        _primary_group_name=self.primary_group_name
        _flair_group_id=self.flair_group_id
        _flair_name=self.flair_name
        _flair_url=self.flair_url
        _flair_bg_color=self.flair_bg_color
        _flair_color=self.flair_color
        _featured_topic=self.featured_topic
        _staged=self.staged
        _can_edit=self.can_edit
        _can_edit_username=self.can_edit_username
        _can_edit_email=self.can_edit_email
        _can_edit_name=self.can_edit_name
        _uploaded_avatar_id=self.uploaded_avatar_id
        _has_title_badges=self.has_title_badges
        _pending_count=self.pending_count
        _pending_posts_count=(
            self.pending_posts_count
            if hasattr(self, "pending_posts_count")
            else None
        )
        _profile_view_count=self.profile_view_count
        _second_factor_enabled=self.second_factor_enabled
        _can_upload_profile_header=self.can_upload_profile_header
        _can_upload_user_card_background=self.can_upload_user_card_background
        _post_count=self.post_count
        _topic_count=self.topic_count
        _can_be_deleted=self.can_be_deleted
        _can_delete_all_posts=self.can_delete_all_posts
        _locale=self.locale
        _muted_category_ids=self.muted_category_ids
        _regular_category_ids=self.regular_category_ids
        _watched_tags=self.watched_tags
        _watching_first_post_tags=self.watching_first_post_tags
        _tracked_tags=self.tracked_tags
        _muted_tags=self.muted_tags
        _tracked_category_ids=self.tracked_category_ids
        _watched_category_ids=self.watched_category_ids
        _watched_first_post_category_ids=self.watched_first_post_category_ids
        _system_avatar_upload_id=self.system_avatar_upload_id
        _system_avatar_template=self.system_avatar_template
        _muted_usernames=self.muted_usernames
        _ignored_usernames=self.ignored_usernames
        _allowed_pm_usernames=self.allowed_pm_usernames
        _mailing_list_posts_per_day=self.mailing_list_posts_per_day
        _can_change_bio=self.can_change_bio
        _can_change_location=self.can_change_location
        _can_change_website=self.can_change_website
        _can_change_tracking_preferences=self.can_change_tracking_preferences
        _user_api_keys=self.user_api_keys
        _user_passkeys=(
            self.user_passkeys
            if hasattr(self, "user_passkeys")
            else None
        )
        _sidebar_tags=(
            self.sidebar_tags
            if hasattr(self, "sidebar_tags")
            else None
        )
        _sidebar_category_ids=(
            self.sidebar_category_ids
            if hasattr(self, "sidebar_category_ids")
            else None
        )
        _display_sidebar_tags=(
            self.display_sidebar_tags
            if hasattr(self, "display_sidebar_tags")
            else None
        )
        _can_pick_theme_with_custom_homepage=(
            self.can_pick_theme_with_custom_homepage
            if hasattr(self, "can_pick_theme_with_custom_homepage")
            else None
        )
        _user_auth_tokens=self.user_auth_tokens
        _user_notification_schedule=self.user_notification_schedule
        _use_logo_small_as_avatar=self.use_logo_small_as_avatar
        _featured_user_badge_ids=self.featured_user_badge_ids
        _invited_by=self.invited_by
        _groups=self.groups
        _group_users=self.group_users
        _user_option=self.user_option
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"username={_username!s}, "
            f"name={_name!s}, "
            f"avatar_template={_avatar_template!s}, "
            f"last_posted_at={_last_posted_at!s}, "
            f"last_seen_at={_last_seen_at!s}, "
            f"created_at={_created_at!s}, "
            f"ignored={_ignored!s}, "
            f"muted={_muted!s}, "
            f"can_ignore_user={_can_ignore_user!s}, "
            f"can_ignore_users={_can_ignore_users!s}, "
            f"can_mute_user={_can_mute_user!s}, "
            f"can_mute_users={_can_mute_users!s}, "
            f"can_send_private_messages={_can_send_private_messages!s}, "
            f"can_send_private_message_to_user={_can_send_private_message_to_user!s}, "
            f"trust_level={_trust_level!s}, "
            f"moderator={_moderator!s}, "
            f"admin={_admin!s}, "
            f"title={_title!s}, "
            f"badge_count={_badge_count!s}, "
            f"second_factor_backup_enabled={_second_factor_backup_enabled!s}, "
            f"user_fields={_user_fields!s}, "
            f"custom_fields={_custom_fields!s}, "
            f"time_read={_time_read!s}, "
            f"recent_time_read={_recent_time_read!s}, "
            f"primary_group_id={_primary_group_id!s}, "
            f"primary_group_name={_primary_group_name!s}, "
            f"flair_group_id={_flair_group_id!s}, "
            f"flair_name={_flair_name!s}, "
            f"flair_url={_flair_url!s}, "
            f"flair_bg_color={_flair_bg_color!s}, "
            f"flair_color={_flair_color!s}, "
            f"featured_topic={_featured_topic!s}, "
            f"staged={_staged!s}, "
            f"can_edit={_can_edit!s}, "
            f"can_edit_username={_can_edit_username!s}, "
            f"can_edit_email={_can_edit_email!s}, "
            f"can_edit_name={_can_edit_name!s}, "
            f"uploaded_avatar_id={_uploaded_avatar_id!s}, "
            f"has_title_badges={_has_title_badges!s}, "
            f"pending_count={_pending_count!s}, "
            f"pending_posts_count={_pending_posts_count!s}, "
            f"profile_view_count={_profile_view_count!s}, "
            f"second_factor_enabled={_second_factor_enabled!s}, "
            f"can_upload_profile_header={_can_upload_profile_header!s}, "
            f"can_upload_user_card_background={_can_upload_user_card_background!s}, "
            f"post_count={_post_count!s}, "
            f"topic_count={_topic_count!s}, "
            f"can_be_deleted={_can_be_deleted!s}, "
            f"can_delete_all_posts={_can_delete_all_posts!s}, "
            f"locale={_locale!s}, "
            f"muted_category_ids={_muted_category_ids!s}, "
            f"regular_category_ids={_regular_category_ids!s}, "
            f"watched_tags={_watched_tags!s}, "
            f"watching_first_post_tags={_watching_first_post_tags!s}, "
            f"tracked_tags={_tracked_tags!s}, "
            f"muted_tags={_muted_tags!s}, "
            f"tracked_category_ids={_tracked_category_ids!s}, "
            f"watched_category_ids={_watched_category_ids!s}, "
            f"watched_first_post_category_ids={_watched_first_post_category_ids!s}, "
            f"system_avatar_upload_id={_system_avatar_upload_id!s}, "
            f"system_avatar_template={_system_avatar_template!s}, "
            f"muted_usernames={_muted_usernames!s}, "
            f"ignored_usernames={_ignored_usernames!s}, "
            f"allowed_pm_usernames={_allowed_pm_usernames!s}, "
            f"mailing_list_posts_per_day={_mailing_list_posts_per_day!s}, "
            f"can_change_bio={_can_change_bio!s}, "
            f"can_change_location={_can_change_location!s}, "
            f"can_change_website={_can_change_website!s}, "
            f"can_change_tracking_preferences={_can_change_tracking_preferences!s}, "
            f"user_api_keys={_user_api_keys!s}, "
            f"user_passkeys={_user_passkeys!s}, "
            f"sidebar_tags={_sidebar_tags!s}, "
            f"sidebar_category_ids={_sidebar_category_ids!s}, "
            f"display_sidebar_tags={_display_sidebar_tags!s}, "
            f"can_pick_theme_with_custom_homepage={_can_pick_theme_with_custom_homepage!s}, "
            f"user_auth_tokens={_user_auth_tokens!s}, "
            f"user_notification_schedule={_user_notification_schedule!s}, "
            f"use_logo_small_as_avatar={_use_logo_small_as_avatar!s}, "
            f"featured_user_badge_ids={_featured_user_badge_ids!s}, "
            f"invited_by={_invited_by!s}, "
            f"groups={_groups!s}, "
            f"group_users={_group_users!s}, "
            f"user_option={_user_option!s}, "
            f")"
        )
