"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourse.models.basic_group import BasicGroup


class AdminGroupsJsonResponse(object):
    """Implementation of the 'Admin GroupsJson Response' model.

    Attributes:
        basic_group (BasicGroup): The model property of type BasicGroup.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "basic_group": "basic_group",
    }

    def __init__(
        self,
        basic_group=None):
        """Initialize a AdminGroupsJsonResponse instance."""
        # Initialize members of the class
        self.basic_group = basic_group

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        basic_group =\
            BasicGroup.from_dictionary(
                dictionary.get("basic_group"))\
                if dictionary.get("basic_group") else None

        # Return an object of this model
        return cls(basic_group)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _basic_group=self.basic_group
        return (
            f"{self.__class__.__name__}("
            f"basic_group={_basic_group!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _basic_group=self.basic_group
        return (
            f"{self.__class__.__name__}("
            f"basic_group={_basic_group!s}, "
            f")"
        )
