"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourse.models.silence import Silence


class AdminUsersSilenceJsonResponse(object):
    """Implementation of the 'Admin Users SilenceJson Response' model.

    Attributes:
        silence (Silence): The model property of type Silence.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "silence": "silence",
    }

    def __init__(
        self,
        silence=None):
        """Initialize a AdminUsersSilenceJsonResponse instance."""
        # Initialize members of the class
        self.silence = silence

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        silence =\
            Silence.from_dictionary(
                dictionary.get("silence"))\
                if dictionary.get("silence") else None

        # Return an object of this model
        return cls(silence)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _silence=self.silence
        return (
            f"{self.__class__.__name__}("
            f"silence={_silence!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _silence=self.silence
        return (
            f"{self.__class__.__name__}("
            f"silence={_silence!s}, "
            f")"
        )
