"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class AdminBackupsJsonRequest(object):
    """Implementation of the 'Admin BackupsJson Request' model.

    Attributes:
        with_uploads (bool): The model property of type bool.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "with_uploads": "with_uploads",
    }

    def __init__(
        self,
        with_uploads=None):
        """Initialize a AdminBackupsJsonRequest instance."""
        # Initialize members of the class
        self.with_uploads = with_uploads

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        with_uploads =\
            dictionary.get("with_uploads")\
            if "with_uploads" in dictionary.keys()\
                else None

        # Return an object of this model
        return cls(with_uploads)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _with_uploads=self.with_uploads
        return (
            f"{self.__class__.__name__}("
            f"with_uploads={_with_uploads!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _with_uploads=self.with_uploads
        return (
            f"{self.__class__.__name__}("
            f"with_uploads={_with_uploads!s}, "
            f")"
        )
