"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourse.api_helper import APIHelper


class AdminUsersJsonRequest(object):
    """Implementation of the 'Admin Users Json Request' model.

    Attributes:
        delete_posts (bool): The model property of type bool.
        block_email (bool): The model property of type bool.
        block_urls (bool): The model property of type bool.
        block_ip (bool): The model property of type bool.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "delete_posts": "delete_posts",
        "block_email": "block_email",
        "block_urls": "block_urls",
        "block_ip": "block_ip",
    }

    _optionals = [
        "delete_posts",
        "block_email",
        "block_urls",
        "block_ip",
    ]

    def __init__(
        self,
        delete_posts=APIHelper.SKIP,
        block_email=APIHelper.SKIP,
        block_urls=APIHelper.SKIP,
        block_ip=APIHelper.SKIP):
        """Initialize a AdminUsersJsonRequest instance."""
        # Initialize members of the class
        if delete_posts is not APIHelper.SKIP:
            self.delete_posts = delete_posts
        if block_email is not APIHelper.SKIP:
            self.block_email = block_email
        if block_urls is not APIHelper.SKIP:
            self.block_urls = block_urls
        if block_ip is not APIHelper.SKIP:
            self.block_ip = block_ip

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        delete_posts =\
            dictionary.get("delete_posts")\
            if "delete_posts" in dictionary.keys()\
                else APIHelper.SKIP
        block_email =\
            dictionary.get("block_email")\
            if "block_email" in dictionary.keys()\
                else APIHelper.SKIP
        block_urls =\
            dictionary.get("block_urls")\
            if "block_urls" in dictionary.keys()\
                else APIHelper.SKIP
        block_ip =\
            dictionary.get("block_ip")\
            if "block_ip" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(delete_posts,
                   block_email,
                   block_urls,
                   block_ip)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _delete_posts=(
            self.delete_posts
            if hasattr(self, "delete_posts")
            else None
        )
        _block_email=(
            self.block_email
            if hasattr(self, "block_email")
            else None
        )
        _block_urls=(
            self.block_urls
            if hasattr(self, "block_urls")
            else None
        )
        _block_ip=(
            self.block_ip
            if hasattr(self, "block_ip")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"delete_posts={_delete_posts!r}, "
            f"block_email={_block_email!r}, "
            f"block_urls={_block_urls!r}, "
            f"block_ip={_block_ip!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _delete_posts=(
            self.delete_posts
            if hasattr(self, "delete_posts")
            else None
        )
        _block_email=(
            self.block_email
            if hasattr(self, "block_email")
            else None
        )
        _block_urls=(
            self.block_urls
            if hasattr(self, "block_urls")
            else None
        )
        _block_ip=(
            self.block_ip
            if hasattr(self, "block_ip")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"delete_posts={_delete_posts!s}, "
            f"block_email={_block_email!s}, "
            f"block_urls={_block_urls!s}, "
            f"block_ip={_block_ip!s}, "
            f")"
        )
