"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class BadgeGrouping(object):
    """Implementation of the 'BadgeGrouping' model.

    Attributes:
        id (int): The model property of type int.
        name (str): The model property of type str.
        description (str): The model property of type str.
        position (int): The model property of type int.
        system (bool): The model property of type bool.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "name": "name",
        "description": "description",
        "position": "position",
        "system": "system",
    }

    _nullables = [
        "description",
    ]

    def __init__(
        self,
        id=None,
        name=None,
        description=None,
        position=None,
        system=None):
        """Initialize a BadgeGrouping instance."""
        # Initialize members of the class
        self.id = id
        self.name = name
        self.description = description
        self.position = position
        self.system = system

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else None
        position =\
            dictionary.get("position")\
            if dictionary.get("position")\
                else None
        system =\
            dictionary.get("system")\
            if "system" in dictionary.keys()\
                else None

        # Return an object of this model
        return cls(id,
                   name,
                   description,
                   position,
                   system)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _name=self.name
        _description=self.description
        _position=self.position
        _system=self.system
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"name={_name!r}, "
            f"description={_description!r}, "
            f"position={_position!r}, "
            f"system={_system!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _name=self.name
        _description=self.description
        _position=self.position
        _system=self.system
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"name={_name!s}, "
            f"description={_description!s}, "
            f"position={_position!s}, "
            f"system={_system!s}, "
            f")"
        )
