"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class CreatedBy(object):
    """Implementation of the 'CreatedBy' model.

    Attributes:
        id (int): The model property of type int.
        username (str): The model property of type str.
        name (str): The model property of type str.
        avatar_template (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "username": "username",
        "name": "name",
        "avatar_template": "avatar_template",
    }

    def __init__(
        self,
        id=None,
        username=None,
        name=None,
        avatar_template=None):
        """Initialize a CreatedBy instance."""
        # Initialize members of the class
        self.id = id
        self.username = username
        self.name = name
        self.avatar_template = avatar_template

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        username =\
            dictionary.get("username")\
            if dictionary.get("username")\
                else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        avatar_template =\
            dictionary.get("avatar_template")\
            if dictionary.get("avatar_template")\
                else None

        # Return an object of this model
        return cls(id,
                   username,
                   name,
                   avatar_template)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _username=self.username
        _name=self.name
        _avatar_template=self.avatar_template
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"username={_username!r}, "
            f"name={_name!r}, "
            f"avatar_template={_avatar_template!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _username=self.username
        _name=self.name
        _avatar_template=self.avatar_template
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"username={_username!s}, "
            f"name={_name!s}, "
            f"avatar_template={_avatar_template!s}, "
            f")"
        )
