"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourse.api_helper import APIHelper


class CustomFields(object):
    """Implementation of the 'CustomFields' model.

    Attributes:
        first_name (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "first_name": "first_name",
    }

    _optionals = [
        "first_name",
    ]

    _nullables = [
        "first_name",
    ]

    def __init__(
        self,
        first_name=APIHelper.SKIP):
        """Initialize a CustomFields instance."""
        # Initialize members of the class
        if first_name is not APIHelper.SKIP:
            self.first_name = first_name

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        first_name =\
            dictionary.get("first_name")\
            if "first_name" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(first_name)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _first_name=(
            self.first_name
            if hasattr(self, "first_name")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"first_name={_first_name!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _first_name=(
            self.first_name
            if hasattr(self, "first_name")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"first_name={_first_name!s}, "
            f")"
        )
