"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourse.api_helper import APIHelper


class GroupUser(object):
    """Implementation of the 'GroupUser' model.

    Attributes:
        group_id (int): The model property of type int.
        user_id (int): The model property of type int.
        notification_level (int): The model property of type int.
        owner (bool): The model property of type bool.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "group_id": "group_id",
        "user_id": "user_id",
        "notification_level": "notification_level",
        "owner": "owner",
    }

    _optionals = [
        "owner",
    ]

    def __init__(
        self,
        group_id=None,
        user_id=None,
        notification_level=None,
        owner=APIHelper.SKIP):
        """Initialize a GroupUser instance."""
        # Initialize members of the class
        self.group_id = group_id
        self.user_id = user_id
        self.notification_level = notification_level
        if owner is not APIHelper.SKIP:
            self.owner = owner

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        group_id =\
            dictionary.get("group_id")\
            if dictionary.get("group_id")\
                else None
        user_id =\
            dictionary.get("user_id")\
            if dictionary.get("user_id")\
                else None
        notification_level =\
            dictionary.get("notification_level")\
            if dictionary.get("notification_level")\
                else None
        owner =\
            dictionary.get("owner")\
            if "owner" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(group_id,
                   user_id,
                   notification_level,
                   owner)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _group_id=self.group_id
        _user_id=self.user_id
        _notification_level=self.notification_level
        _owner=(
            self.owner
            if hasattr(self, "owner")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"group_id={_group_id!r}, "
            f"user_id={_user_id!r}, "
            f"notification_level={_notification_level!r}, "
            f"owner={_owner!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _group_id=self.group_id
        _user_id=self.user_id
        _notification_level=self.notification_level
        _owner=(
            self.owner
            if hasattr(self, "owner")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"group_id={_group_id!s}, "
            f"user_id={_user_id!s}, "
            f"notification_level={_notification_level!s}, "
            f"owner={_owner!s}, "
            f")"
        )
