"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class Meta1(object):
    """Implementation of the 'Meta1' model.

    Attributes:
        last_updated_at (str): The model property of type str.
        total_rows_directory_items (int): The model property of type int.
        load_more_directory_items (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "last_updated_at": "last_updated_at",
        "total_rows_directory_items": "total_rows_directory_items",
        "load_more_directory_items": "load_more_directory_items",
    }

    _nullables = [
        "last_updated_at",
    ]

    def __init__(
        self,
        last_updated_at=None,
        total_rows_directory_items=None,
        load_more_directory_items=None):
        """Initialize a Meta1 instance."""
        # Initialize members of the class
        self.last_updated_at = last_updated_at
        self.total_rows_directory_items = total_rows_directory_items
        self.load_more_directory_items = load_more_directory_items

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        last_updated_at =\
            dictionary.get("last_updated_at")\
            if dictionary.get("last_updated_at")\
                else None
        total_rows_directory_items =\
            dictionary.get("total_rows_directory_items")\
            if dictionary.get("total_rows_directory_items")\
                else None
        load_more_directory_items =\
            dictionary.get("load_more_directory_items")\
            if dictionary.get("load_more_directory_items")\
                else None

        # Return an object of this model
        return cls(last_updated_at,
                   total_rows_directory_items,
                   load_more_directory_items)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _last_updated_at=self.last_updated_at
        _total_rows_directory_items=self.total_rows_directory_items
        _load_more_directory_items=self.load_more_directory_items
        return (
            f"{self.__class__.__name__}("
            f"last_updated_at={_last_updated_at!r}, "
            f"total_rows_directory_items={_total_rows_directory_items!r}, "
            f"load_more_directory_items={_load_more_directory_items!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _last_updated_at=self.last_updated_at
        _total_rows_directory_items=self.total_rows_directory_items
        _load_more_directory_items=self.load_more_directory_items
        return (
            f"{self.__class__.__name__}("
            f"last_updated_at={_last_updated_at!s}, "
            f"total_rows_directory_items={_total_rows_directory_items!s}, "
            f"load_more_directory_items={_load_more_directory_items!s}, "
            f")"
        )
