"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class Occurrence(object):
    """Implementation of the 'Occurrence' model.

    Attributes:
        starts_at (str): The model property of type str.
        ends_at (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "starts_at": "starts_at",
        "ends_at": "ends_at",
    }

    _nullables = [
        "starts_at",
        "ends_at",
    ]

    def __init__(
        self,
        starts_at=None,
        ends_at=None):
        """Initialize a Occurrence instance."""
        # Initialize members of the class
        self.starts_at = starts_at
        self.ends_at = ends_at

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        starts_at =\
            dictionary.get("starts_at")\
            if dictionary.get("starts_at")\
                else None
        ends_at =\
            dictionary.get("ends_at")\
            if dictionary.get("ends_at")\
                else None

        # Return an object of this model
        return cls(starts_at,
                   ends_at)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _starts_at=self.starts_at
        _ends_at=self.ends_at
        return (
            f"{self.__class__.__name__}("
            f"starts_at={_starts_at!r}, "
            f"ends_at={_ends_at!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _starts_at=self.starts_at
        _ends_at=self.ends_at
        return (
            f"{self.__class__.__name__}("
            f"starts_at={_starts_at!s}, "
            f"ends_at={_ends_at!s}, "
            f")"
        )
