"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class ParentTag(object):
    """Implementation of the 'ParentTag' model.

    Attributes:
        id (int): The model property of type int.
        name (str): The model property of type str.
        slug (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "name": "name",
        "slug": "slug",
    }

    def __init__(
        self,
        id=None,
        name=None,
        slug=None):
        """Initialize a ParentTag instance."""
        # Initialize members of the class
        self.id = id
        self.name = name
        self.slug = slug

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        slug =\
            dictionary.get("slug")\
            if dictionary.get("slug")\
                else None

        # Return an object of this model
        return cls(id,
                   name,
                   slug)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _name=self.name
        _slug=self.slug
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"name={_name!r}, "
            f"slug={_slug!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _name=self.name
        _slug=self.slug
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"name={_name!s}, "
            f"slug={_slug!s}, "
            f")"
        )
