"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class PenaltyCounts(object):
    """Implementation of the 'PenaltyCounts' model.

    Attributes:
        silenced (int): The model property of type int.
        suspended (int): The model property of type int.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "silenced": "silenced",
        "suspended": "suspended",
    }

    def __init__(
        self,
        silenced=None,
        suspended=None):
        """Initialize a PenaltyCounts instance."""
        # Initialize members of the class
        self.silenced = silenced
        self.suspended = suspended

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        silenced =\
            dictionary.get("silenced")\
            if dictionary.get("silenced")\
                else None
        suspended =\
            dictionary.get("suspended")\
            if dictionary.get("suspended")\
                else None

        # Return an object of this model
        return cls(silenced,
                   suspended)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _silenced=self.silenced
        _suspended=self.suspended
        return (
            f"{self.__class__.__name__}("
            f"silenced={_silenced!r}, "
            f"suspended={_suspended!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _silenced=self.silenced
        _suspended=self.suspended
        return (
            f"{self.__class__.__name__}("
            f"silenced={_silenced!s}, "
            f"suspended={_suspended!s}, "
            f")"
        )
