"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourse.models.topic import Topic


class Post(object):
    """Implementation of the 'Post' model.

    Attributes:
        id (int): The model property of type int.
        post_number (int): The model property of type int.
        url (str): The model property of type str.
        category_slug (str): The model property of type str.
        topic (Topic): The model property of type Topic.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "post_number": "post_number",
        "url": "url",
        "category_slug": "category_slug",
        "topic": "topic",
    }

    def __init__(
        self,
        id=None,
        post_number=None,
        url=None,
        category_slug=None,
        topic=None):
        """Initialize a Post instance."""
        # Initialize members of the class
        self.id = id
        self.post_number = post_number
        self.url = url
        self.category_slug = category_slug
        self.topic = topic

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        post_number =\
            dictionary.get("post_number")\
            if dictionary.get("post_number")\
                else None
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else None
        category_slug =\
            dictionary.get("category_slug")\
            if dictionary.get("category_slug")\
                else None
        topic =\
            Topic.from_dictionary(
                dictionary.get("topic"))\
                if dictionary.get("topic") else None

        # Return an object of this model
        return cls(id,
                   post_number,
                   url,
                   category_slug,
                   topic)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _post_number=self.post_number
        _url=self.url
        _category_slug=self.category_slug
        _topic=self.topic
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"post_number={_post_number!r}, "
            f"url={_url!r}, "
            f"category_slug={_category_slug!r}, "
            f"topic={_topic!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _post_number=self.post_number
        _url=self.url
        _category_slug=self.category_slug
        _topic=self.topic
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"post_number={_post_number!s}, "
            f"url={_url!s}, "
            f"category_slug={_category_slug!s}, "
            f"topic={_topic!s}, "
            f")"
        )
