"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourse.api_helper import APIHelper


class Post1(object):
    """Implementation of the 'Post1' model.

    Attributes:
        raw (str): The model property of type str.
        edit_reason (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "raw": "raw",
        "edit_reason": "edit_reason",
    }

    _optionals = [
        "edit_reason",
    ]

    def __init__(
        self,
        raw=None,
        edit_reason=APIHelper.SKIP):
        """Initialize a Post1 instance."""
        # Initialize members of the class
        self.raw = raw
        if edit_reason is not APIHelper.SKIP:
            self.edit_reason = edit_reason

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        raw =\
            dictionary.get("raw")\
            if dictionary.get("raw")\
                else None
        edit_reason =\
            dictionary.get("edit_reason")\
            if dictionary.get("edit_reason")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(raw,
                   edit_reason)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _raw=self.raw
        _edit_reason=(
            self.edit_reason
            if hasattr(self, "edit_reason")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"raw={_raw!r}, "
            f"edit_reason={_edit_reason!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _raw=self.raw
        _edit_reason=(
            self.edit_reason
            if hasattr(self, "edit_reason")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"raw={_raw!s}, "
            f"edit_reason={_edit_reason!s}, "
            f")"
        )
