"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourse.models.silenced_by import SilencedBy


class Silence(object):
    """Implementation of the 'Silence' model.

    Attributes:
        silenced (bool): The model property of type bool.
        silence_reason (str): The model property of type str.
        full_silence_reason (str): The model property of type str.
        silenced_till (str): The model property of type str.
        silenced_at (str): The model property of type str.
        silenced_by (SilencedBy): The model property of type SilencedBy.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "silenced": "silenced",
        "silence_reason": "silence_reason",
        "full_silence_reason": "full_silence_reason",
        "silenced_till": "silenced_till",
        "silenced_at": "silenced_at",
        "silenced_by": "silenced_by",
    }

    def __init__(
        self,
        silenced=None,
        silence_reason=None,
        full_silence_reason=None,
        silenced_till=None,
        silenced_at=None,
        silenced_by=None):
        """Initialize a Silence instance."""
        # Initialize members of the class
        self.silenced = silenced
        self.silence_reason = silence_reason
        self.full_silence_reason = full_silence_reason
        self.silenced_till = silenced_till
        self.silenced_at = silenced_at
        self.silenced_by = silenced_by

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        silenced =\
            dictionary.get("silenced")\
            if "silenced" in dictionary.keys()\
                else None
        silence_reason =\
            dictionary.get("silence_reason")\
            if dictionary.get("silence_reason")\
                else None
        full_silence_reason =\
            dictionary.get("full_silence_reason")\
            if dictionary.get("full_silence_reason")\
                else None
        silenced_till =\
            dictionary.get("silenced_till")\
            if dictionary.get("silenced_till")\
                else None
        silenced_at =\
            dictionary.get("silenced_at")\
            if dictionary.get("silenced_at")\
                else None
        silenced_by =\
            SilencedBy.from_dictionary(
                dictionary.get("silenced_by"))\
                if dictionary.get("silenced_by") else None

        # Return an object of this model
        return cls(silenced,
                   silence_reason,
                   full_silence_reason,
                   silenced_till,
                   silenced_at,
                   silenced_by)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _silenced=self.silenced
        _silence_reason=self.silence_reason
        _full_silence_reason=self.full_silence_reason
        _silenced_till=self.silenced_till
        _silenced_at=self.silenced_at
        _silenced_by=self.silenced_by
        return (
            f"{self.__class__.__name__}("
            f"silenced={_silenced!r}, "
            f"silence_reason={_silence_reason!r}, "
            f"full_silence_reason={_full_silence_reason!r}, "
            f"silenced_till={_silenced_till!r}, "
            f"silenced_at={_silenced_at!r}, "
            f"silenced_by={_silenced_by!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _silenced=self.silenced
        _silence_reason=self.silence_reason
        _full_silence_reason=self.full_silence_reason
        _silenced_till=self.silenced_till
        _silenced_at=self.silenced_at
        _silenced_by=self.silenced_by
        return (
            f"{self.__class__.__name__}("
            f"silenced={_silenced!s}, "
            f"silence_reason={_silence_reason!s}, "
            f"full_silence_reason={_full_silence_reason!s}, "
            f"silenced_till={_silenced_till!s}, "
            f"silenced_at={_silenced_at!s}, "
            f"silenced_by={_silenced_by!s}, "
            f")"
        )
