"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourse.api_helper import APIHelper


class TTimerJsonRequest(object):
    """Implementation of the 'T TimerJson Request' model.

    Attributes:
        time (str): The model property of type str.
        status_type (str): The model property of type str.
        based_on_last_post (bool): The model property of type bool.
        category_id (int): The model property of type int.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "time": "time",
        "status_type": "status_type",
        "based_on_last_post": "based_on_last_post",
        "category_id": "category_id",
    }

    _optionals = [
        "time",
        "status_type",
        "based_on_last_post",
        "category_id",
    ]

    def __init__(
        self,
        time=APIHelper.SKIP,
        status_type=APIHelper.SKIP,
        based_on_last_post=APIHelper.SKIP,
        category_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a TTimerJsonRequest instance."""
        # Initialize members of the class
        if time is not APIHelper.SKIP:
            self.time = time
        if status_type is not APIHelper.SKIP:
            self.status_type = status_type
        if based_on_last_post is not APIHelper.SKIP:
            self.based_on_last_post = based_on_last_post
        if category_id is not APIHelper.SKIP:
            self.category_id = category_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        time =\
            dictionary.get("time")\
            if dictionary.get("time")\
                else APIHelper.SKIP
        status_type =\
            dictionary.get("status_type")\
            if dictionary.get("status_type")\
                else APIHelper.SKIP
        based_on_last_post =\
            dictionary.get("based_on_last_post")\
            if "based_on_last_post" in dictionary.keys()\
                else APIHelper.SKIP
        category_id =\
            dictionary.get("category_id")\
            if dictionary.get("category_id")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(time,
                   status_type,
                   based_on_last_post,
                   category_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _time=(
            self.time
            if hasattr(self, "time")
            else None
        )
        _status_type=(
            self.status_type
            if hasattr(self, "status_type")
            else None
        )
        _based_on_last_post=(
            self.based_on_last_post
            if hasattr(self, "based_on_last_post")
            else None
        )
        _category_id=(
            self.category_id
            if hasattr(self, "category_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"time={_time!r}, "
            f"status_type={_status_type!r}, "
            f"based_on_last_post={_based_on_last_post!r}, "
            f"category_id={_category_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _time=(
            self.time
            if hasattr(self, "time")
            else None
        )
        _status_type=(
            self.status_type
            if hasattr(self, "status_type")
            else None
        )
        _based_on_last_post=(
            self.based_on_last_post
            if hasattr(self, "based_on_last_post")
            else None
        )
        _category_id=(
            self.category_id
            if hasattr(self, "category_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"time={_time!s}, "
            f"status_type={_status_type!s}, "
            f"based_on_last_post={_based_on_last_post!s}, "
            f"category_id={_category_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
