"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourse.api_helper import APIHelper


class Tag4(object):
    """Implementation of the 'Tag4' model.

    Attributes:
        id (int): The model property of type int.
        name (str): The model property of type str.
        topic_count (int): The model property of type int.
        staff (bool): The model property of type bool.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "name": "name",
        "topic_count": "topic_count",
        "staff": "staff",
    }

    _optionals = [
        "id",
        "name",
        "topic_count",
        "staff",
    ]

    def __init__(
        self,
        id=APIHelper.SKIP,
        name=APIHelper.SKIP,
        topic_count=APIHelper.SKIP,
        staff=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Tag4 instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if name is not APIHelper.SKIP:
            self.name = name
        if topic_count is not APIHelper.SKIP:
            self.topic_count = topic_count
        if staff is not APIHelper.SKIP:
            self.staff = staff

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        topic_count =\
            dictionary.get("topic_count")\
            if dictionary.get("topic_count")\
                else APIHelper.SKIP
        staff =\
            dictionary.get("staff")\
            if "staff" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(id,
                   name,
                   topic_count,
                   staff,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _topic_count=(
            self.topic_count
            if hasattr(self, "topic_count")
            else None
        )
        _staff=(
            self.staff
            if hasattr(self, "staff")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"name={_name!r}, "
            f"topic_count={_topic_count!r}, "
            f"staff={_staff!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _topic_count=(
            self.topic_count
            if hasattr(self, "topic_count")
            else None
        )
        _staff=(
            self.staff
            if hasattr(self, "staff")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"name={_name!s}, "
            f"topic_count={_topic_count!s}, "
            f"staff={_staff!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
