"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourse.models.tag_group import TagGroup


class TagGroupsJsonResponse(object):
    """Implementation of the 'Tag GroupsJson Response' model.

    Attributes:
        tag_groups (List[TagGroup]): The model property of type List[TagGroup].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "tag_groups": "tag_groups",
    }

    def __init__(
        self,
        tag_groups=None):
        """Initialize a TagGroupsJsonResponse instance."""
        # Initialize members of the class
        self.tag_groups = tag_groups

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        tag_groups = None
        if dictionary.get("tag_groups") is not None:
            tag_groups = [
                TagGroup.from_dictionary(x)
                    for x in dictionary.get("tag_groups")
            ]

        # Return an object of this model
        return cls(tag_groups)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _tag_groups=self.tag_groups
        return (
            f"{self.__class__.__name__}("
            f"tag_groups={_tag_groups!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _tag_groups=self.tag_groups
        return (
            f"{self.__class__.__name__}("
            f"tag_groups={_tag_groups!s}, "
            f")"
        )
