"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourse.api_helper import APIHelper
from discourse.models.topic_list_1 import TopicList1
from discourse.models.user_1 import User1


class TopicsPrivateMessagesJsonResponse(object):
    """Implementation of the 'Topics Private Messages Json Response' model.

    Attributes:
        users (List[User1]): The model property of type List[User1].
        primary_groups (List[Any]): The model property of type List[Any].
        topic_list (TopicList1): The model property of type TopicList1.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "users": "users",
        "primary_groups": "primary_groups",
        "topic_list": "topic_list",
    }

    _optionals = [
        "users",
        "primary_groups",
        "topic_list",
    ]

    def __init__(
        self,
        users=APIHelper.SKIP,
        primary_groups=APIHelper.SKIP,
        topic_list=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a TopicsPrivateMessagesJsonResponse instance."""
        # Initialize members of the class
        if users is not APIHelper.SKIP:
            self.users = users
        if primary_groups is not APIHelper.SKIP:
            self.primary_groups = primary_groups
        if topic_list is not APIHelper.SKIP:
            self.topic_list = topic_list

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        users = None
        if dictionary.get("users") is not None:
            users = [
                User1.from_dictionary(x)
                    for x in dictionary.get("users")
            ]
        else:
            users = APIHelper.SKIP
        primary_groups =\
            dictionary.get("primary_groups")\
            if dictionary.get("primary_groups")\
                else APIHelper.SKIP
        topic_list =\
            TopicList1.from_dictionary(
                dictionary.get("topic_list"))\
                if "topic_list" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(users,
                   primary_groups,
                   topic_list,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _users=(
            self.users
            if hasattr(self, "users")
            else None
        )
        _primary_groups=(
            self.primary_groups
            if hasattr(self, "primary_groups")
            else None
        )
        _topic_list=(
            self.topic_list
            if hasattr(self, "topic_list")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"users={_users!r}, "
            f"primary_groups={_primary_groups!r}, "
            f"topic_list={_topic_list!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _users=(
            self.users
            if hasattr(self, "users")
            else None
        )
        _primary_groups=(
            self.primary_groups
            if hasattr(self, "primary_groups")
            else None
        )
        _topic_list=(
            self.topic_list
            if hasattr(self, "topic_list")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"users={_users!s}, "
            f"primary_groups={_primary_groups!s}, "
            f"topic_list={_topic_list!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
