"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourse.api_helper import APIHelper


class Topic5(object):
    """Implementation of the 'Topic5' model.

    Attributes:
        title (str): The model property of type str.
        category_id (int): The model property of type int.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "title": "title",
        "category_id": "category_id",
    }

    _optionals = [
        "title",
        "category_id",
    ]

    def __init__(
        self,
        title=APIHelper.SKIP,
        category_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Topic5 instance."""
        # Initialize members of the class
        if title is not APIHelper.SKIP:
            self.title = title
        if category_id is not APIHelper.SKIP:
            self.category_id = category_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        title =\
            dictionary.get("title")\
            if dictionary.get("title")\
                else APIHelper.SKIP
        category_id =\
            dictionary.get("category_id")\
            if dictionary.get("category_id")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(title,
                   category_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _category_id=(
            self.category_id
            if hasattr(self, "category_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"title={_title!r}, "
            f"category_id={_category_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _category_id=(
            self.category_id
            if hasattr(self, "category_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"title={_title!s}, "
            f"category_id={_category_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
