"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class UJsonResponse1(object):
    """Implementation of the 'U Json Response1' model.

    Attributes:
        success (str): The model property of type str.
        user (Any): The model property of type Any.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "success": "success",
        "user": "user",
    }

    def __init__(
        self,
        success=None,
        user=None):
        """Initialize a UJsonResponse1 instance."""
        # Initialize members of the class
        self.success = success
        self.user = user

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        success =\
            dictionary.get("success")\
            if dictionary.get("success")\
                else None
        user =\
            dictionary.get("user")\
            if dictionary.get("user")\
                else None

        # Return an object of this model
        return cls(success,
                   user)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _success=self.success
        _user=self.user
        return (
            f"{self.__class__.__name__}("
            f"success={_success!r}, "
            f"user={_user!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _success=self.success
        _user=self.user
        return (
            f"{self.__class__.__name__}("
            f"success={_success!s}, "
            f"user={_user!s}, "
            f")"
        )
