"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourse.api_helper import APIHelper
from discourse.models.metadata import Metadata


class UploadsGeneratePresignedPutJsonRequest(object):
    """Implementation of the 'Uploads Generate Presigned PutJson Request' model.

    Attributes:
        mtype (Type): The model property of type Type.
        file_name (str): The model property of type str.
        file_size (int): File size should be represented in bytes.
        metadata (Metadata): The model property of type Metadata.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": "type",
        "file_name": "file_name",
        "file_size": "file_size",
        "metadata": "metadata",
    }

    _optionals = [
        "metadata",
    ]

    def __init__(
        self,
        mtype=None,
        file_name=None,
        file_size=None,
        metadata=APIHelper.SKIP):
        """Initialize a UploadsGeneratePresignedPutJsonRequest instance."""
        # Initialize members of the class
        self.mtype = mtype
        self.file_name = file_name
        self.file_size = file_size
        if metadata is not APIHelper.SKIP:
            self.metadata = metadata

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else None
        file_name =\
            dictionary.get("file_name")\
            if dictionary.get("file_name")\
                else None
        file_size =\
            dictionary.get("file_size")\
            if dictionary.get("file_size")\
                else None
        metadata =\
            Metadata.from_dictionary(
                dictionary.get("metadata"))\
                if "metadata" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(mtype,
                   file_name,
                   file_size,
                   metadata)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mtype=self.mtype
        _file_name=self.file_name
        _file_size=self.file_size
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!r}, "
            f"file_name={_file_name!r}, "
            f"file_size={_file_size!r}, "
            f"metadata={_metadata!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mtype=self.mtype
        _file_name=self.file_name
        _file_size=self.file_size
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!s}, "
            f"file_name={_file_name!s}, "
            f"file_size={_file_size!s}, "
            f"metadata={_metadata!s}, "
            f")"
        )
