"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class UploadsAbortMultipartJsonRequest(object):
    """Implementation of the 'Uploads Abort MultipartJson Request' model.

    Attributes:
        external_upload_identifier (str): The identifier of the multipart upload in
            the external storage provider. This is the multipart upload_id in AWS S3.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "external_upload_identifier": "external_upload_identifier",
    }

    def __init__(
        self,
        external_upload_identifier=None):
        """Initialize a UploadsAbortMultipartJsonRequest instance."""
        # Initialize members of the class
        self.external_upload_identifier = external_upload_identifier

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        external_upload_identifier =\
            dictionary.get("external_upload_identifier")\
            if dictionary.get("external_upload_identifier")\
                else None

        # Return an object of this model
        return cls(external_upload_identifier)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _external_upload_identifier=self.external_upload_identifier
        return (
            f"{self.__class__.__name__}("
            f"external_upload_identifier={_external_upload_identifier!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _external_upload_identifier=self.external_upload_identifier
        return (
            f"{self.__class__.__name__}("
            f"external_upload_identifier={_external_upload_identifier!s}, "
            f")"
        )
