"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from discourse.api_helper import APIHelper


class UploadsCompleteExternalUploadJsonRequest(object):
    """Implementation of the 'Uploads Complete External UploadJson Request' model.

    Attributes:
        unique_identifier (str): The unique identifier returned in the original
            /generate-presigned-put request.
        for_private_message (str): Optionally set this to true if the upload is for a
            private message.
        for_site_setting (str): Optionally set this to true if the upload is for a
            site setting.
        pasted (str): Optionally set this to true if the upload was pasted into the
            upload area. This will convert PNG files to JPEG.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "unique_identifier": "unique_identifier",
        "for_private_message": "for_private_message",
        "for_site_setting": "for_site_setting",
        "pasted": "pasted",
    }

    _optionals = [
        "for_private_message",
        "for_site_setting",
        "pasted",
    ]

    def __init__(
        self,
        unique_identifier=None,
        for_private_message=APIHelper.SKIP,
        for_site_setting=APIHelper.SKIP,
        pasted=APIHelper.SKIP):
        """Initialize a UploadsCompleteExternalUploadJsonRequest instance."""
        # Initialize members of the class
        self.unique_identifier = unique_identifier
        if for_private_message is not APIHelper.SKIP:
            self.for_private_message = for_private_message
        if for_site_setting is not APIHelper.SKIP:
            self.for_site_setting = for_site_setting
        if pasted is not APIHelper.SKIP:
            self.pasted = pasted

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        unique_identifier =\
            dictionary.get("unique_identifier")\
            if dictionary.get("unique_identifier")\
                else None
        for_private_message =\
            dictionary.get("for_private_message")\
            if dictionary.get("for_private_message")\
                else APIHelper.SKIP
        for_site_setting =\
            dictionary.get("for_site_setting")\
            if dictionary.get("for_site_setting")\
                else APIHelper.SKIP
        pasted =\
            dictionary.get("pasted")\
            if dictionary.get("pasted")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(unique_identifier,
                   for_private_message,
                   for_site_setting,
                   pasted)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _unique_identifier=self.unique_identifier
        _for_private_message=(
            self.for_private_message
            if hasattr(self, "for_private_message")
            else None
        )
        _for_site_setting=(
            self.for_site_setting
            if hasattr(self, "for_site_setting")
            else None
        )
        _pasted=(
            self.pasted
            if hasattr(self, "pasted")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"unique_identifier={_unique_identifier!r}, "
            f"for_private_message={_for_private_message!r}, "
            f"for_site_setting={_for_site_setting!r}, "
            f"pasted={_pasted!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _unique_identifier=self.unique_identifier
        _for_private_message=(
            self.for_private_message
            if hasattr(self, "for_private_message")
            else None
        )
        _for_site_setting=(
            self.for_site_setting
            if hasattr(self, "for_site_setting")
            else None
        )
        _pasted=(
            self.pasted
            if hasattr(self, "pasted")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"unique_identifier={_unique_identifier!s}, "
            f"for_private_message={_for_private_message!s}, "
            f"for_site_setting={_for_site_setting!s}, "
            f"pasted={_pasted!s}, "
            f")"
        )
