"""discourse.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
class UserBadge(object):
    """Implementation of the 'UserBadge' model.

    Attributes:
        id (int): The model property of type int.
        granted_at (str): The model property of type str.
        grouping_position (int): The model property of type int.
        is_favorite (str): The model property of type str.
        can_favorite (bool): The model property of type bool.
        badge_id (int): The model property of type int.
        granted_by_id (int): The model property of type int.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "granted_at": "granted_at",
        "grouping_position": "grouping_position",
        "is_favorite": "is_favorite",
        "can_favorite": "can_favorite",
        "badge_id": "badge_id",
        "granted_by_id": "granted_by_id",
    }

    _nullables = [
        "is_favorite",
    ]

    def __init__(
        self,
        id=None,
        granted_at=None,
        grouping_position=None,
        is_favorite=None,
        can_favorite=None,
        badge_id=None,
        granted_by_id=None):
        """Initialize a UserBadge instance."""
        # Initialize members of the class
        self.id = id
        self.granted_at = granted_at
        self.grouping_position = grouping_position
        self.is_favorite = is_favorite
        self.can_favorite = can_favorite
        self.badge_id = badge_id
        self.granted_by_id = granted_by_id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        granted_at =\
            dictionary.get("granted_at")\
            if dictionary.get("granted_at")\
                else None
        grouping_position =\
            dictionary.get("grouping_position")\
            if dictionary.get("grouping_position")\
                else None
        is_favorite =\
            dictionary.get("is_favorite")\
            if dictionary.get("is_favorite")\
                else None
        can_favorite =\
            dictionary.get("can_favorite")\
            if "can_favorite" in dictionary.keys()\
                else None
        badge_id =\
            dictionary.get("badge_id")\
            if dictionary.get("badge_id")\
                else None
        granted_by_id =\
            dictionary.get("granted_by_id")\
            if dictionary.get("granted_by_id")\
                else None

        # Return an object of this model
        return cls(id,
                   granted_at,
                   grouping_position,
                   is_favorite,
                   can_favorite,
                   badge_id,
                   granted_by_id)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=self.id
        _granted_at=self.granted_at
        _grouping_position=self.grouping_position
        _is_favorite=self.is_favorite
        _can_favorite=self.can_favorite
        _badge_id=self.badge_id
        _granted_by_id=self.granted_by_id
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"granted_at={_granted_at!r}, "
            f"grouping_position={_grouping_position!r}, "
            f"is_favorite={_is_favorite!r}, "
            f"can_favorite={_can_favorite!r}, "
            f"badge_id={_badge_id!r}, "
            f"granted_by_id={_granted_by_id!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=self.id
        _granted_at=self.granted_at
        _grouping_position=self.grouping_position
        _is_favorite=self.is_favorite
        _can_favorite=self.can_favorite
        _badge_id=self.badge_id
        _granted_by_id=self.granted_by_id
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"granted_at={_granted_at!s}, "
            f"grouping_position={_grouping_position!s}, "
            f"is_favorite={_is_favorite!s}, "
            f"can_favorite={_can_favorite!s}, "
            f"badge_id={_badge_id!s}, "
            f"granted_by_id={_granted_by_id!s}, "
            f")"
        )
