"""discourseapidocumentation.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from discourseapidocumentation.api_helper import (
    APIHelper,
)
from discourseapidocumentation.apis.base_api import (
    BaseApi,
)
from discourseapidocumentation.configuration import (
    Server,
)
from discourseapidocumentation.http.http_method_enum import (
    HttpMethodEnum,
)
from discourseapidocumentation.models.latest_json_response import (
    LatestJsonResponse,
)
from discourseapidocumentation.models.t_change_timestamp_json_response import (
    TChangeTimestampJsonResponse,
)
from discourseapidocumentation.models.t_invite_group_json_response import (
    TInviteGroupJsonResponse,
)
from discourseapidocumentation.models.t_invite_json_response import (
    TInviteJsonResponse,
)
from discourseapidocumentation.models.t_json_response import (
    TJsonResponse,
)
from discourseapidocumentation.models.t_json_response_1 import (
    TJsonResponse1,
)
from discourseapidocumentation.models.t_notifications_json_response import (
    TNotificationsJsonResponse,
)
from discourseapidocumentation.models.t_posts_json_response import (
    TPostsJsonResponse,
)
from discourseapidocumentation.models.t_status_json_response import (
    TStatusJsonResponse,
)
from discourseapidocumentation.models.t_timer_json_response import (
    TTimerJsonResponse,
)
from discourseapidocumentation.models.top_json_response import (
    TopJsonResponse,
)


class TopicsApi(BaseApi):
    """A Controller to access Endpoints in the discourseapidocumentation API."""

    def __init__(self, config):
        """Initialize TopicsApi object."""
        super(TopicsApi, self).__init__(config)

    def get_specific_posts_from_topic(self,
                                      api_key,
                                      api_username,
                                      id):
        """Perform a GET request to /t/{id}/posts.json.

        Args:
            api_key (str): The request header parameter.
            api_username (str): The request header parameter.
            id (str): The request template parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. specific posts

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/t/{id}/posts.json")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Api-Key")
                .value(api_key)
                .is_required(True))
            .header_param(Parameter()
                .key("Api-Username")
                .value(api_username)
                .is_required(True))
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(TPostsJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def get_topic(self,
                  api_key,
                  api_username,
                  id):
        """Perform a GET request to /t/{id}.json.

        Args:
            api_key (str): The request header parameter.
            api_username (str): The request header parameter.
            id (str): The request template parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. specific posts

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/t/{id}.json")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Api-Key")
                .value(api_key)
                .is_required(True))
            .header_param(Parameter()
                .key("Api-Username")
                .value(api_username)
                .is_required(True))
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(TJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def remove_topic(self,
                     api_key,
                     api_username,
                     id):
        """Perform a DELETE request to /t/{id}.json.

        Args:
            api_key (str): The request header parameter.
            api_username (str): The request header parameter.
            id (str): The request template parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. specific posts

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/t/{id}.json")
            .http_method(HttpMethodEnum.DELETE)
            .header_param(Parameter()
                .key("Api-Key")
                .value(api_key)
                .is_required(True))
            .header_param(Parameter()
                .key("Api-Username")
                .value(api_username)
                .is_required(True))
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True)),
        ).response(
            ResponseHandler()
            .is_api_response(True),
        ).execute()

    def update_topic(self,
                     api_key,
                     api_username,
                     id,
                     body=None):
        """Perform a PUT request to /t/-/{id}.json.

        Args:
            api_key (str): The request header parameter.
            api_username (str): The request header parameter.
            id (str): The request template parameter.
            body (TJsonRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. topic updated

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/t/-/{id}.json")
            .http_method(HttpMethodEnum.PUT)
            .header_param(Parameter()
                .key("Api-Key")
                .value(api_key)
                .is_required(True))
            .header_param(Parameter()
                .key("Api-Username")
                .value(api_username)
                .is_required(True))
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(TJsonResponse1.from_dictionary)
            .is_api_response(True),
        ).execute()

    def invite_to_topic(self,
                        api_key,
                        api_username,
                        id,
                        body=None):
        """Perform a POST request to /t/{id}/invite.json.

        Args:
            api_key (str): The request header parameter.
            api_username (str): The request header parameter.
            id (str): The request template parameter.
            body (TInviteJsonRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. topic updated

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/t/{id}/invite.json")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("Api-Key")
                .value(api_key)
                .is_required(True))
            .header_param(Parameter()
                .key("Api-Username")
                .value(api_username)
                .is_required(True))
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(TInviteJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def invite_group_to_topic(self,
                              api_key,
                              api_username,
                              id,
                              body=None):
        """Perform a POST request to /t/{id}/invite-group.json.

        Args:
            api_key (str): The request header parameter.
            api_username (str): The request header parameter.
            id (str): The request template parameter.
            body (TInviteGroupJsonRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. invites to a PM

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/t/{id}/invite-group.json")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("Api-Key")
                .value(api_key)
                .is_required(True))
            .header_param(Parameter()
                .key("Api-Username")
                .value(api_username)
                .is_required(True))
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(TInviteGroupJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def bookmark_topic(self,
                       api_key,
                       api_username,
                       id):
        """Perform a PUT request to /t/{id}/bookmark.json.

        Args:
            api_key (str): The request header parameter.
            api_username (str): The request header parameter.
            id (str): The request template parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. topic updated

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/t/{id}/bookmark.json")
            .http_method(HttpMethodEnum.PUT)
            .header_param(Parameter()
                .key("Api-Key")
                .value(api_key)
                .is_required(True))
            .header_param(Parameter()
                .key("Api-Username")
                .value(api_username)
                .is_required(True))
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True)),
        ).response(
            ResponseHandler()
            .is_api_response(True),
        ).execute()

    def update_topic_status(self,
                            api_key,
                            api_username,
                            id,
                            body=None):
        """Perform a PUT request to /t/{id}/status.json.

        Args:
            api_key (str): The request header parameter.
            api_username (str): The request header parameter.
            id (str): The request template parameter.
            body (TStatusJsonRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. topic updated

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/t/{id}/status.json")
            .http_method(HttpMethodEnum.PUT)
            .header_param(Parameter()
                .key("Api-Key")
                .value(api_key)
                .is_required(True))
            .header_param(Parameter()
                .key("Api-Username")
                .value(api_username)
                .is_required(True))
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(TStatusJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def list_latest_topics(self,
                           api_key,
                           api_username,
                           order=None,
                           ascending=None,
                           per_page=None):
        """Perform a GET request to /latest.json.

        Args:
            api_key (str): The request header parameter.
            api_username (str): The request header parameter.
            order (str, optional): Enum: `default`, `created`, `activity`, `views`,
                `posts`, `category`, `likes`, `op_likes`, `posters`
            ascending (str, optional): Defaults to `desc`, add `ascending=true` to
                sort asc
            per_page (int, optional): Maximum number of topics returned, between 1-100

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. topic updated

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/latest.json")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Api-Key")
                .value(api_key)
                .is_required(True))
            .header_param(Parameter()
                .key("Api-Username")
                .value(api_username)
                .is_required(True))
            .query_param(Parameter()
                .key("order")
                .value(order))
            .query_param(Parameter()
                .key("ascending")
                .value(ascending))
            .query_param(Parameter()
                .key("per_page")
                .value(per_page))
            .header_param(Parameter()
                .key("accept")
                .value("application/json")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(LatestJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def list_top_topics(self,
                        api_key,
                        api_username,
                        period=None,
                        per_page=None):
        """Perform a GET request to /top.json.

        Args:
            api_key (str): The request header parameter.
            api_username (str): The request header parameter.
            period (str, optional): Enum: `all`, `yearly`, `quarterly`, `monthly`,
                `weekly`, `daily`
            per_page (int, optional): Maximum number of topics returned, between 1-100

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/top.json")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Api-Key")
                .value(api_key)
                .is_required(True))
            .header_param(Parameter()
                .key("Api-Username")
                .value(api_username)
                .is_required(True))
            .query_param(Parameter()
                .key("period")
                .value(period))
            .query_param(Parameter()
                .key("per_page")
                .value(per_page))
            .header_param(Parameter()
                .key("accept")
                .value("application/json")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(TopJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def set_notification_level(self,
                               api_key,
                               api_username,
                               id,
                               body=None):
        """Perform a POST request to /t/{id}/notifications.json.

        Args:
            api_key (str): The request header parameter.
            api_username (str): The request header parameter.
            id (str): The request template parameter.
            body (TNotificationsJsonRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. topic updated

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/t/{id}/notifications.json")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("Api-Key")
                .value(api_key)
                .is_required(True))
            .header_param(Parameter()
                .key("Api-Username")
                .value(api_username)
                .is_required(True))
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(TNotificationsJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def update_topic_timestamp(self,
                               api_key,
                               api_username,
                               id,
                               body=None):
        """Perform a PUT request to /t/{id}/change-timestamp.json.

        Args:
            api_key (str): The request header parameter.
            api_username (str): The request header parameter.
            id (str): The request template parameter.
            body (TChangeTimestampJsonRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. topic updated

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/t/{id}/change-timestamp.json")
            .http_method(HttpMethodEnum.PUT)
            .header_param(Parameter()
                .key("Api-Key")
                .value(api_key)
                .is_required(True))
            .header_param(Parameter()
                .key("Api-Username")
                .value(api_username)
                .is_required(True))
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(TChangeTimestampJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def create_topic_timer(self,
                           api_key,
                           api_username,
                           id,
                           body=None):
        """Perform a POST request to /t/{id}/timer.json.

        Args:
            api_key (str): The request header parameter.
            api_username (str): The request header parameter.
            id (str): The request template parameter.
            body (TTimerJsonRequest, optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. topic updated

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/t/{id}/timer.json")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("Api-Key")
                .value(api_key)
                .is_required(True))
            .header_param(Parameter()
                .key("Api-Username")
                .value(api_username)
                .is_required(True))
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(TTimerJsonResponse.from_dictionary)
            .is_api_response(True),
        ).execute()

    def get_topic_by_external_id(self,
                                 external_id):
        """Perform a GET request to /t/external_id/{external_id}.json.

        Args:
            external_id (str): The request template parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers.

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/t/external_id/{external_id}.json")
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                .key("external_id")
                .value(external_id)
                .is_required(True)
                .should_encode(True)),
        ).response(
            ResponseHandler()
            .is_api_response(True),
        ).execute()
